---
title: Глава 10. Соединения
subtitle: SQL Lab in JupyterLab
# license: CC-BY-4.0
github: https://github.com/magus1968/learning-sql
subject: Technical Portfolio
venue: GitHub & GitVerse Pages
# abstract: |
#   В последнем запросе главы, в разделе _Этот таинственный null_, увидим причину, по которой для усечения строк в дальнейшем будет использоваться Pandas.
authors:
  - name: Alex Smirnov
    email: a@smirnovs.pro
    corresponding: true
    affiliations: Data & BI Analyst
date: 2026-09-25
abbreviations:
    MyST: Markedly Structured Text
    Jupyter Book: Инструмент сборки статических сайтов
    JupySQL: Расширение для запуска и подсветки SQL в Jupyter
    GitHub: Платформа хостинга репозиториев и совместной разработки
    GitHub Pages: Сервис бесплатного хостинга статических сайтов
    GitHub Actions: Платформа автоматизации рабочих процессов и CI/CD
    Pandas: Библиотека Python для анализа и обработки данных
    Polars: Мощный аналог Pandas на Rust/Python
---

In [1]:
import pandas as pd
import sql
import sqlalchemy as sa

pd.set_option('display.max_rows', 20)

%load_ext sql
%config SqlMagic.displaycon = False
%config SqlMagic.autopandas = True

connection_url = sa.engine.URL.create(
    drivername='mysql+pymysql',
    host='localhost',
    port=3306,
    database='sakila',
    username='root',
    password='*UHB5rdx',
)
engine = sa.create_engine(connection_url)

%sql engine

print(f"Pandas ver. {pd.__version__}: порог усечения строк уменьшен до 20")
print(f"SQLAlchemy ver. {sa.__version__}: подключение создано")
print(f"JupySQL ver. {sql.__version__}: подключен через SQLAlchemy Engine")

Pandas ver. 3.0.5: порог усечения строк уменьшен до 20
SQLAlchemy ver. 2.0.52: подключение создано
JupySQL ver. 0.11.1: подключен через SQLAlchemy Engine

К настоящему времени вы уже должны быть хорошо знакомы с концепцией *врутреннего* соединения, которая была представлена в главе 5.

:::{figure} ./media/inner-join.png
:alt: INNER JOIN
:align: center
Внутреннее соединение **INNER JOIN**
:::

В этой главе рассматриваются другие способы соединения таблиц, включая _**внешнее**_ соединение и _**перекрестное**_ соединение.

## Внешние соединения

До сих пор во всех примерах, включающих несколько таблиц, нас не волновало, что условия соединения могут не найти совпадений для всех строк таблицы.

Например, таблица **inventory** содержит строку для каждого фильма, доступного для проката, но из 1000 строк в таблице **film** только 958 имеют одну или несколько строк в таблице **inventory**. Остальные 42 фильма для проката недоступны (возможно это новинки, которые должны прибыть в пункты проката со дня на день), поэтому идентификаторы этих фильмов в таблице **inventory** отсутствуют.

Следующий запрос подсчитывает количество доступных копий каждого фильма с помощью соединения этих двух таблиц:

In [3]:
%%sql
SELECT
    f.film_id,
    f.title,
    COUNT(*) AS num_copies
FROM film f
    INNER JOIN inventory i
        ON f.film_id = i.film_id
GROUP BY
    f.film_id,
    f.title;

958 rows affected.

     film_id              title  num_copies
0          1   ACADEMY DINOSAUR           8
1          2     ACE GOLDFINGER           3
2          3   ADAPTATION HOLES           4
3          4   AFFAIR PREJUDICE           7
4          5        AFRICAN EGG           3
..       ...                ...         ...
953      996     YOUNG LANGUAGE           2
954      997         YOUTH KICK           2
955      998       ZHIVAGO CORE           2
956      999  ZOOLANDER FICTION           5
957     1000          ZORRO ARK           8

[958 rows x 3 columns]

Хотя можно было бы ожидать, что будет возвращено 1000 строк (по одной для каждого фильма), запрос возвращает только 958 строк.

Дело в том, что запрос использует *внутреннее* соединение, которое возвращает только строки, удовлетворяющие условию соединения. Например, фильм *Alice Fantasia* (**film_id** равен 14) не отображается в результатах, потому что для него нет строк в таблице **inventory**.

Если хотите, чтобы запрос возвращал все 1000 фильмов, независимо от того, имеются ли соответствующие строки в таблице **inventory**, можете использовать *внешнее* соединение, которое, по сути, делает условие соединения необязательным:

In [9]:
%%sql
SELECT
    f.film_id,
    f.title,
    COUNT(i.inventory_id) AS num_copies
FROM film f
    LEFT OUTER JOIN inventory i
        ON f.film_id = i.film_id
GROUP BY
    f.film_id,
    f.title
ORDER BY num_copies;

1000 rows affected.

     film_id                 title  num_copies
0         14        ALICE FANTASIA           0
1         33           APOLLO TEEN           0
2         36        ARGONAUTS TOWN           0
3         38         ARK RIDGEMONT           0
4         41  ARSENIC INDEPENDENCE           0
..       ...                   ...         ...
995      897          TORQUE BOUND           8
996      911           TRIP NEWTON           8
997      945       VIRGINIAN PLUTO           8
998      973             WIFE TURN           8
999     1000             ZORRO ARK           8

[1000 rows x 3 columns]

Как видите, запрос теперь возвращает все 1000 строк из таблицы **film**, при этом 42 строки из общего количества строк (включая фильм *Alice Fantasia*) имеют значение 0 в столбце **num_copies**, что указывает на отсутствие доступных для проката копий.

Вот описание изменений по сравнению с предыдущей версией запроса.
- Определение соединения было изменено с `inner` на `left outer`, что указывает серверу на необходимость включения всех строк из таблицы в левой части соединения (в данном случае **film**) и включения столбцов из таблицы с правой стороны соединения (**inventory**), если соединение прошло успешно.
- Определение столбца **num_copies** было изменено с `count(*)` на `count(i.inventory_id`; это выражение подсчитывает количество значений столбца **inventory.inventory_id** _не равных_ `null`.

Давайте удалим предложение `group by` и отфильтруем большинство строк, чтобы ясно видеть различия между внутренними и внешними соединениями. Вот запрос с использованием внутреннего соединения и условия фильтрации для возврата всего лишь нескольких фильмов:

In [2]:
%%sql
SELECT
    f.film_id,
    f.title,
    i.inventory_id
FROM film f
    INNER JOIN inventory i
        ON f.film_id = i.film_id
WHERE f.film_id BETWEEN 13 AND 15;

10 rows affected.

   film_id         title  inventory_id
0       13   ALI FOREVER            67
1       13   ALI FOREVER            68
2       13   ALI FOREVER            69
3       13   ALI FOREVER            70
4       15  ALIEN CENTER            71
5       15  ALIEN CENTER            72
6       15  ALIEN CENTER            73
7       15  ALIEN CENTER            74
8       15  ALIEN CENTER            75
9       15  ALIEN CENTER            76

Результаты показывают, что в прокате имеется четыре копии *Ali Forever* и шесть копий *Alien Center*.

Вот так выглядит тот же запрос. но с использованием внешнего соединения:

In [3]:
%%sql
SELECT
    f.film_id,
    f.title,
    i.inventory_id
FROM film f
    LEFT JOIN inventory i
        ON f.film_id = i.film_id
WHERE f.film_id BETWEEN 13 AND 15;

11 rows affected.

    film_id           title  inventory_id
0        13     ALI FOREVER          67.0
1        13     ALI FOREVER          68.0
2        13     ALI FOREVER          69.0
3        13     ALI FOREVER          70.0
4        14  ALICE FANTASIA           NaN
5        15    ALIEN CENTER          71.0
6        15    ALIEN CENTER          72.0
7        15    ALIEN CENTER          73.0
8        15    ALIEN CENTER          74.0
9        15    ALIEN CENTER          75.0
10       15    ALIEN CENTER          76.0

Результаты для *Ali Forever* и *Alien Center* остаются прежними, но появляется одна новая строка для *Alice Fantasia* со значением `null` (NaN) в столбце **inventory.inventory_id**. В этом примере показано, как внешнее соединение добавляет значения столбцов без ограничения на количество строк, возвращаемых запросом. Если условие соединения не выполняется (как в случае *Alice Fantasia*), то любые столбцы, извлеченные из внешне соединенной таблицы, будут иметь  значения `null`.

### Левое и правое внешние соединения

В примерах внешнего соединания в предыдущем разделе было указано `left outer join`. Ключевое слово `left` указывает, что таблица в левой части соединения отвечает за определение количества строк в результирующем наборе, тогда как таблица в правой части используется для предоставления значений столбца всякий раз, когда найдено совпадение.

:::{figure} ./media/left-join.png
:alt: LEFT JOIN
:align: center
Внешнее соединение **LEFT JOIN**
:::

Однако можно указать и правое внешнее соединение – в этом случае таблица с правой стороны от `right outer join` отвечает за определение количества строк в результирующем наборе, тогда как таблица с левой стороны используется для предоставления значений столбцов.

:::{figure} ./media/right-join.png
:alt: RIGHT JOIN
:align: center
Внешнее соединение **RIGHT JOIN**
:::

Вот последний запрос из предыдущего раздела, в котором используется правое внешнее соединение вместо левого:

In [4]:
%%sql
SELECT
    f.film_id,
    f.title,
    i.inventory_id
FROM inventory i
    RIGHT OUTER JOIN film f
        ON f.film_id = i.film_id
WHERE f.film_id BETWEEN 13 AND 15;

11 rows affected.

    film_id           title  inventory_id
0        13     ALI FOREVER          67.0
1        13     ALI FOREVER          68.0
2        13     ALI FOREVER          69.0
3        13     ALI FOREVER          70.0
4        14  ALICE FANTASIA           NaN
5        15    ALIEN CENTER          71.0
6        15    ALIEN CENTER          72.0
7        15    ALIEN CENTER          73.0
8        15    ALIEN CENTER          74.0
9        15    ALIEN CENTER          75.0
10       15    ALIEN CENTER          76.0

Заметим, что обе версии запроса выполняют внешнее соединение. Ключевые слова `left` и `right` служат только для того, чтобы сообщить серверу, в какой таблице разрешено иметь пробелы в данных.

Если вы хотите внешне соединить таблицы А и В и хотите, чтобы в результирующем наборе присутствовали все строки из А (с дополнительными столбцами из В всякий раз, когда есть соответствующие данные), то можете указать либо `А left outer join B` либо `B right outer join A`.

:::{note}
Поскольку правые внешние соединения встречаются крайне редко (и не все серверы баз данных их поддерживают), лучше всегда использовать левые внешние соединения.

Ключевое слово `outer` необязательное, так что можно просто писать `A left join B`, но я рекомендую включать слово `outer` для ясности.
:::

### Трехсторонние внешние соединения

В некоторых случаях может потребоваться внешнее соединение одной таблицы с двумя другими. Например, запрос из предыдущего раздела можно расширить, включив в него данные из таблицы **rental**:

In [9]:
%%sql
SELECT
    f.film_id,
    f.title,
    i.inventory_id,
    r.rental_date
FROM film f
    LEFT JOIN inventory i
        ON f.film_id = i.film_id
    LEFT JOIN rental r
        ON i.inventory_id = r.inventory_id
WHERE f.film_id BETWEEN 13 AND 15;

32 rows affected.

+---------+----------------+--------------+---------------------+
| film_id |     title      | inventory_id |     rental_date     |
+---------+----------------+--------------+---------------------+
|    13   |  ALI FOREVER   |      67      | 2005-07-31 18:11:17 |
|    13   |  ALI FOREVER   |      67      | 2005-08-22 21:59:29 |
|    13   |  ALI FOREVER   |      68      | 2005-07-28 15:26:20 |
|    13   |  ALI FOREVER   |      68      | 2005-08-23 05:02:31 |
|    13   |  ALI FOREVER   |      69      | 2005-08-01 23:36:10 |
|    13   |  ALI FOREVER   |      69      | 2005-08-22 02:12:44 |
|    13   |  ALI FOREVER   |      70      | 2005-07-12 10:51:09 |
|    13   |  ALI FOREVER   |      70      | 2005-07-29 01:29:51 |
|    13   |  ALI FOREVER   |      70      | 2006-02-14 15:16:03 |
|    14   | ALICE FANTASIA |     None     |         None        |
|    15   |  ALIEN CENTER  |      71      | 2005-05-28 02:06:37 |
|    15   |  ALIEN CENTER  |      71      | 2005-06-17 16:40:03 |
|    15   |  ALIEN CENTER  |      71      | 2005-07-11 05:47:08 |
|    15   |  ALIEN CENTER  |      71      | 2005-08-02 13:58:55 |
|    15   |  ALIEN CENTER  |      71      | 2005-08-23 05:13:09 |
|    15   |  ALIEN CENTER  |      72      | 2005-05-27 22:49:27 |
|    15   |  ALIEN CENTER  |      72      | 2005-06-19 13:29:28 |
|    15   |  ALIEN CENTER  |      72      | 2005-07-07 23:05:53 |
|    15   |  ALIEN CENTER  |      72      | 2005-08-01 05:55:13 |
|    15   |  ALIEN CENTER  |      72      | 2005-08-20 15:11:48 |
|    15   |  ALIEN CENTER  |      73      | 2005-07-06 15:51:58 |
|    15   |  ALIEN CENTER  |      73      | 2005-07-30 14:48:24 |
|    15   |  ALIEN CENTER  |      73      | 2005-08-20 22:32:11 |
|    15   |  ALIEN CENTER  |      74      | 2005-07-27 00:15:18 |
|    15   |  ALIEN CENTER  |      74      | 2005-08-23 19:21:22 |
|    15   |  ALIEN CENTER  |      75      | 2005-07-09 02:58:41 |
|    15   |  ALIEN CENTER  |      75      | 2005-07-29 23:52:01 |
|    15   |  ALIEN CENTER  |      75      | 2005-08-18 21:55:01 |
|    15   |  ALIEN CENTER  |      76      | 2005-06-15 08:01:29 |
|    15   |  ALIEN CENTER  |      76      | 2005-07-07 18:31:50 |
|    15   |  ALIEN CENTER  |      76      | 2005-08-01 01:49:36 |
|    15   |  ALIEN CENTER  |      76      | 2005-08-17 07:26:47 |
+---------+----------------+--------------+---------------------+

Резульаты включают в себя все фильмы, имеющиеся в наличии, но у фильма *Alice Fantasia* в столбцах из обеих таблиц, соединенных внешним соединением находятся значения `null` (None).

## Перекрестные соединения

Еще в главе 5 была представлена концепция декартова произведения, которая по сути представляет собой результат соединения нескольких таблиц без указания каких-либо условий соединения.

Декартово произведение довольно часто используется случайно (например, если вы забыли добавить условие соединения в предложение `from`), но преднамеренное его применение не так уж распространено. Если все же намереваетесь сгенерировать декартово произведение твух таблиц, то должны указать *перекрестное соединение* как в следующем примере:

In [13]:
%%sql
SELECT
    c.name AS category_name,
    l.name AS language_name
FROM category c
    CROSS JOIN language l;

96 rows affected.

   category_name language_name
0         Action        German
1         Action        French
2         Action      Mandarin
3         Action      Japanese
4         Action       Italian
..           ...           ...
91        Travel        French
92        Travel      Mandarin
93        Travel      Japanese
94        Travel       Italian
95        Travel       English

[96 rows x 2 columns]

Этот запрос генерурует декартово произведение таблиц **category** и **language**, в результате  чего получается результирующий набор из 96 строк (16 строк category x 6 строк language).

Теперь, когда вы знаете что такое перекрестное соединение и как его указать, возникает вопрос *А для чего оно используется?* В большинстве книг по SQL после описания что такое перекрестное соединение, просто говорится что оно редко бывает полезным. Но я хотел бы поделиться с вами ситуацией, в которой считаю перекрестное соединение весьма полезным.

В главе 9 рассматривалось как испольовать подзапросы для создания таблиц и как построить таблицу из трех строк, которую можно объединить с другими таблицами. Вот собранная таким образом таблица из примера:

In [14]:
%%sql
SELECT 'Small Fry' name, 0 low_limit, 74.99 high_limit
UNION ALL
SELECT 'Average Joes', 75, 149.99
UNION ALL
SELECT 'Heavy Hitters', 150, 9999999.99;

3 rows affected.

            name  low_limit  high_limit
0      Small Fry          0       74.99
1   Average Joes         75      149.99
2  Heavy Hitters        150  9999999.99

Хотя эта таблица – именно то, что нужно для разделения клиентов на три группы на основе их платежей, такая стратегия объединения однострочных таблиц с использованием оператора `union all` – все же не самый лучший вариант в случае больших таблиц.

Пусть, например, вы хотите создать запрос, который генерирует по одной строке на каждый день 2020 года, но в базе данных нет таблицы, которая содержит по строке для каждого дня. Используя стратегию из упомянутого примера, вы можете сделать что-то вроде следующего:

```sql
SELECT '2020-01-01' dt
UNION ALL
SELECT '2020-01-02' dt
UNION ALL
SELECT '2020-01-03' dt
UNION ALL
...
SELECT '2020-12-29' dt
UNION ALL
SELECT '2020-12-30' dt
UNION ALL
SELECT '2020-12-31' dt
```
Создание запроса, объединяющего результаты 366 запросов, несколько утомительно, поэтому пожалуй нужна другая стратегия.

Что если вы созданите таблицу с 366 строками (2020 – високосный год) с одним столбцом, содержащим числа от 0 до 366, а затем добавите это количество дняй к 1 января 2020 года? Вот один из возможных способов создания такой таблицы: