---
title: Интенсив по SQL от Simulative
subtitle: SQL Lab in JupyterLab
# license: CC-BY-4.0
github: https://github.com/magus1968/learning-sql
subject: Technical Portfolio
venue: GitHub & GitVerse Pages
# abstract: |
#   В последнем запросе главы, в разделе _Этот таинственный null_, увидим причину, по которой для усечения строк в дальнейшем будет использоваться Pandas.
authors:
  - name: Alex Smirnov
    email: a@smirnovs.pro
    corresponding: true
    affiliations: Data & BI Analyst
date: 2026-09-05
abbreviations:
    MyST: Markedly Structured Text
    Jupyter Book: Инструмент сборки статических сайтов
    JupySQL: Расширение для запуска и подсветки SQL в Jupyter
    GitHub: Платформа хостинга репозиториев и совместной разработки
    GitHub Pages: Сервис бесплатного хостинга статических сайтов
    GitHub Actions: Платформа автоматизации рабочих процессов и CI/CD
    Pandas: Библиотека Python для анализа и обработки данных
    Polars: Мощный аналог Pandas на Rust/Python
---

Для подключения к базе данных PostgreSQL необходимо в [окружение](https://magus1968.github.io/learning-sql/intro1-environment/) установить соответствующий драйвер [`psycopg2`](https://www.psycopg.org/):
```bash
# (base) Anaconda Prompt

conda install -n ds-book --override-channels -c conda-forge -c defaults psycopg2
```

In [1]:
import pandas as pd
import sqlalchemy as sa
import sql

pd.set_option('display.max_rows', 10)

connection_url = sa.engine.URL.create(
    drivername="postgresql+psycopg2",
    host="95.163.241.236",
    port=5432,
    database="simulative",
    username="student",
    password="qweasd963",
)
engine = sa.create_engine(connection_url)

%load_ext sql

# %config SqlMagic.displaylimit = 20
%config SqlMagic.displaycon = False
# %config SqlMagic.feedback = False
%config SqlMagic.autopandas = True

%sql engine

print(f"Pandas ver. {pd.__version__}: порог усечения строк уменьшен до 10")
print(f"SQLAlchemy ver. {sa.__version__}: подключение создано")
print(f"JupySQL ver. {sql.__version__}: подключен через SQLAlchemy Engine")

Pandas ver. 3.0.5: порог усечения строк уменьшен до 10
SQLAlchemy ver. 2.0.52: подключение создано
JupySQL ver. 0.11.1: подключен через SQLAlchemy Engine


---

## Интро

Ссылка на [Бесплатный интенсив Основы SQL](https://simulative.ru/free-sql)

::::{tip} Расписание
:class: dropdown
:open: false
:icon: true

:::{div}
:class: text-sm
**День 1**
- [x] Введение и подключение к БД
- [x] Базовый синтаксис (SELECT, сортировка)

**День 2**
- [x] Горизонтальная фильтрация WHERE
- [x] Скалярные функции (текстовые

**День 3**
- [x] Полезные операторы
- [x] Скалярные функции (работа с датой и временем)

**День 4**
- [x] Дополнительные приемы SQL
- [x] Соединение таблиц

**День 5**
- [ ] Объединение таблиц
- [ ] Группировки

**День 6**
- [ ] Подзапросы и CTE
- [ ] Оконные функции

**День 7**
- [ ] Допроходим уроки
- [ ] Финальный проект

**День 8**
- [ ] Доделываем проект и заканчиваем курс
:::
::::

**Общая инфа**
- Данные, которые мы используем в курсе - база IT Resume. [Описание таблиц](https://docs.google.com/document/d/1qKDKq_d8Mhud5p3mADxWWxlIrPx-EfHzvuE0j02dKtA/edit?tab=t.0#heading=h.2jjs7kn5dns)
- Гайд [10 инструментов аналитика](https://drive.google.com/file/d/1oOxXIdi46rThkqSun6DYvCUI9Zz2vm7v/view?pli=1)
- [Блог с полезностями](https://simulative.ru/blog) от Симулейтив

**Статьи [^1] от Евгения Буторина**
- [x] [Пишем свой первый SQL-запрос](https://simulative.ru/blog/sql-first-query)
- [ ] [Операторы SQL: основные группы и примеры использования](https://simulative.ru/blog/sql-operators)
- [x] [10 SQL-ошибок и фишек, о которых редко говорят](https://simulative.ru/blog/10-sql-mistakes)
- [ ] [JOIN в SQL: как использовать оператор соединения](https://simulative.ru/blog/sql-join)
- [ ] Гайд [JOIN в SQL: виды, описание и примеры](https://drive.google.com/file/d/1yo8VER7z_iPuwYgZFdoVvMfxaHo6wHzz/view?pli=1)
- [ ] [Агрегатные функции в SQL-запросах: что это и для чего нужны](https://simulative.ru/blog/aggregate-functions-sql)
- [ ] Кейс [^2] [Группировка и агрегатные функции (GROUP BY, HAVING, SUM, COUNT, AVG)](https://colab.research.google.com/drive/1jiK06msi8cXXWI7YCTfmuCxLA6mnh1jJ?usp=drive_link)
- [ ] [CTE: для чего нужна временная таблица в SQL](https://simulative.ru/blog/cte-sql)
- [ ] [Оконные функции в SQL: что это и для чего они нужны](https://simulative.ru/blog/sql-window-functions)

[^1]: Читай статьи Евгения Буторина – прям реално лучше поймешь лекции и проще будет делать практику.
[^2]: Google **Colab**

**Полезности из чата**
- [SQL Fiddle](https://sqlfiddle.com/) - онлайн-редактор (компилятор) SQL-запросов для разных СУБД (MySQL, PostgreSQL, SQLLite ... )

::::{note} Примечание
:class: dropdown
:open: true
:icon: true

:::{div}
:class: text-sm
1. Первые три дня делал в **DBeaver**, потом *ушел* в **JupyterLab**.
2. В интерфейсе **JupyterLab** столбцы помещаются как в **DBeaver**. Но _**не**_ на сайте **Jupyter Book**. Поэтому:
   - чтобы столбцы на сайте умещались по ширине без горизонтальной прокрутки, старался *ужать* вывод за счет выбора полей в **SELECT**;
   - чтобы перечисляемое количество полей не отвлекало от сути, визуально отделял суть через дополнительный комментарий `--`.
3. **Pandas** используется исключительно для усечения строк вывода.
:::
::::

---

## 3. Базовый синтаксис
В этом уроке вы сделаете первые уверенные шаги в SQL. Мы разберём, как извлекать данные из таблиц, выбирать конкретные столбцы или все сразу. А чтобы данные были не только полезными, но и удобными для восприятия - научимся сортировать результаты.

Вы изучите:
- Команду `SELECT` и выбор нужных колонок
- Использование псевдонимов (`AS`)
- Сортировку результатов с помощью `ORDER BY`, `ASC`, `DESC`

### SELECT

In [4]:
%%sql
SELECT * FROM users;

2774 rows affected.

,id,username,first_name,last_name,is_active,date_joined,email,referal_user,company_id,tier,score
0,198,Pbnnd,NaN,NaN,1,2021-11-23 13:58:52.051036,jbsnjbf@gmail.com,NaN,NaN,1,0
1,52,fjbis,Элина,Полякова,1,2021-09-01 12:04:31.148715,fjbis@yandex.ru,NaN,NaN,1,0
2,331,jjxbfox,Эмилия,Афанасьев,1,2021-12-12 07:03:00.583264,jjxbfox@bk.ru,NaN,NaN,1,0
3,416,nsosabisfsobm,NaN,NaN,1,2022-01-02 12:22:43.014039,isfsobm.nseo@gmail.com,NaN,1.0,1,0
4,19,Fofbx196,Эмилия,Фролова,1,2021-04-22 15:37:33.000000,koonbnanojj.jofbx@yandex.ru,NaN,NaN,1,0
...,...,...,...,...,...,...,...,...,...,...,...
2769,1706,Domsd,Константин,Хохлова,1,2022-02-18 05:21:31.631400,abd-mbmb@ya.ru,NaN,NaN,1,10
2770,2574,odbfonn,Яна,Сухарева,1,2022-04-01 12:31:14.559731,nbjsbjds@mail.ru,NaN,4.0,1,0
2771,2660,cookboo,Артём,Хохлова,1,2022-04-08 21:01:54.011350,cookboo@gmail.com,NaN,NaN,1,25
2772,2816,dbkbxdsaasna,NaN,NaN,1,2022-04-21 10:58:08.609494,fdsnbfo@example.org,NaN,4.0,1,0
2773,2817,jbesnab_ooojo,NaN,NaN,0,2022-04-21 12:20:00.000202,enbfxseo71@example.net,NaN,NaN,0,0

### AS

In [5]:
%%sql
SELECT
	u.username login,
	u.date_joined AS created_at
FROM users u;

2774 rows affected.

              login                 created_at
0             Pbnnd 2021-11-23 13:58:52.051036
1             fjbis 2021-09-01 12:04:31.148715
2           jjxbfox 2021-12-12 07:03:00.583264
3     nsosabisfsobm 2022-01-02 12:22:43.014039
4          Fofbx196 2021-04-22 15:37:33.000000
...             ...                        ...
2769          Domsd 2022-02-18 05:21:31.631400
2770        odbfonn 2022-04-01 12:31:14.559731
2771        cookboo 2022-04-08 21:01:54.011350
2772   dbkbxdsaasna 2022-04-21 10:58:08.609494
2773  jbesnab_ooojo 2022-04-21 12:20:00.000202

[2774 rows x 2 columns]

### ORDER BY

#### ASC

In [2]:
%%sql
-- ASC сортировка по возрастанию (по умолчанию - можно не указывать)
SELECT
	id,
    username,
    first_name,
    last_name,
    date_joined
FROM users u
ORDER BY date_joined ASC;

2774 rows affected.

        id       username first_name last_name                date_joined
0        8       foebeb13      Демид   Фадеева 2021-03-28 08:50:53.000000
1       18       aixbcssn     Карина  Соловьев 2021-03-28 17:08:26.000000
2       15         Sonno1       Анна    Исаева 2021-03-29 03:58:58.000000
3       13       Kbxdbobn    Даниэль  Столяров 2021-03-29 18:16:06.000000
4        9       fonnosna        NaN       NaN 2021-03-30 19:40:30.000000
...    ...            ...        ...       ...                        ...
2769  2813       coxanb24      Демид   Ермаков 2022-04-20 18:39:47.208602
2770  2814      aoxnbxf50    Варвара    Демина 2022-04-20 20:37:17.440384
2771  2815        xxbabnn       Анна  Столяров 2022-04-20 20:42:15.647099
2772  2816   dbkbxdsaasna        NaN       NaN 2022-04-21 10:58:08.609494
2773  2817  jbesnab_ooojo        NaN       NaN 2022-04-21 12:20:00.000202

[2774 rows x 5 columns]

#### DESC

In [5]:
%%sql
-- DESC сортировка по убыванию
SELECT
	id,
    username,
    first_name,
    last_name,
    date_joined
FROM users u
ORDER BY date_joined DESC;

2774 rows affected.

        id       username first_name last_name                date_joined
0     2817  jbesnab_ooojo        NaN       NaN 2022-04-21 12:20:00.000202
1     2816   dbkbxdsaasna        NaN       NaN 2022-04-21 10:58:08.609494
2     2815        xxbabnn       Анна  Столяров 2022-04-20 20:42:15.647099
3     2814      aoxnbxf50    Варвара    Демина 2022-04-20 20:37:17.440384
4     2813       coxanb24      Демид   Ермаков 2022-04-20 18:39:47.208602
...    ...            ...        ...       ...                        ...
2769     9       fonnosna        NaN       NaN 2021-03-30 19:40:30.000000
2770    13       Kbxdbobn    Даниэль  Столяров 2021-03-29 18:16:06.000000
2771    15         Sonno1       Анна    Исаева 2021-03-29 03:58:58.000000
2772    18       aixbcssn     Карина  Соловьев 2021-03-28 17:08:26.000000
2773     8       foebeb13      Демид   Фадеева 2021-03-28 08:50:53.000000

[2774 rows x 5 columns]

In [7]:
%%sql
SELECT
	id,
    username,
    first_name,
    last_name,
    is_active
FROM users u
ORDER BY is_active;

2774 rows affected.

        id     username first_name     last_name  is_active
0      989       22fnfn     Виктор     Трифонова          0
1      862     Enba0027    Смирнов      Дмитриев          0
2      757  bcbxonbabmb      Фёдор     Степанова          0
3     1136    fsocbdcon        NaN           NaN          0
4     2781  Jonns412142  Маргарита     Старостин          0
...    ...          ...        ...           ...        ...
2769   270    bnbdmbdab        Ева  Константинов          1
2770   271        Oxxso       Глеб      Миронова          1
2771   272  bxbnkbnsnbm    Дмитрий         Иван           1
2772   273    obmbdonob    Варвара     Воронцова          1
2773   274       obaasb     Степан     Гончарова          1

[2774 rows x 5 columns]

In [8]:
%%sql
SELECT
	id,
    first_name,
    last_name,
    is_active,
    date_joined
FROM users u
ORDER BY is_active, date_joined DESC;

2774 rows affected.

        id first_name  last_name  is_active                date_joined
0     2817        NaN        NaN          0 2022-04-21 12:20:00.000202
1     2815       Анна   Столяров          0 2022-04-20 20:42:15.647099
2     2813      Демид    Ермаков          0 2022-04-20 18:39:47.208602
3     2811      София    Булатов          0 2022-04-20 10:06:02.505335
4     2810     Михаил  Тимофеева          0 2022-04-20 08:52:42.474688
...    ...        ...        ...        ...                        ...
2769     9        NaN        NaN          1 2021-03-30 19:40:30.000000
2770    13    Даниэль   Столяров          1 2021-03-29 18:16:06.000000
2771    15       Анна     Исаева          1 2021-03-29 03:58:58.000000
2772    18     Карина   Соловьев          1 2021-03-28 17:08:26.000000
2773     8      Демид    Фадеева          1 2021-03-28 08:50:53.000000

[2774 rows x 5 columns]

In [10]:
%%sql
SELECT 
	id,
	username,
	email,
	date_joined
FROM users
ORDER BY date_joined DESC, id;

2774 rows affected.

        id       username                     email                date_joined
0     2817  jbesnab_ooojo    enbfxseo71@example.net 2022-04-21 12:20:00.000202
1     2816   dbkbxdsaasna       fdsnbfo@example.org 2022-04-21 10:58:08.609494
2     2815        xxbabnn  bsfxb.fsxabn@example.com 2022-04-20 20:42:15.647099
3     2814      aoxnbxf50     bdsoaaaon@example.net 2022-04-20 20:37:17.440384
4     2813       coxanb24        fnksan@example.com 2022-04-20 18:39:47.208602
...    ...            ...                       ...                        ...
2769     9       fonnosna   asfbdsnnbm.fons@mail.ru 2021-03-30 19:40:30.000000
2770    13       Kbxdbobn   fscbmsanosfon@gmail.com 2021-03-29 18:16:06.000000
2771    15         Sonno1    ob.fbnmdbf1990@mail.ru 2021-03-29 03:58:58.000000
2772    18       aixbcssn            jbfksn@list.ru 2021-03-28 17:08:26.000000
2773     8       foebeb13  jbnbnasxcbcbom@yandex.ru 2021-03-28 08:50:53.000000

[2774 rows x 4 columns]

### Практика #1

::::{note} Задание 1
:class: dropdown
:open: true
:icon: false
:::{div}
:class: text-xs

Из таблицы users требуется вывести следующую информацию о пользователях:
- Идентификатор
- Логин
- Почта
- Дата и время регистрации

**Столбцы в результате**:
- `id`
- `username`
- `email`
- `date_joined`

**Сортировка**: \
Результат отсортируйте сначала по убыванию поля date_joined, а затем по возрастанию поля `id`.
:::
::::

In [37]:
%%sql
select
    id,
    username,
    email,
    date_joined
from users
order by date_joined desc, id;

2774 rows affected.

        id       username                     email                date_joined
0     2817  jbesnab_ooojo    enbfxseo71@example.net 2022-04-21 12:20:00.000202
1     2816   dbkbxdsaasna       fdsnbfo@example.org 2022-04-21 10:58:08.609494
2     2815        xxbabnn  bsfxb.fsxabn@example.com 2022-04-20 20:42:15.647099
3     2814      aoxnbxf50     bdsoaaaon@example.net 2022-04-20 20:37:17.440384
4     2813       coxanb24        fnksan@example.com 2022-04-20 18:39:47.208602
...    ...            ...                       ...                        ...
2769     9       fonnosna   asfbdsnnbm.fons@mail.ru 2021-03-30 19:40:30.000000
2770    13       Kbxdbobn   fscbmsanosfon@gmail.com 2021-03-29 18:16:06.000000
2771    15         Sonno1    ob.fbnmdbf1990@mail.ru 2021-03-29 03:58:58.000000
2772    18       aixbcssn            jbfksn@list.ru 2021-03-28 17:08:26.000000
2773     8       foebeb13  jbnbnasxcbcbom@yandex.ru 2021-03-28 08:50:53.000000

[2774 rows x 4 columns]

### Куратор

::::{seealso} [ссылка](https://t.me/c/3825910988/465) Вы можете создавать свои поля
:::{div}
:class: text-sm

Например, используя CASE WHEN или просто указывая значение:

```sql
-- Эта команда выведет все поля таблицы с пользователями:
SELECT *
FROM users;
```

```sql
-- Этот селект уже более сложный:
SELECT 
    u.*,
    CASE WHEN user_name LIKE 'U%' THEN 1 ELSE 0 END AS user_u_flg,
    'Пользователи' as types
FROM users u;
```
Обратите внимание мы присвоили таблице `users` алиас (псевдоним) `u` и сказали выведи мне все столбцы из таблицы `u` и добавь 2 столбца: `user_u_flg` (флаг где имя пользователя начинается с `u`) и `types` (где мы просто указали тип руками).

Для чего это нужно? В 80% случаев мы не делаем обычный SELECT, мы на ходу рассчитываем необходимые нам поля.
:::
::::

:::{div}
:class: text-sm
**Curse of knowledge** *(проклятие знания)*: \
Это когда опытный специалист настолько привык к вещам, которые делает каждый день годами, что для него это становится *воздухом*. Ему кажется: *Ну это же очевидно!* – и он просто забывает, как на это смотрит человек, делающий первые шаги.
:::

::::{hint} Пояснение
:::{div}
:class: text-sm

1. **Обычный** SELECT \
Когда куратор говорит **обычный** SELECT, он имеет в виду пассивный запрос вида: *достань из базы то, что там уже лежит, ровно в том виде, как оно записано, без изменений*:
```sql
SELECT id, username, email FROM users;
```

2. **Почему этого не хватает в 80% случаев**? \
Потому что бизнесу (руководству, маркетологам, продуктовым менеджерам) сырые данные из базы почти никогда не нужны сами по себе. Им нужны ответы на бизнес-вопросы:
- Бизнесу не интересна дата регистрации `2021-04-12 15:42:01` – им нужно знать: *Сколько полных дней пользователь с нами?*
- Бизнесу не интересны разрозненные столбцы `first_name` и `last_name` – им нужно единое поле `full_name` для отправки красивого email.
- Бизнесу не интересны баллы `score = 142` – им нужно знать сегмент: *Новичок*, *Опытный* или *VIP*.

Ты абсолютно прав: и `CONCAT(...)`, и `NOW() - date_joined` – это синтаксически обычный SELECT. Куратор противопоставлял не синтаксис команды, а **подход**: мы не просто *читаем* готовые колонки *(обычный селект)*, мы прямо в SELECT **создаем новые сущности и признаки на лету**.

3. **Зачем** поле `'Пользователи' AS types`? Какая **цель**? \
В вакууме (когда ты делаешь один запрос к одной таблице) поле со словом 'Пользователи' действительно выглядит бессмысленным. Ты и так знаешь, что запросил таблицу users.

Но в реальной аналитике такие статические поля решают две ключевые задачи:

**Задача А**: Объединение списков (оператор `UNION`) \
Представь, что в компании есть две разные таблицы: `clients` (клиенты) и `contractors` (подрядчики). Директор просит: *Сделай мне один общий список всех людей, с которыми мы работаем, их имена и контакты*.

Ты объединяешь две таблицы в один большой список. Если не добавить такое искусственное поле, в общем списке все перемешаются – ты не поймешь, кто клиент, а кто подрядчик:
```sql
-- Первый кусок:
SELECT name, email, 'Клиент' AS role FROM clients
UNION ALL
-- Второй кусок:
SELECT name, email, 'Подрядчик' AS role FROM contractors;
```
В итоговой таблице колонка `role` будет содержать слова `'Клиент'` или `'Подрядчик'`. Теперь любой человек в Excel сразу поймёт, кто есть кто, и сможет отфильтровать нужных.

**Задача Б**: Экспорт для внешних программ (Excel, PowerBI, CRM) \
Аналитик выгружает таблицу в CSV и отправляет в другой отдел. Там не знают, из какой таблицы базы данных это выгружено. Поле `'Пользователи' AS types` сразу документирует строку для внешней системы.

4. **Почему** `u.*`, а не просто `*`? \
Давай посмотрим, как на это реагирует сам PostgreSQL.

Если ты напишешь:
```sql
SELECT 
    *,
    CASE WHEN username LIKE 'U%' THEN 1 ELSE 0 END AS user_u_flg,
    'Пользователи' AS types
FROM users;
```
В PostgreSQL это сработает точно так же! Звёздочка `*` без алиаса прекрасно выведет все колонки, а следом добавятся два новых поля.

Тогда зачем куратор написал `u.*` и дал таблице алиас `u`?

- Привычка к хорошему тону (**Best Practice**): \
Когда в запросе появится объединение таблиц (`JOIN`), звёздочка без указания таблицы (`SELECT *`) превратит результат в кашу из всех колонок обеих таблиц, включая одинаковые `id`. Указание `u.*` явно приказывает: *Выведи все колонки именно из таблицы `u` (users), но не трогай колонки из других таблиц*.
- **Читаемость кода**: \
Алиас `u` явно связывает выборку колонок `u.*` с источником `FROM users u`.

Итог: \
`u.*` – это не обязательное правило для одной таблицы, а признак зрелого SQL-стиля, который спасает от ошибок, когда запросы становятся сложнее и работают с несколькими таблицами сразу.

:::
::::

---

## 4. Горизонтальная фильтрация

В этом уроке мы научимся *вырезать* из таблицы только нужные нам строки по определенным условиям, ведь без фильтрации не обходится ни один реальный SQL-запрос.

Вы изучите:
- Условия сравнения: `=`, `!=`, `<`, `>`, `BETWEEN`
- Логические операторы: `AND`, `OR`, `NOT`
- Работа с NULL: `IS NULL`, `IS NOT NULL`
- Фильтрацию по строкам, числам и датам

In [13]:
%%sql
SELECT
    id,
    username,
    first_name,
    last_name,
    email
FROM users
WHERE id = 198;

1 rows affected.

    id username first_name last_name              email
0  198    Pbnnd       None      None  jbsnjbf@gmail.com

In [14]:
%%sql
SELECT
    id,
    username,
    first_name,
    last_name,
    email
FROM users
WHERE 1 = 1;

2774 rows affected.

        id       username  first_name  last_name                        email
0      198          Pbnnd         NaN        NaN            jbsnjbf@gmail.com
1       52          fjbis       Элина   Полякова              fjbis@yandex.ru
2      331        jjxbfox      Эмилия  Афанасьев                jjxbfox@bk.ru
3      416  nsosabisfsobm         NaN        NaN       isfsobm.nseo@gmail.com
4       19       Fofbx196      Эмилия    Фролова  koonbnanojj.jofbx@yandex.ru
...    ...            ...         ...        ...                          ...
2769  1706          Domsd  Константин    Хохлова               abd-mbmb@ya.ru
2770  2574        odbfonn         Яна   Сухарева             nbjsbjds@mail.ru
2771  2660        cookboo       Артём    Хохлова            cookboo@gmail.com
2772  2816   dbkbxdsaasna         NaN        NaN          fdsnbfo@example.org
2773  2817  jbesnab_ooojo         NaN        NaN       enbfxseo71@example.net

[2774 rows x 5 columns]

In [15]:
%%sql
SELECT
    id,
    username,
    first_name,
    last_name,
    email
FROM users
WHERE True;

2774 rows affected.

        id       username  first_name  last_name                        email
0      198          Pbnnd         NaN        NaN            jbsnjbf@gmail.com
1       52          fjbis       Элина   Полякова              fjbis@yandex.ru
2      331        jjxbfox      Эмилия  Афанасьев                jjxbfox@bk.ru
3      416  nsosabisfsobm         NaN        NaN       isfsobm.nseo@gmail.com
4       19       Fofbx196      Эмилия    Фролова  koonbnanojj.jofbx@yandex.ru
...    ...            ...         ...        ...                          ...
2769  1706          Domsd  Константин    Хохлова               abd-mbmb@ya.ru
2770  2574        odbfonn         Яна   Сухарева             nbjsbjds@mail.ru
2771  2660        cookboo       Артём    Хохлова            cookboo@gmail.com
2772  2816   dbkbxdsaasna         NaN        NaN          fdsnbfo@example.org
2773  2817  jbesnab_ooojo         NaN        NaN       enbfxseo71@example.net

[2774 rows x 5 columns]

### AND

In [44]:
%%sql
SELECT
    id,
    username,
    first_name,
    last_name,
    is_active,
    referal_user,
    company_id,
    score
FROM users
--
WHERE id = 198 AND True;

1 rows affected.

    id username first_name last_name  is_active referal_user company_id  score
0  198    Pbnnd       None      None          1         None       None      0

### IS NOT NULL

In [4]:
%%sql
SELECT
    id,
    first_name,
    last_name,
    is_active,
    referal_user,
    company_id,
    score
FROM users
--
WHERE is_active  = 1 AND company_id IS NOT null;

224 rows affected.

       id first_name last_name  is_active referal_user  company_id  score
0     416        NaN       NaN          1         None           1      0
1      43        NaN       NaN          1         None           1      0
2      50     Никита   Ермаков          1         None           1      0
3    1964        NaN       NaN          1         None          10      0
4     249     Даниил   Горшков          1         None           1      0
..    ...        ...       ...        ...          ...         ...    ...
219  2812     Даниил  Семенова          1         None           7      0
220  2483        NaN       NaN          1         None           1     15
221  2701      Дарья   Беликов          1         None           7     70
222  2574        Яна  Сухарева          1         None           4      0
223  2816        NaN       NaN          1         None           4      0

[224 rows x 7 columns]

### OR

In [5]:
%%sql
SELECT
    id,
    first_name,
    last_name,
    is_active,
    referal_user,
    company_id,
    score
FROM users
--
WHERE referal_user IS NOT NULL OR company_id IS NOT NULL;

313 rows affected.

       id first_name last_name  is_active  referal_user  company_id  score
0     416        NaN       NaN          1           NaN         1.0      0
1      43        NaN       NaN          1           NaN         1.0      0
2      50     Никита   Ермаков          1           NaN         1.0      0
3    1964        NaN       NaN          1           NaN        10.0      0
4     249     Даниил   Горшков          1           NaN         1.0      0
..    ...        ...       ...        ...           ...         ...    ...
308  2483        NaN       NaN          1           NaN         1.0     15
309  2624    Ярослав  Захарова          1        2611.0         NaN      0
310  2701      Дарья   Беликов          1           NaN         7.0     70
311  2574        Яна  Сухарева          1           NaN         4.0      0
312  2816        NaN       NaN          1           NaN         4.0      0

[313 rows x 7 columns]

In [6]:
%%sql
SELECT
    id,
    first_name,
    last_name,
    is_active,
    referal_user,
    company_id,
    score
FROM users
--
WHERE referal_user IS NOT NULL OR company_id IS NOT NULL OR score > 1000;

313 rows affected.

       id first_name last_name  is_active  referal_user  company_id  score
0     416        NaN       NaN          1           NaN         1.0      0
1      43        NaN       NaN          1           NaN         1.0      0
2      50     Никита   Ермаков          1           NaN         1.0      0
3    1964        NaN       NaN          1           NaN        10.0      0
4     249     Даниил   Горшков          1           NaN         1.0      0
..    ...        ...       ...        ...           ...         ...    ...
308  2483        NaN       NaN          1           NaN         1.0     15
309  2624    Ярослав  Захарова          1        2611.0         NaN      0
310  2701      Дарья   Беликов          1           NaN         7.0     70
311  2574        Яна  Сухарева          1           NaN         4.0      0
312  2816        NaN       NaN          1           NaN         4.0      0

[313 rows x 7 columns]

In [7]:
%%sql
SELECT
    id,
    first_name,
    last_name,
    is_active,
    referal_user,
    company_id,
    score
FROM users
--
WHERE referal_user IS NOT NULL OR company_id IS NOT NULL OR score > 500
ORDER BY score DESC;

315 rows affected.

       id first_name  last_name  is_active  referal_user  company_id  score
0    2558    Варвара     Ефимов          1           NaN         4.0    805
1    2282  Александр  Степанова          1           NaN         NaN    790
2    2491  Александр   Тимофеев          1           NaN         NaN    670
3    2575      Макар   Артемова          1           NaN         4.0    395
4    2564      Макар  Филиппова          1           NaN         4.0    320
..    ...        ...        ...        ...           ...         ...    ...
310   375    Даниэль     Кузина          1         364.0         NaN      0
311  1964        NaN        NaN          1           NaN        10.0      0
312   272    Дмитрий      Иван           1           NaN         1.0      0
313   381    Варвара    Антонов          1           NaN         1.0      0
314   391  Елизавета    Семенов          1           NaN         1.0      0

[315 rows x 7 columns]

In [8]:
%%sql
SELECT
    id,
    first_name,
    last_name,
    is_active,
    referal_user,
    company_id,
    score
FROM users
--
WHERE is_active + 1 = 2;

2472 rows affected.

        id  first_name  last_name  is_active  referal_user  company_id  score
0      198         NaN        NaN          1           NaN         NaN      0
1       52       Элина   Полякова          1           NaN         NaN      0
2      331      Эмилия  Афанасьев          1           NaN         NaN      0
3      416         NaN        NaN          1           NaN         1.0      0
4       19      Эмилия    Фролова          1           NaN         NaN      0
...    ...         ...        ...        ...           ...         ...    ...
2467  1418      Даниил  Гончарова          1           NaN         NaN      0
2468  1706  Константин    Хохлова          1           NaN         NaN     10
2469  2574         Яна   Сухарева          1           NaN         4.0      0
2470  2660       Артём    Хохлова          1           NaN         NaN     25
2471  2816         NaN        NaN          1           NaN         4.0      0

[2472 rows x 7 columns]

In [9]:
%%sql
SELECT id,
    first_name,
    last_name,
    is_active,
    referal_user,
    company_id,
    score
FROM users
--
WHERE 
	referal_user IS NOT NULL
	AND 
	company_id IS NOT NULL 
	OR 
	score > 500
ORDER BY score DESC;

3 rows affected.

     id first_name  last_name  is_active referal_user  company_id  score
0  2558    Варвара     Ефимов          1         None         4.0    805
1  2282  Александр  Степанова          1         None         NaN    790
2  2491  Александр   Тимофеев          1         None         NaN    670

In [36]:
%%sql
SELECT
    id,
    username,
    first_name,
    last_name,
    is_active,
    referal_user,
    company_id,
    score
FROM users
--
WHERE 
	referal_user IS NOT NULL
	AND
	(company_id IS NOT NULL
	OR
	score > 500)
ORDER BY score DESC;

Empty DataFrame
Columns: [id, username, first_name, last_name, is_active, referal_user, company_id, score]
Index: []

In [37]:
%%sql
SELECT
    id,
    username,
    first_name,
    last_name,
    is_active,
    referal_user,
    company_id,
    score
FROM users
--
WHERE 
	referal_user IS NOT NULL
	OR 
	company_id IS NOT NULL 
	AND 
	score > 500
ORDER BY score DESC;

70 rows affected.

,id,username,first_name,last_name,is_active,referal_user,company_id,score
0,2558,Knonsb,Варвара,Ефимов,1,NaN,4.0,805
1,2615,Anabn1993,Варвара,Макаров,1,2611.0,NaN,245
2,2331,xbkbnbmoma,Георгий,Антонов,1,2268.0,NaN,185
3,2324,FbeoFbeo,Андрей,Никитин,1,1424.0,NaN,185
4,175,Snobfbmb,NaN,NaN,1,140.0,NaN,90
...,...,...,...,...,...,...,...,...
65,373,bfm0oba,Даниэль,Булатов,1,364.0,NaN,0
66,374,biinoe031,Валерия,Горшков,1,364.0,NaN,0
67,375,isfxsm,Даниэль,Кузина,1,364.0,NaN,0
68,449,Lsinxbd,NaN,NaN,1,219.0,NaN,0
69,620,ibxbmbf15,Валерия,Фролова,1,605.0,NaN,0

In [45]:
%%sql
SELECT
    id,
    username,
    first_name,
    last_name,
    is_active,
    referal_user,
    company_id,
    score
FROM users
--
WHERE 
	(referal_user IS NOT NULL
	OR  
	company_id IS NOT NULL)
	AND
	score > 500
ORDER BY score DESC;

1 rows affected.

,id,username,first_name,last_name,is_active,referal_user,company_id,score
0,2558,Knonsb,Варвара,Ефимов,1,None,4,805

In [46]:
%%sql
-- AND имеет приоритет над OR
-- Всегда расставляйте скобки
SELECT
    id,
    username,
    first_name,
    last_name,
    is_active,
    referal_user,
    company_id,
    score
FROM users
--
WHERE 
	(
		referal_user IS NOT NULL
	)
	OR  
	(
		company_id IS NOT NULL
		AND
		score > 500
	)
	OR
	(
		is_active = 0
	)
ORDER BY score DESC;

365 rows affected.

,id,username,first_name,last_name,is_active,referal_user,company_id,score
0,2558,Knonsb,Варвара,Ефимов,1,NaN,4.0,805
1,2615,Anabn1993,Варвара,Макаров,1,2611.0,NaN,245
2,2324,FbeoFbeo,Андрей,Никитин,1,1424.0,NaN,185
3,2331,xbkbnbmoma,Георгий,Антонов,1,2268.0,NaN,185
4,175,Snobfbmb,NaN,NaN,1,140.0,NaN,90
...,...,...,...,...,...,...,...,...
360,106,msdbxa,Таисия,Воронцова,0,NaN,NaN,0
361,123,kbfskлф1980,NaN,NaN,0,NaN,NaN,0
362,136,Hbndbkb,Даниэль,Смирнова,0,NaN,NaN,0
363,141,x1mbn,NaN,NaN,0,NaN,NaN,0
364,143,msobnsbk,Илья,Захаров,1,140.0,NaN,0

In [47]:
%%sql
SELECT
    id,
    username,
    first_name,
    last_name,
    is_active,
    referal_user,
    company_id,
    score
FROM users
--
WHERE company_id != 7; -- Пропали значения NULL

204 rows affected.

,id,username,first_name,last_name,is_active,referal_user,company_id,score
0,416,nsosabisfsobm,NaN,NaN,1,None,1,0
1,43,NbabnnbTona,NaN,NaN,1,None,1,0
2,50,jbdn,Никита,Ермаков,1,None,1,0
3,1964,babnnom,NaN,NaN,1,None,10,0
4,249,Kbaoxsnb,Даниил,Горшков,1,None,1,0
...,...,...,...,...,...,...,...,...
199,2760,odsfob,Даниэль,Андрей,1,None,4,25
200,2802,adobnbn_onb,Степан,Исаева,0,None,1,0
201,2483,Lomsbanbn,NaN,NaN,1,None,1,15
202,2574,odbfonn,Яна,Сухарева,1,None,4,0
203,2816,dbkbxdsaasna,NaN,NaN,1,None,4,0

### IS NULL

In [3]:
%%sql
SELECT
    id,
    first_name,
    last_name,
    is_active,
    referal_user,
    company_id,
    score
FROM users
--
WHERE company_id != 7 OR company_id IS NULL;

2734 rows affected.

        id  first_name  last_name  is_active  referal_user  company_id  score
0      198         NaN        NaN          1           NaN         NaN      0
1       52       Элина   Полякова          1           NaN         NaN      0
2      331      Эмилия  Афанасьев          1           NaN         NaN      0
3      416         NaN        NaN          1           NaN         1.0      0
4       19      Эмилия    Фролова          1           NaN         NaN      0
...    ...         ...        ...        ...           ...         ...    ...
2729  1706  Константин    Хохлова          1           NaN         NaN     10
2730  2574         Яна   Сухарева          1           NaN         4.0      0
2731  2660       Артём    Хохлова          1           NaN         NaN     25
2732  2816         NaN        NaN          1           NaN         4.0      0
2733  2817         NaN        NaN          0           NaN         NaN      0

[2734 rows x 7 columns]

In [31]:
%%sql
SELECT
	is_active,
	is_active + 1 AS new_col
FROM users;

2774 rows affected.

      is_active  new_col
0             1        2
1             1        2
2             1        2
3             1        2
4             1        2
...         ...      ...
2769          1        2
2770          1        2
2771          1        2
2772          1        2
2773          0        1

[2774 rows x 2 columns]

In [32]:
%%sql
SELECT
	is_active,
	is_active + 1 AS new_col
FROM users
WHERE new_col = 2;
-- ERROR мы не можем использовать алиасы из ТЕКУЩЕГО запроса в фильтрации

RuntimeError: (psycopg2.errors.UndefinedColumn) column "new_col" does not exist
LINE 5: WHERE new_col = 2;
              ^

[SQL: SELECT
	is_active,
	is_active + 1 AS new_col
FROM users
WHERE new_col = 2;]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [33]:
%%sql
SELECT
	is_active,
	is_active + 1 AS new_col
FROM users
WHERE is_active + 1 = 2;

2472 rows affected.

      is_active  new_col
0             1        2
1             1        2
2             1        2
3             1        2
4             1        2
...         ...      ...
2467          1        2
2468          1        2
2469          1        2
2470          1        2
2471          1        2

[2472 rows x 2 columns]


---

### Практика #2

::::{note} Задание 1
:class: dropdown
:open: true
:icon: false
:::{div}
:class: text-xs

Из таблицы `users` требуется вывести информацию о пользователях, у которых либо не указана фамилия либо количество очков опыта строго больше 100:

- Идентификатор
- Логин
- Количество очков опыта на платформе

**Столбцы в результате**:
- `id`
- `username`
- `score`

**Сортировка**: \
Результат отсортируйте по возрастанию поля `id`.
:::
::::

In [34]:
%%sql
-- Практика 2. Задача 1
SELECT
	id,
	username,
	score
FROM users
WHERE
	score > 100 OR last_name IS NULL 
ORDER BY id;

767 rows affected.

       id       username  score
0       2         Pbbdob     20
1       7           Lbeo      0
2       9       fonnosna      0
3      23        ssob003      0
4      25       Donmox86      0
..    ...            ...    ...
762  2793              1      0
763  2795          bfbnf      0
764  2806     ibnjsbdo21      0
765  2816   dbkbxdsaasna      0
766  2817  jbesnab_ooojo      0

[767 rows x 3 columns]


---
::::{note} Задание 2
:class: dropdown
:open: true
:icon: false
:::{div}
:class: text-xs

Из таблицы users требуется вывести информацию об активных пользователях (is_active = 1), которые при этом либо имеют количество очков опыта строго больше 500, либо относятся к компании с id = 7:

- Идентификатор
- Логин
- Идентификатор компании
- Количество очков опыта на платформе

**Столбцы в результате**: \
- `id`
- `username`
- `company_id`
- `score`

**Сортировка**: \
Результат отсортируйте по возрастанию поля `id`.
:::
::::

In [38]:
%%sql
-- Практика 2. Задача 2
SELECT 
	id,
	username,
	company_id,
	score
FROM users
WHERE 
	is_active = 1
	AND 
	(score > 500 OR company_id = 7)
ORDER BY id;

35 rows affected.

      id          username  company_id  score
0    925         Anbxebnse         7.0      0
1   2282  ssdsbnjofsebasbn         NaN    790
2   2491       smksonbsdbm         NaN    670
3   2499          Rbknb777         7.0      0
4   2558            Knonsb         4.0    805
5   2661            ZoxaSS         7.0      5
6   2701         amonfbdsn         7.0     70
7   2702             ibmod         7.0      0
8   2703       kedbebdnbna         7.0      0
9   2705           koadsen         7.0     30
10  2706  Soxaos2711fffsff         7.0      0
11  2707             Axaok         7.0      0
12  2708           fbdbbdo         7.0     10
13  2709           abbffbs         7.0      0
14  2710         fsnbfbn88         7.0     30
15  2711         xsfsjxsfs         7.0      5
16  2712          nbanbeno         7.0    100
17  2713             Tbnbs         7.0      0
18  2714             bfksn         7.0      0
19  2715       omaonaxbabn         7.0     10
20  2717        DbxoLbxsbn         7.0     20
21  2718           Axaok99         7.0      0
22  2719          Fbksnskb         7.0     10
23  2722    MbnnbSsfbxosnb         7.0     25
24  2723  FONAKOVALEKSANDR         7.0     20
25  2726            AnabnG         7.0      5
26  2733             Lonsf         7.0    105
27  2734            mbnbnb         7.0      5
28  2740           aona145         7.0      0
29  2748             aona8         7.0      0
30  2757           njaona3         7.0      0
31  2773            Jonnsj         7.0      0
32  2796              nsos         7.0      0
33  2806        ibnjsbdo21         7.0      0
34  2812   osxdsn2nbnasbab         7.0      0

:::{note} Дополнительное задание
:class: dropdown
:open: true
:icon: false

Что выведет запрос?
```sql
SELECT * FROM table
ORDER BY name ASC, name DESC
```
:::

In [36]:
%%sql
-- Задача из чата
SELECT * FROM users
ORDER BY first_name ASC, first_name DESC;

2774 rows affected.

,id,username,first_name,last_name,is_active,date_joined,email,referal_user,company_id,tier,score
0,1709,Mbxabmnm,Аделина,Булатов,1,2022-02-18 07:43:24.145446,kbxab.moxnbmb@mail.ru,NaN,1.0,1,0
1,2791,aona123,Аделина,Иванов,1,2022-04-18 16:40:00.931663,nbkokbsd@mail.com,NaN,NaN,1,0
2,2216,Moxbnbmsnnnb,Аделина,Демина,0,2022-03-08 21:22:09.696729,koxbnbmsnb7@gmail.com,NaN,NaN,0,0
3,2413,noxa4891,Аделина,Филиппова,1,2022-03-21 09:31:25.028468,noxa4891@yandex.ru,NaN,NaN,1,0
4,2764,Jonnsnaj,Аделина,Семенов,0,2022-04-17 10:28:23.573326,sncbf@jesfdssssssss.fsd,NaN,NaN,0,0
...,...,...,...,...,...,...,...,...,...,...,...
2769,988,Jnnjjjj,NaN,NaN,0,2022-01-31 08:43:40.552524,fbm.10@mail.ru,NaN,NaN,0,0
2770,991,sabxnsk1,NaN,NaN,1,2022-01-31 11:29:35.626399,sabxnsk35@gmail.com,NaN,NaN,1,0
2771,993,Ysxss,NaN,NaN,1,2022-01-31 12:14:48.561058,YsxssMBbsob@gmail.com,NaN,NaN,1,95
2772,996,Adbssibmb,NaN,NaN,1,2022-01-31 13:51:14.688521,bdbssibmb@yandex.ru,NaN,NaN,1,0
2773,997,nbkxsn10,NaN,NaN,1,2022-01-31 14:24:59.424515,nbkxsn_xbkbn@rambler.ru,NaN,NaN,1,0


---
:::{tip} Выведет все строки таблицы `table` по возрастанию поля `name`
:class: dropdown
:open: true
:icon: false

Я так понял: `DESC` - это дополнительное условие к первому (`ASC`). \
1. `ASC` отсортировал по возрастанию - разбил на группы одинаковых имен. \
Анна \
Анна \
Анна \

2. `DESC` - если бы были фамилии, то он отсортировал бы получившиеся группы дополнительно по убыванию фамилий. Но поскольку снова сортировка по name, то SQL *сортирует* (пытается сортировать) получившиеся группы внутри себя.
Анна \
Анна \
Анна \
*Сортирует* - сравнивает одинаковые слова - не находит между ними разницы и оставляет в том порядке, который получил после ASC
:::


---

## 5. Скалярные функции (текстовые)
В этом уроке мы научимся работать со строками: изменять регистр, обрезать лишнее, извлекать подстроки, склеивать значения и искать/заменять фрагменты. Эти функции пригодятся вам каждый раз, когда нужно *почистить* или привести к нужному виду текстовые данные.

Вы изучите:
- Изменение регистра: `LOWER`, `UPPER`, `INITCAP`
- Работа с длиной и пробелами: `LENGTH`
- Извлечение подстрок: `LEFT`, `RIGHT`
- Поиск позиции фрагмента: `POSITION`
- Фильтрация по шаблону: `LIKE`, `ILIKE`

### LOWER( )

In [39]:
%%sql
SELECT LOWER('ПриВЕт');

1 rows affected.

    lower
0  привет

In [40]:
%%sql
-- в двойных кавычках в PostgreSQL указываются объекты БД:
-- названия столбцов, названия таблиц - чтобы явно отличить от зарезервированных слов
SELECT 
	LOWER('ПриВЕт') AS "lower_case", -- в двойных кавычках
	'ПриВЕт' AS init_phrase;

1 rows affected.

  lower_case init_phrase
0     привет      ПриВЕт

### UPPER( )

In [49]:
%%sql
SELECT UPPER('ПриВЕт');

1 rows affected.

    upper
0  ПРИВЕТ

### INITCAP( )

In [49]:
%%sql
SELECT
	name,
	LOWER(name),
	UPPER(name),
	INITCAP(name)
FROM problem;

248 rows affected.

,name,lower,upper,initcap
0,Сумма 2 чисел,сумма 2 чисел,СУММА 2 ЧИСЕЛ,Сумма 2 Чисел
1,Преобразование массива,преобразование массива,ПРЕОБРАЗОВАНИЕ МАССИВА,Преобразование Массива
2,Задача о детях и конфетах,задача о детях и конфетах,ЗАДАЧА О ДЕТЯХ И КОНФЕТАХ,Задача О Детях И Конфетах
3,Задача о «хороших парах»,задача о «хороших парах»,ЗАДАЧА О «ХОРОШИХ ПАРАХ»,Задача О «Хороших Парах»
4,Числа с четным числом цифр,числа с четным числом цифр,ЧИСЛА С ЧЕТНЫМ ЧИСЛОМ ЦИФР,Числа С Четным Числом Цифр
...,...,...,...,...
243,Python. ДЗ 3: Поиск подстроки,python. дз 3: поиск подстроки,PYTHON. ДЗ 3: ПОИСК ПОДСТРОКИ,Python. Дз 3: Поиск Подстроки
244,Python. ДЗ 3: Слайсинг строки,python. дз 3: слайсинг строки,PYTHON. ДЗ 3: СЛАЙСИНГ СТРОКИ,Python. Дз 3: Слайсинг Строки
245,Python. ДЗ 3: Реверс строки,python. дз 3: реверс строки,PYTHON. ДЗ 3: РЕВЕРС СТРОКИ,Python. Дз 3: Реверс Строки
246,Python. ДЗ 3: Замена подстроки,python. дз 3: замена подстроки,PYTHON. ДЗ 3: ЗАМЕНА ПОДСТРОКИ,Python. Дз 3: Замена Подстроки
247,Python. ДЗ 3: Комплексная работа со строками,python. дз 3: комплексная работа со строками,PYTHON. ДЗ 3: КОМПЛЕКСНАЯ РАБОТА СО СТРОКАМИ,Python. Дз 3: Комплексная Работа Со Строками

In [53]:
%%sql
SELECT id, username, first_name, last_name,
    is_active, referal_user, company_id, score
FROM users
--
WHERE LOWER(username) = 'девелопер';

1 rows affected.

,id,username,first_name,last_name,is_active,referal_user,company_id,score
0,53,Девелопер,Варвара,Демина,1,None,None,0

### LIKE( )

In [58]:
%%sql
SELECT
    id,
    name
FROM problem
--
WHERE lower(name) LIKE '%new%'; -- Регистрозависимый поиск

20 rows affected.

     id                                               name
0   123                     NEW! SQL. ДЗ 1. Расчет наценки
1   126  NEW! SQL. ДЗ 1. Фильтр и сортировка розничной ...
2   127               NEW! SQL. ДЗ 1. Смешанная сортировка
3   128          NEW! SQL. ДЗ 2. Фильтр строк неравенством
4   129               NEW! SQL. ДЗ 2. Фильтр по длине слов
..  ...                                                ...
15  150      NEW! SQL. ДЗ 5. Следующее/предыдущее значение
16  151                 NEW! SQL. ДЗ 6. Прирост начислений
17  152        NEW! SQL. ДЗ 6. Среднее значение транзакций
18  153                        NEW! | По дороге с облаками
19  154                NEW! | Лиза и ее учебник математики

[20 rows x 2 columns]

### iLIKE( )

In [59]:
%%sql
SELECT
    id,
    name
FROM problem
--
WHERE name iLIKE '%new%'; -- регистроНЕзависимый поиск

20 rows affected.

     id                                               name
0   123                     NEW! SQL. ДЗ 1. Расчет наценки
1   126  NEW! SQL. ДЗ 1. Фильтр и сортировка розничной ...
2   127               NEW! SQL. ДЗ 1. Смешанная сортировка
3   128          NEW! SQL. ДЗ 2. Фильтр строк неравенством
4   129               NEW! SQL. ДЗ 2. Фильтр по длине слов
..  ...                                                ...
15  150      NEW! SQL. ДЗ 5. Следующее/предыдущее значение
16  151                 NEW! SQL. ДЗ 6. Прирост начислений
17  152        NEW! SQL. ДЗ 6. Среднее значение транзакций
18  153                        NEW! | По дороге с облаками
19  154                NEW! | Лиза и ее учебник математики

[20 rows x 2 columns]

### LENGTH( )

In [49]:
%%sql
SELECT name, length(name)
FROM problem;

248 rows affected.

                                             name  length
0                                   Сумма 2 чисел      13
1                          Преобразование массива      22
2                       Задача о детях и конфетах      25
3                        Задача о «хороших парах»      24
4                      Числа с четным числом цифр      26
..                                            ...     ...
243                 Python. ДЗ 3: Поиск подстроки      29
244                 Python. ДЗ 3: Слайсинг строки      29
245                   Python. ДЗ 3: Реверс строки      27
246                Python. ДЗ 3: Замена подстроки      30
247  Python. ДЗ 3: Комплексная работа со строками      44

[248 rows x 2 columns]

### RIGHT( )

In [50]:
%%sql
SELECT email, right(email, 9)
FROM users;

2774 rows affected.

                            email      right
0               jbsnjbf@gmail.com  gmail.com
1                 fjbis@yandex.ru  yandex.ru
2                   jjxbfox@bk.ru  fox@bk.ru
3          isfsobm.nseo@gmail.com  gmail.com
4     koonbnanojj.jofbx@yandex.ru  yandex.ru
...                           ...        ...
2769               abd-mbmb@ya.ru  bmb@ya.ru
2770             nbjsbjds@mail.ru  s@mail.ru
2771            cookboo@gmail.com  gmail.com
2772          fdsnbfo@example.org  ample.org
2773       enbfxseo71@example.net  ample.net

[2774 rows x 2 columns]

### POSITION( )

In [51]:
%%sql
SELECT position('@' IN email)
FROM users;

2774 rows affected.

      position
0            8
1            6
2            8
3           13
4           18
...        ...
2769         9
2770         9
2771         8
2772         8
2773        11

[2774 rows x 1 columns]

### LEFT( )

In [52]:
%%sql
SELECT email, left(email, position('@' IN email))
FROM users;

2774 rows affected.

                            email                left
0               jbsnjbf@gmail.com            jbsnjbf@
1                 fjbis@yandex.ru              fjbis@
2                   jjxbfox@bk.ru            jjxbfox@
3          isfsobm.nseo@gmail.com       isfsobm.nseo@
4     koonbnanojj.jofbx@yandex.ru  koonbnanojj.jofbx@
...                           ...                 ...
2769               abd-mbmb@ya.ru           abd-mbmb@
2770             nbjsbjds@mail.ru           nbjsbjds@
2771            cookboo@gmail.com            cookboo@
2772          fdsnbfo@example.org            fdsnbfo@
2773       enbfxseo71@example.net         enbfxseo71@

[2774 rows x 2 columns]

In [53]:
%%sql
SELECT email, left(email, position('@' IN email) - 1)
FROM users;

2774 rows affected.

                            email               left
0               jbsnjbf@gmail.com            jbsnjbf
1                 fjbis@yandex.ru              fjbis
2                   jjxbfox@bk.ru            jjxbfox
3          isfsobm.nseo@gmail.com       isfsobm.nseo
4     koonbnanojj.jofbx@yandex.ru  koonbnanojj.jofbx
...                           ...                ...
2769               abd-mbmb@ya.ru           abd-mbmb
2770             nbjsbjds@mail.ru           nbjsbjds
2771            cookboo@gmail.com            cookboo
2772          fdsnbfo@example.org            fdsnbfo
2773       enbfxseo71@example.net         enbfxseo71

[2774 rows x 2 columns]

In [54]:
%%sql
SELECT 
	email,
	left(email, position('@' IN email) - 1) AS left_part,
	right(email, length(email) - position('@' IN email)) AS right_part
FROM users;

2774 rows affected.

                            email          left_part   right_part
0               jbsnjbf@gmail.com            jbsnjbf    gmail.com
1                 fjbis@yandex.ru              fjbis    yandex.ru
2                   jjxbfox@bk.ru            jjxbfox        bk.ru
3          isfsobm.nseo@gmail.com       isfsobm.nseo    gmail.com
4     koonbnanojj.jofbx@yandex.ru  koonbnanojj.jofbx    yandex.ru
...                           ...                ...          ...
2769               abd-mbmb@ya.ru           abd-mbmb        ya.ru
2770             nbjsbjds@mail.ru           nbjsbjds      mail.ru
2771            cookboo@gmail.com            cookboo    gmail.com
2772          fdsnbfo@example.org            fdsnbfo  example.org
2773       enbfxseo71@example.net         enbfxseo71  example.net

[2774 rows x 3 columns]


---

### Практика #3

::::{note} Задание 1
:class: dropdown
:open: true
:icon: false
:::{div}
:class: text-xs
Из таблицы `users` требуется вывести следующую информацию о пользователях:
- Идентификатор
- Логин
- Имя
- Фамилия
- Имя в нижнем регистре
- Фамилия в верхнем регистре
- Длина логина

**Столбцы в результате**:
- `id`
- `username`
- `first_name`
- `last_name`
- `lower_first_name`
- `upper_last_name`
- `length_username`

**Сортировка**: \
Результат отсортируйте сначала по убыванию length_username, затем по возрастанию id.
:::
::::

In [55]:
%%sql
SELECT 
	id,
	username,
	first_name,
	last_name,
	LOWER(first_name) lower_first_name,
	UPPER(last_name) upper_last_name,
	length(username) length_username
FROM users
ORDER BY length_username DESC, id;

2774 rows affected.

,id,username,first_name,last_name,lower_first_name,upper_last_name,length_username
0,2808,obaodsnAobnbiodnos,Варвара,Горячева,варвара,ГОРЯЧЕВА,18
1,222,bdonbksdenonob91,Никита,Константинов,никита,КОНСТАНТИНОВ,16
2,240,GobxassBodsnnoss,Варвара,Семенова,варвара,СЕМЕНОВА,16
3,414,nbabdsbYsboskbmb,София,Ефимов,софия,ЕФИМОВ,16
4,699,Dksaxsdbibansobm,NaN,NaN,NaN,NaN,16
...,...,...,...,...,...,...,...
2769,2787,jdo@,Ярослав,Горячева,ярослав,ГОРЯЧЕВА,4
2770,2789,@111,Варвара,Архипов,варвара,АРХИПОВ,4
2771,2796,nsos,Василиса,Медведева,василиса,МЕДВЕДЕВА,4
2772,2788,@,Дарья,Константинов,дарья,КОНСТАНТИНОВ,1
2773,2793,1,NaN,NaN,NaN,NaN,1


---

::::{note} Задание 2
:class: dropdown
:open: true
:icon: false
:::{div}
:class: text-xs
Из таблицы `users` требуется вывести следующую информацию о пользователях:

- Идентификатор
- Логин
- Почта
- Домен электронной почты (вычисляется как часть электронной почты после символа @)

**Столбцы в результате**:
- `id`
- `username`
- `email`
- `domain`

**Сортировка**:
Результат отсортируйте по возрастанию поля `id`.
:::
::::

In [56]:
%%sql
SELECT 
	id,
	username,
	email,
	right(email, length(email) - position('@' IN email)) AS domain
FROM users
ORDER BY id;

2774 rows affected.

        id       username                     email       domain
0        1   bnbnabnsbona   bnbnabnsb.ona@yandex.ru    yandex.ru
1        2         Pbbdob    ibbdob999.00@gmail.com    gmail.com
2        3       ebxnsomo               nsomo@bk.ru        bk.ru
3        4   LsooSioesbdK         1583253@gmail.com    gmail.com
4        5       Dskbnnsb    9158415237fc@gmail.com    gmail.com
...    ...            ...                       ...          ...
2769  2813       coxanb24        fnksan@example.com  example.com
2770  2814      aoxnbxf50     bdsoaaaon@example.net  example.net
2771  2815        xxbabnn  bsfxb.fsxabn@example.com  example.com
2772  2816   dbkbxdsaasna       fdsnbfo@example.org  example.org
2773  2817  jbesnab_ooojo    enbfxseo71@example.net  example.net

[2774 rows x 4 columns]


---

::::{note} Задание 3
:class: dropdown
:open: true
:icon: false
:::{div}
:class: text-xs

Из таблицы `users` требуется вывести информацию о пользователях, которые имеют домен электронной почты bk.ru.

**Столбцы в результате**:
- `id`
- `username`
- `email`

**Сортировка**:
Результат отсортируйте по возрастанию поля `id`.
:::
::::

In [57]:
%%sql
SELECT 
	id,
	username,
	email
FROM users
WHERE lower(email) LIKE '%@bk.ru'
ORDER BY id;

51 rows affected.

      id    username              email
0      3    ebxnsomo        nsomo@bk.ru
1     77   bxakbasmo    bxakbasmo@bk.ru
2    161     Bbfxsom        fffd4@bk.ru
3    175    Snobfbmb        f_nno@bk.ru
4    200        ADff        b.b-f@bk.ru
..   ...         ...                ...
46  2479  TskBbosna1     a.nmsxsn@bk.ru
47  2585    DsdsbxbK        nbfsd@bk.ru
48  2664      Ifbobm  sfbobm_sdsb@bk.ru
49  2693      b001nn   b.n.n.1992@bk.ru
50  2704    bkoadsen      koadsen@bk.ru

[51 rows x 3 columns]

:::{note} Дополнительная задача
:class: dropdown
:open: true
:icon: false

Как можно отфильтровать из таблицы все платежи по жку (может писаться в description как ЖКУ, жку, ЖКХ, жкх), с тем ограничением, что диалект нашего SQL поддерживает только LIKE? При этом в описании могут быть слова «платежку», «задержку» и тд. Также могут быть знаки препинания, как до, так и после. Слово может быть и первым, и последний, и по середине. 

Жду ваши ответы))
Пример начала запроса:
```sql
SELECT * FROM transaction
WHERE description like …
```
Понимаю, что оптимально здесь использовать регулярные выражения, но прошу решить задачу без них)

Решение 1 (в лоб)

```sql
%%sql
SELECT * 
FROM transaction
WHERE LOWER(description) LIKE '% жку %'
   OR LOWER(description) LIKE 'жку %'
   OR LOWER(description) LIKE '% жку'
   OR LOWER(description) = 'жку'
   OR LOWER(description) LIKE '% жкх %'
   OR LOWER(description) LIKE 'жкх %'
   OR LOWER(description) LIKE '% жкх'
   OR LOWER(description) = 'жкх';
```

---

Решение 2 (регулярные выражения)

Как эту проблему решают **регулярные выражения** `RegEx`: \
Регулярные выражения – это специальный язык описания текстовых шаблонов. В PostgreSQL для этого есть оператор `~*` (поиск по регулярному выражению без учета регистра). Идеальный и пуленепробиваемый запрос выглядел бы так:
```sql
SELECT * FROM transaction
WHERE description ~* '\b(жку|жкх)\b';
```
Почему это магия:
- `\b` – это специальный символ регулярных выражений, который означает *граница слова* (word boundary).
- Границей слова движок RegEx считает *всё что угодно, кроме букв*: пробел, точку, запятую, скобку, начало строки или конец строки.
- Этот запрос мгновенно найдет "ЖКУ,", "(ЖКУ)", "ЖКУ.", "оплата ЖКУ" и при этом железобетонно проигнорирует "платежку", потому что между буквой е и ж в слове платежку нет границы слова!

Поэтому регулярные выражения оптимальны: они пишутся в одну строчку и учитывают абсолютно все знаки препинания в мире за один раз.

- Круглые скобки `()` создают группу условий. Они ограничивают зону действия вертикальной черты (как скобки в математике).
- Символ `|` разделяет варианты внутри этой группы. Конструкция (жку|жкх) говорит движку регулярных выражений: Найди мне либо точную последовательность букв "жку", ЛИБО последовательность "жкх". Если бы символа `|` не существовало, пришлось бы писать два отдельных регулярных выражения и связывать их через привычный SQL-оператор OR:
```sql
WHERE description ~* '\bжку\b'
   OR description ~* '\bжкх\b'
```

---

Решение 3 (элегантное):
```sql
SELECT *
FROM transaction
WHERE INITCAP(description) LIKE '%Жку%'
OR INITCAP(description) LIKE '%Жкх%';
```

In [60]:
%%sql
WITH transaction as (
select 'Оплата за задержку' as description 
union all
select 'Платежка за жку, за октябрь 2025' as description
union all
select 'жку за октябрь 2025' as description
union all
select 'жкх' as description
union all
select 'оплата, жкх.' as description
union all
select 'ЖКУ' as description
union all
select 'жкх: оплата задежки'
union all
select 'Надо проверить платежку'
union all
select 'Оплата за (жку)'
    )
--
SELECT *
FROM transaction
WHERE INITCAP(description) LIKE '%Жку%'
OR INITCAP(description) LIKE '%Жкх%';

7 rows affected.

                        description
0  Платежка за жку, за октябрь 2025
1               жку за октябрь 2025
2                               жкх
3                      оплата, жкх.
4                               ЖКУ
5               жкх: оплата задежки
6                   Оплата за (жку)


---

## 6. Полезные операторы

В этом уроке продолжаем делать SQL-запросы сложнее. Вы узнаете, как подставить значение по умолчанию, избежать деления на ноль, или применить условную логику прямо в запросе. Эти конструкции особенно полезны, когда работаете с реальными, неидеальными данными.

Вы изучите:
- Подстановку значений по умолчанию: `COALESCE`, `NULLIF`
- Склеивание строк: `CONCAT`, `||`
- Ветвление логики через `CASE WHEN`
- Работа с `NULL` и комбинирование выражений

In [61]:
%%sql
-- Посмотрим на табл. users
SELECT
    id,
    username,
    first_name,
    last_name
FROM users;

2774 rows affected.

        id       username  first_name  last_name
0      198          Pbnnd         NaN        NaN
1       52          fjbis       Элина   Полякова
2      331        jjxbfox      Эмилия  Афанасьев
3      416  nsosabisfsobm         NaN        NaN
4       19       Fofbx196      Эмилия    Фролова
...    ...            ...         ...        ...
2769  1706          Domsd  Константин    Хохлова
2770  2574        odbfonn         Яна   Сухарева
2771  2660        cookboo       Артём    Хохлова
2772  2816   dbkbxdsaasna         NaN        NaN
2773  2817  jbesnab_ooojo         NaN        NaN

[2774 rows x 4 columns]

### CONCAT( )

```sql
-- Объединяет переменное количество аргументов в одну строку
-- Null значения игнорируются.

CONCAT(expression [, ...])
-- expression - любое выражение для объединения.
```

Функция `concat()` и оператор конкатенации `||` объединяет любое число строк в одну. Но есть различия (см. комментарий в запросе).

**Задача**: Чтобы обратиться к юзеру, обратимся по имени и фамилии. Если данных нет, будем писать *Дорогой клиент*.

In [26]:
%%sql
SELECT
    id,
    username,
    first_name,
    last_name,
    first_name || ' ' || last_name AS concat1, -- если есть NULL, то результат NULL
    CONCAT(first_name, ' ', last_name) concat2 -- если есть NULL, то результат строка
FROM users;

2774 rows affected.

,id,username,first_name,last_name,concat1,concat2
0,198,Pbnnd,NaN,NaN,NaN,
1,52,fjbis,Элина,Полякова,Элина Полякова,Элина Полякова
2,331,jjxbfox,Эмилия,Афанасьев,Эмилия Афанасьев,Эмилия Афанасьев
3,416,nsosabisfsobm,NaN,NaN,NaN,
4,19,Fofbx196,Эмилия,Фролова,Эмилия Фролова,Эмилия Фролова
...,...,...,...,...,...,...
2769,1706,Domsd,Константин,Хохлова,Константин Хохлова,Константин Хохлова
2770,2574,odbfonn,Яна,Сухарева,Яна Сухарева,Яна Сухарева
2771,2660,cookboo,Артём,Хохлова,Артём Хохлова,Артём Хохлова
2772,2816,dbkbxdsaasna,NaN,NaN,NaN,
2773,2817,jbesnab_ooojo,NaN,NaN,NaN,

### CONCAT_WS( )

Когда разделитель один и тот же, **удобнее** [`CONCAT_WS`](https://sql-academy.org/ru/blog/sql-string-functions) (**W**ith **S**eparator): \
первый аргумент – разделитель, дальше – склеиваемые части.

In [62]:
%%sql
SELECT
    id,
    first_name,
    last_name,
    first_name || ' ' || last_name AS concat1, -- если есть NULL, то результат NULL
    CONCAT(first_name, ' ', last_name) concat2, -- если есть NULL, то результат строка
    CONCAT_WS(' ', first_name, last_name) concat3 -- первым аргументом разделитель
FROM users;

2774 rows affected.

,id,first_name,last_name,concat1,concat2,concat3
0,198,NaN,NaN,NaN,,
1,52,Элина,Полякова,Элина Полякова,Элина Полякова,Элина Полякова
2,331,Эмилия,Афанасьев,Эмилия Афанасьев,Эмилия Афанасьев,Эмилия Афанасьев
3,416,NaN,NaN,NaN,,
4,19,Эмилия,Фролова,Эмилия Фролова,Эмилия Фролова,Эмилия Фролова
...,...,...,...,...,...,...
2769,1706,Константин,Хохлова,Константин Хохлова,Константин Хохлова,Константин Хохлова
2770,2574,Яна,Сухарева,Яна Сухарева,Яна Сухарева,Яна Сухарева
2771,2660,Артём,Хохлова,Артём Хохлова,Артём Хохлова,Артём Хохлова
2772,2816,NaN,NaN,NaN,,
2773,2817,NaN,NaN,NaN,,

### COALESCE( )

Загружаем какое-то количество аргументов и `COALESCE` смотрит значение столбца в каждой строчке на значение аргумента NULL или не NULL.
```sql
-- Возвращает первое не-null значение из списка
-- vali - Значения для проверки
COALESCE(val1, val2, ..., valn)
```
Если val1 не NULL - выводим, если val1 NULL - идем дальше, проверяем val2. \
`COALESCE` выводит первое значение, которое не NULL.

:::{warning} Важно
Пустая строка это не NULL
:::

In [17]:
%%sql
SELECT '' != NULL;

1 rows affected.

  ?column?
0     None

In [18]:
%%sql
SELECT '' IS NOT NULL;

1 rows affected.

   ?column?
0      True

In [67]:
%%sql
SELECT
    id,
    first_name,
    last_name,
    first_name || ' ' || last_name AS concat1,
        -- если есть NULL, то результат NULL
    CONCAT(first_name, ' ', last_name) concat2,
        -- если есть NULL, то результат строка
    CONCAT_WS(' ', first_name, last_name) concat3,
        -- первым аргументом разделитель
    COALESCE(first_name || ' ' || last_name, 'Дорогой клиент') concat4
        -- работает, т.к. `||` выдает явный NULL
FROM users;

2774 rows affected.

,id,first_name,last_name,concat1,concat2,concat3,concat4
0,198,NaN,NaN,NaN,,,Дорогой клиент
1,52,Элина,Полякова,Элина Полякова,Элина Полякова,Элина Полякова,Элина Полякова
2,331,Эмилия,Афанасьев,Эмилия Афанасьев,Эмилия Афанасьев,Эмилия Афанасьев,Эмилия Афанасьев
3,416,NaN,NaN,NaN,,,Дорогой клиент
4,19,Эмилия,Фролова,Эмилия Фролова,Эмилия Фролова,Эмилия Фролова,Эмилия Фролова
...,...,...,...,...,...,...,...
2769,1706,Константин,Хохлова,Константин Хохлова,Константин Хохлова,Константин Хохлова,Константин Хохлова
2770,2574,Яна,Сухарева,Яна Сухарева,Яна Сухарева,Яна Сухарева,Яна Сухарева
2771,2660,Артём,Хохлова,Артём Хохлова,Артём Хохлова,Артём Хохлова,Артём Хохлова
2772,2816,NaN,NaN,NaN,,,Дорогой клиент
2773,2817,NaN,NaN,NaN,,,Дорогой клиент

In [68]:
%%sql
SELECT
    first_name,
    last_name,
    first_name || ' ' || last_name AS concat1,
    CONCAT(first_name, ' ', last_name) concat2,
    CONCAT_WS(' ', first_name, last_name) concat3,
    COALESCE(first_name || ' ' || last_name, 'Дорогой клиент') concat4,
        -- работает, т.к. `||` выдает явный NULL
    COALESCE(CONCAT(first_name, ' ', last_name), 'Дорогой клиент') concat5
        -- не корректно, т.к. `CONCAT` не выдает NULL (пустая строка IS NOT NULL)
FROM users;

2774 rows affected.

,first_name,last_name,concat1,concat2,concat3,concat4,concat5
0,NaN,NaN,NaN,,,Дорогой клиент,
1,Элина,Полякова,Элина Полякова,Элина Полякова,Элина Полякова,Элина Полякова,Элина Полякова
2,Эмилия,Афанасьев,Эмилия Афанасьев,Эмилия Афанасьев,Эмилия Афанасьев,Эмилия Афанасьев,Эмилия Афанасьев
3,NaN,NaN,NaN,,,Дорогой клиент,
4,Эмилия,Фролова,Эмилия Фролова,Эмилия Фролова,Эмилия Фролова,Эмилия Фролова,Эмилия Фролова
...,...,...,...,...,...,...,...
2769,Константин,Хохлова,Константин Хохлова,Константин Хохлова,Константин Хохлова,Константин Хохлова,Константин Хохлова
2770,Яна,Сухарева,Яна Сухарева,Яна Сухарева,Яна Сухарева,Яна Сухарева,Яна Сухарева
2771,Артём,Хохлова,Артём Хохлова,Артём Хохлова,Артём Хохлова,Артём Хохлова,Артём Хохлова
2772,NaN,NaN,NaN,,,Дорогой клиент,
2773,NaN,NaN,NaN,,,Дорогой клиент,

:::{hint} Использовать `CONCAT` с `COALESCE` нельзя.
Но если очень хочется, то можно.
:::

In [24]:
%%sql
-- Посмотрим на вывод: как и ожидалось вместо NULL строка
SELECT CONCAT(first_name, ' ', last_name)
FROM users;

2774 rows affected.

                  concat
0
1         Элина Полякова
2       Эмилия Афанасьев
3
4         Эмилия Фролова
...                  ...
2769  Константин Хохлова
2770        Яна Сухарева
2771       Артём Хохлова
2772
2773

[2774 rows x 1 columns]

Используем строку `CONCAT(first_name, ' ', last_name)` чтобы реализовать конструкцию таким образом: если у нас получилась пустая строка, преобразуем ее в NULL, а потом этот NULL обработает `COALESCE` и выведет *'Дорогой клиент'*.

Используем вместо `CONCAT` -> `CONCAT_WS`, т.к. если у нас много аргументов (много строк нужно объединить), то удобнее написать разделитель только один раз.

### NULLIF( )

```sql
NULLIF(value_1, value_2)
```

Сравнивает результат работы первого аргумента и второго аргумента. \
Если они совпадают – выводит NULL. Если не совпадают – выводит первый аргумент.

In [28]:
%%sql
-- Все значения где была пустая строка "обнулились"
SELECT NULLIF(CONCAT_WS(' ', first_name, last_name), '')
FROM users;

2774 rows affected.

                  nullif
0                    NaN
1         Элина Полякова
2       Эмилия Афанасьев
3                    NaN
4         Эмилия Фролова
...                  ...
2769  Константин Хохлова
2770        Яна Сухарева
2771       Артём Хохлова
2772                 NaN
2773                 NaN

[2774 rows x 1 columns]

In [31]:
%%sql
-- Сравним вывод
SELECT 
    CONCAT_WS(' ', first_name, last_name),
    NULLIF(CONCAT_WS(' ', first_name, last_name), '')
FROM users;

2774 rows affected.

               concat_ws              nullif
0                                        NaN
1         Элина Полякова      Элина Полякова
2       Эмилия Афанасьев    Эмилия Афанасьев
3                                        NaN
4         Эмилия Фролова      Эмилия Фролова
...                  ...                 ...
2769  Константин Хохлова  Константин Хохлова
2770        Яна Сухарева        Яна Сухарева
2771       Артём Хохлова       Артём Хохлова
2772                                     NaN
2773                                     NaN

[2774 rows x 2 columns]

Научились превращать пустую строку в NULL, а значит теперь можем пойти обратно в наш запрос и добавить в `COALESCE` строку `NULLIF`

In [70]:
%%sql
SELECT
 last_name,
 first_name || ' ' || last_name AS concat1,
 CONCAT(first_name, ' ', last_name) concat2,
 CONCAT_WS(' ', first_name, last_name) concat3,
 COALESCE(first_name || ' ' || last_name, 'Дорогой клиент') concat4,
 COALESCE(CONCAT(first_name, ' ', last_name), 'Дорогой клиент') concat5,
 COALESCE(NULLIF(CONCAT_WS(' ', first_name, last_name), ''), 'Дорогой клиент') concat6
      -- работает, т.к. NULLIF превращает пустую строку в NULL
FROM users;

2774 rows affected.

,last_name,concat1,concat2,concat3,concat4,concat5,concat6
0,NaN,NaN,,,Дорогой клиент,,Дорогой клиент
1,Полякова,Элина Полякова,Элина Полякова,Элина Полякова,Элина Полякова,Элина Полякова,Элина Полякова
2,Афанасьев,Эмилия Афанасьев,Эмилия Афанасьев,Эмилия Афанасьев,Эмилия Афанасьев,Эмилия Афанасьев,Эмилия Афанасьев
3,NaN,NaN,,,Дорогой клиент,,Дорогой клиент
4,Фролова,Эмилия Фролова,Эмилия Фролова,Эмилия Фролова,Эмилия Фролова,Эмилия Фролова,Эмилия Фролова
...,...,...,...,...,...,...,...
2769,Хохлова,Константин Хохлова,Константин Хохлова,Константин Хохлова,Константин Хохлова,Константин Хохлова,Константин Хохлова
2770,Сухарева,Яна Сухарева,Яна Сухарева,Яна Сухарева,Яна Сухарева,Яна Сухарева,Яна Сухарева
2771,Хохлова,Артём Хохлова,Артём Хохлова,Артём Хохлова,Артём Хохлова,Артём Хохлова,Артём Хохлова
2772,NaN,NaN,,,Дорогой клиент,,Дорогой клиент
2773,NaN,NaN,,,Дорогой клиент,,Дорогой клиент

### CASE( )

In [72]:
%%sql
SELECT id, username, first_name, last_name, score,
    CASE 
        WHEN score < 100 THEN 'low'
        WHEN score < 500 THEN 'medium'
        ELSE 'high'
    END AS score2
FROM users
ORDER BY score2; -- чтобы увидеть разницу в усеченном выводе Pandas

2774 rows affected.

        id          username first_name  last_name  score  score2
0     2282  ssdsbnjofsebasbn  Александр  Степанова    790    high
1      139           IabxBsb  Елизавета    Федоров    500    high
2     2558            Knonsb    Варвара     Ефимов    805    high
3     2491       smksonbsdbm  Александр   Тимофеев    670    high
4       19          Fofbx196     Эмилия    Фролова      0     low
...    ...               ...        ...        ...    ...     ...
2769  2452        bdcodsbobm    Варвара   Синицына    110  medium
2770  1982       cxbbfnbxis9     Даниил  Медведева    125  medium
2771  2674         nbdjebdbk     Никита   Баранова    145  medium
2772  2575        Lssfksdb88      Макар   Артемова    395  medium
2773  2607    bnnbnsfbxbmboo    Даниэль   Щербаков    250  medium

[2774 rows x 6 columns]

Как только выполняется одно из условий, оператор останавливается.

Внутри можно *наслаивать как угодно*, например
```sql
WHEN score < 100 AND is_active = 1 THEN 'low'
```

Применим `CASE()` к нашей задаче

In [73]:
%%sql
-- Вначале проверим что если имя NULL, то и фамилия NULL
-- Есть строки где задано только имя или только фамилия?

SELECT first_name, last_name
FROM users
WHERE first_name IS NULL AND last_name IS NOT NULL;
-- WHERE first_name IS NOT NULL AND last_name IS NULL

Empty DataFrame
Columns: [first_name, last_name]
Index: []

Получили, что если имя NULL, то и фамилия NULL -- т.е. не требуется использовать оба параметра. Возмьмем только имя.

In [75]:
%%sql
SELECT
    first_name || ' ' || last_name AS concat1,
        -- если есть NULL, то результат NULL
    CONCAT(first_name, ' ', last_name) concat2,
        -- если есть NULL, то результат строка
    CONCAT_WS(' ', first_name, last_name) concat3,
        -- указываем первым аргументом разделитель
    COALESCE(first_name || ' ' || last_name, 'Дорогой клиент') concat4,
        -- работает, т.к. `||` выдает явный NULL
    COALESCE(CONCAT(first_name, ' ', last_name), 'Дорогой клиент') concat5,
        -- не корректно, т.к. `CONCAT` не выдает NULL (пустая строка IS NOT NULL)
    COALESCE(NULLIF(CONCAT_WS(' ', first_name, last_name), ''), 'Дорогой клиент') concat6,
        -- работает, т.к. NULLIF превращает пустую строку в NULL
    CASE
        WHEN first_name IS NULL THEN 'Дорогой клиент'
        ELSE CONCAT_WS(' ', first_name, last_name)
    END AS concat7
FROM users;

2774 rows affected.

,concat1,concat2,concat3,concat4,concat5,concat6,concat7
0,NaN,,,Дорогой клиент,,Дорогой клиент,Дорогой клиент
1,Элина Полякова,Элина Полякова,Элина Полякова,Элина Полякова,Элина Полякова,Элина Полякова,Элина Полякова
2,Эмилия Афанасьев,Эмилия Афанасьев,Эмилия Афанасьев,Эмилия Афанасьев,Эмилия Афанасьев,Эмилия Афанасьев,Эмилия Афанасьев
3,NaN,,,Дорогой клиент,,Дорогой клиент,Дорогой клиент
4,Эмилия Фролова,Эмилия Фролова,Эмилия Фролова,Эмилия Фролова,Эмилия Фролова,Эмилия Фролова,Эмилия Фролова
...,...,...,...,...,...,...,...
2769,Константин Хохлова,Константин Хохлова,Константин Хохлова,Константин Хохлова,Константин Хохлова,Константин Хохлова,Константин Хохлова
2770,Яна Сухарева,Яна Сухарева,Яна Сухарева,Яна Сухарева,Яна Сухарева,Яна Сухарева,Яна Сухарева
2771,Артём Хохлова,Артём Хохлова,Артём Хохлова,Артём Хохлова,Артём Хохлова,Артём Хохлова,Артём Хохлова
2772,NaN,,,Дорогой клиент,,Дорогой клиент,Дорогой клиент
2773,NaN,,,Дорогой клиент,,Дорогой клиент,Дорогой клиент

:::{hint} [А вы используете CASE?](https://t.me/c/3825910988/739)

Иногда вы можете сократить свои запросы в несколько раз, используя его, но мы часто наблюдаем, что новички игнорируют использование этого оператора.

Например, была задача — вывести поле sum со знаком -, если type=1 и со знаком +, если type=0.

Пользователь предложил такое решение:
```sql
SELECT id, sum FROM transactions t 
WHERE type = 0
UNION ALL
SELECT id, -sum  FROM transactions t 
WHERE type = 1
```
В целом, не так плохо. Но это всего лишь промежуточный запрос, задача была намного масштабней и таких конструкций в итоге было наворочено очень много.
А вот то же самое с CASE:
```sql
SELECT id,
       CASE
          WHEN type = 0
          THEN sum
          ELSE -sum
       END
FROM transactions t
```
Согласитесь, это намного лаконичнее и понятнее! 👍

Более того, CASE можно использовать ещё много для чего. Например, чтобы сделать из «длинной» таблицы «широкую». Или для суммирования/подсчёта количества внутри агрегатных функций (да, CASE можно использовать внутри агрегатных функций!).

А ещё, кстати, COALESCE — это просто «синтаксический сахар» и обёртка вокруг CASE.

Используя оператор CASE в SQL, вы можете легко выполнять различные условные операции и улучшать читаемость ваших запросов. Не игнорируйте этот мощный инструмент!
:::

### Практика #4

::::{note} Задание 1
:class: dropdown
:open: true
:icon: false
:::{div}
:class: text-xs
Из таблицы `users` требуется вывести следующую информацию о пользователях:
- Идентификатор
- Логин
- Текстовое описание идентификатора формата "Идентификатор пользователя равен x", где x - значение `id`

Столбцы в результате
- `id`
- `username`
- `text_user_id` \
Важно: Обратите внимание, что название столбцов в вашем ответе должно в точности совпадать с условием.

**Сортировка**: \
Результат отсортируйте по возрастанию поля `id`.
:::
::::

In [3]:
%%sql
SELECT 
	id,
	username,
	concat('Идентификатор пользователя равен ', id)
FROM users
ORDER BY id;

2774 rows affected.

        id       username                                 concat
0        1   bnbnabnsbona     Идентификатор пользователя равен 1
1        2         Pbbdob     Идентификатор пользователя равен 2
2        3       ebxnsomo     Идентификатор пользователя равен 3
3        4   LsooSioesbdK     Идентификатор пользователя равен 4
4        5       Dskbnnsb     Идентификатор пользователя равен 5
...    ...            ...                                    ...
2769  2813       coxanb24  Идентификатор пользователя равен 2813
2770  2814      aoxnbxf50  Идентификатор пользователя равен 2814
2771  2815        xxbabnn  Идентификатор пользователя равен 2815
2772  2816   dbkbxdsaasna  Идентификатор пользователя равен 2816
2773  2817  jbesnab_ooojo  Идентификатор пользователя равен 2817

[2774 rows x 3 columns]

::::{note} Задание 2
:class: dropdown
:open: true
:icon: false
:::{div}
:class: text-xs
Из таблицы `users` требуется вывести следующую информацию о пользователях:
- Идентификатор
- Логин
- Имя
- Фамилия
- Приветственное имя пользователя: 
  * если есть имя, то вывести имя пользователя, 
  * если имени нет, но есть фамилия, то вывести фамилию, 
  * если отсутствуют как имя, так и фамилия, то вывести Дорогой друг

**Столбцы в результате**
- `id`
- `username`
- `first_name`
- `last_name`
- `display_name` \
Важно: Обратите внимание, что название столбцов в вашем ответе должно в точности совпадать с условием.

**Сортировка**: \
Результат отсортируйте по возрастанию поля `id`.
:::
::::

In [4]:
%%sql
SELECT 
	id,
	username,
	first_name,
	last_name,
	COALESCE(first_name, last_name, 'Дорогой друг') AS display_name
FROM users
ORDER BY id;

2774 rows affected.

        id       username first_name last_name  display_name
0        1   bnbnabnsbona     Таисия   Ермаков        Таисия
1        2         Pbbdob        NaN       NaN  Дорогой друг
2        3       ebxnsomo     Никита    Петров        Никита
3        4   LsooSioesbdK      София   Ермаков         София
4        5       Dskbnnsb     Филипп   Тарасов        Филипп
...    ...            ...        ...       ...           ...
2769  2813       coxanb24      Демид   Ермаков         Демид
2770  2814      aoxnbxf50    Варвара    Демина       Варвара
2771  2815        xxbabnn       Анна  Столяров          Анна
2772  2816   dbkbxdsaasna        NaN       NaN  Дорогой друг
2773  2817  jbesnab_ooojo        NaN       NaN  Дорогой друг

[2774 rows x 5 columns]

::::{note} Задание 3
:class: dropdown
:open: true
:icon: false
:::{div}
:class: text-xs
Из таблицы `users` требуется вывести следующую информацию о пользователях:
- Идентификатор
- Логин
- Количество очков опыта на платформе
- Группа пользователя по количеству очков опыта на платформе

**Правила присвоения группы пользователю по количеству очков опыта на платформе**:
- Если значение строго больше 300, то Мастер
- Если значение строго больше 150, то Эксперт
- Если значение строго больше 75, то Продвинутый
- В остальных случаях Новичок

**Столбцы в результате**:
- `id`
- `username`
- `score`
- `group_user` \
Важно: Обратите внимание, что название столбцов в вашем ответе должно в точности совпадать с условием.

**Сортировка**: \
Результат отсортируйте по возрастанию поля `id`.
:::
::::

In [5]:
%%sql
SELECT
	id,
	username,
	score,
	CASE
		WHEN score > 300 THEN 'Мастер'
		WHEN score > 150 THEN 'Эксперт'
		WHEN score > 75 THEN 'Продвинутый'
		ELSE 'Новичок'
	END group_user
FROM users
ORDER BY id;

2774 rows affected.

        id       username  score   group_user
0        1   bnbnabnsbona      5      Новичок
1        2         Pbbdob     20      Новичок
2        3       ebxnsomo     95  Продвинутый
3        4   LsooSioesbdK      0      Новичок
4        5       Dskbnnsb     10      Новичок
...    ...            ...    ...          ...
2769  2813       coxanb24      0      Новичок
2770  2814      aoxnbxf50      0      Новичок
2771  2815        xxbabnn      0      Новичок
2772  2816   dbkbxdsaasna      0      Новичок
2773  2817  jbesnab_ooojo      0      Новичок

[2774 rows x 4 columns]


---

## 7. Скалярные функции (дата и время)

Работа с датами - одна из самых частых задач в SQL. В этом уроке вы научитесь извлекать нужные части даты, округлять и форматировать её, вычислять разницу между датами и даже прибавлять интервалы.

Вы изучите:
- Извлечение и округление дат: `EXTRACT`, `DATE_TRUNC`, `TO_CHAR`
- Арифметика с датами: `+`, `-`, `INTERVAL`
- Текущая дата и время: `NOW()`
- Создание даты вручную: `MAKE_DATE`

[Функции форматирования данных](https://postgrespro.ru/docs/postgresql/9.5/functions-formatting)

In [2]:
%%sql
SELECT *
FROM users;

2774 rows affected.

,id,username,first_name,last_name,is_active,date_joined,email,referal_user,company_id,tier,score
0,198,Pbnnd,NaN,NaN,1,2021-11-23 13:58:52.051036,jbsnjbf@gmail.com,NaN,NaN,1,0
1,52,fjbis,Элина,Полякова,1,2021-09-01 12:04:31.148715,fjbis@yandex.ru,NaN,NaN,1,0
2,331,jjxbfox,Эмилия,Афанасьев,1,2021-12-12 07:03:00.583264,jjxbfox@bk.ru,NaN,NaN,1,0
3,416,nsosabisfsobm,NaN,NaN,1,2022-01-02 12:22:43.014039,isfsobm.nseo@gmail.com,NaN,1.0,1,0
4,19,Fofbx196,Эмилия,Фролова,1,2021-04-22 15:37:33.000000,koonbnanojj.jofbx@yandex.ru,NaN,NaN,1,0
...,...,...,...,...,...,...,...,...,...,...,...
2769,1706,Domsd,Константин,Хохлова,1,2022-02-18 05:21:31.631400,abd-mbmb@ya.ru,NaN,NaN,1,10
2770,2574,odbfonn,Яна,Сухарева,1,2022-04-01 12:31:14.559731,nbjsbjds@mail.ru,NaN,4.0,1,0
2771,2660,cookboo,Артём,Хохлова,1,2022-04-08 21:01:54.011350,cookboo@gmail.com,NaN,NaN,1,25
2772,2816,dbkbxdsaasna,NaN,NaN,1,2022-04-21 10:58:08.609494,fdsnbfo@example.org,NaN,4.0,1,0
2773,2817,jbesnab_ooojo,NaN,NaN,0,2022-04-21 12:20:00.000202,enbfxseo71@example.net,NaN,NaN,0,0

Возникают разные задачи:
- Хотим посмотреть регистрации пользователей помесячно, т.е. нам нужно оставить только год и месяц, отрезать время и дату.
- Или хотим посмотреть регистрацию пользователей с разбивкой по дням недели.
- Или посмотреть сколько дней прошло с момента регистрации до совершения первой активности пользователем, т.е. соединяем две таблички регистрация, активность и вычитаем одно из другого, т.е. вычитание дат.
- Хотим посмотреть сколько времени прошло до покупки.
- Хотим посмотреть сколько времени прошло между текущим моментом и регистрацией.
- Хотим посмотреть сколько действий совершил пользователь в течение 3-7-30 дней после регистрации и все это в одном запросе.

Для того, чтобы их решать нужно знать *всего лишь парочку* функций и просто в нужный момент их применять.

:::{note} В Postgres достаточно удобно работать с дата-временем
:class: simple dropdown
:open: true
:icon: false

Потому что, например, в MySQL чтобы вычесть из даты дату нужно использовать специальную функцию, а в Postges достаточно просто поставить знак *минус*.
:::

In [4]:
%%sql
SELECT
    username,
    date_joined
FROM users;

2774 rows affected.

           username                date_joined
0             Pbnnd 2021-11-23 13:58:52.051036
1             fjbis 2021-09-01 12:04:31.148715
2           jjxbfox 2021-12-12 07:03:00.583264
3     nsosabisfsobm 2022-01-02 12:22:43.014039
4          Fofbx196 2021-04-22 15:37:33.000000
...             ...                        ...
2769          Domsd 2022-02-18 05:21:31.631400
2770        odbfonn 2022-04-01 12:31:14.559731
2771        cookboo 2022-04-08 21:01:54.011350
2772   dbkbxdsaasna 2022-04-21 10:58:08.609494
2773  jbesnab_ooojo 2022-04-21 12:20:00.000202

[2774 rows x 2 columns]

Первое что нужно научиться делать - это вытаскивать какие-то конкретные части даты или времени. Чаще всего пригождается вытащить год, месяц, день - когда мы просто хотим обрезать время.

### TO_CHAR( )

[Переводит дату/время или число в строку по нужному формату](https://postgrespro.ru/docs/postgresql/current/functions-formatting).

```sql
-- PostgreSQL

TO_CHAR(timestamp, format)
--
SELECT TO_CHAR(NOW(), 'YYYY-MM-DD')
```
`timestamp` - Значение для преобразования \
`format` - Строка формата

In [19]:
%%sql
SELECT
    username,
    date_joined,
    TO_CHAR(date_joined, 'YYYY-MM') AS ym,
    TO_CHAR(date_joined, 'YYYY-MM-DD') AS ymd
FROM users;

2774 rows affected.

           username                date_joined       ym         ymd
0             Pbnnd 2021-11-23 13:58:52.051036  2021-11  2021-11-23
1             fjbis 2021-09-01 12:04:31.148715  2021-09  2021-09-01
2           jjxbfox 2021-12-12 07:03:00.583264  2021-12  2021-12-12
3     nsosabisfsobm 2022-01-02 12:22:43.014039  2022-01  2022-01-02
4          Fofbx196 2021-04-22 15:37:33.000000  2021-04  2021-04-22
...             ...                        ...      ...         ...
2769          Domsd 2022-02-18 05:21:31.631400  2022-02  2022-02-18
2770        odbfonn 2022-04-01 12:31:14.559731  2022-04  2022-04-01
2771        cookboo 2022-04-08 21:01:54.011350  2022-04  2022-04-08
2772   dbkbxdsaasna 2022-04-21 10:58:08.609494  2022-04  2022-04-21
2773  jbesnab_ooojo 2022-04-21 12:20:00.000202  2022-04  2022-04-21

[2774 rows x 4 columns]

Не самый эффективный способ работы с датавременем, потому что преобразование типа из одного в другой сжирает *какое-то* количество ресурсов, особенно если мы фильтрацию по этому какую-то делаем. Но способ настолько простой, что позволяет делать такие конструкции:

In [18]:
%%sql
SELECT
    username,
    date_joined,
    TO_CHAR(date_joined, 'YYYY-MM') AS ym,
    TO_CHAR(date_joined, 'YYYY-MM-DD') AS ymd
FROM users
--
WHERE TO_CHAR(date_joined, 'YYYY-MM') = '2021-11';

210 rows affected.

        username                date_joined       ym         ymd
0          Pbnnd 2021-11-23 13:58:52.051036  2021-11  2021-11-23
1          Gxbfb 2021-11-23 10:26:54.333004  2021-11  2021-11-23
2       bxsfonob 2021-11-09 13:55:52.378712  2021-11  2021-11-09
3       bdabof06 2021-11-20 12:22:44.472572  2021-11  2021-11-20
4    Nsosabeno97 2021-11-24 12:23:25.416999  2021-11  2021-11-24
..           ...                        ...      ...         ...
205     iskbnos2 2021-11-30 11:28:33.453778  2021-11  2021-11-30
206        nnofo 2021-11-30 16:13:38.745247  2021-11  2021-11-30
207      oma1971 2021-11-30 17:25:06.170361  2021-11  2021-11-30
208  aonibidomsn 2021-11-30 17:52:53.273874  2021-11  2021-11-30
209    IxbnSsabx 2021-11-30 23:28:56.542097  2021-11  2021-11-30

[210 rows x 4 columns]

Если у нас огромное количество данных или другие ограничения из-за которых идет борьба за ресурсы и нам нужно ускорять выполнение нашего кода, то приводить датавремя в строку и сравнивать со строкой может быть не самым оптимальным решением.

Но честно скажу, за все время работы прям с реальным ограничением такой конструкции столкнулся 1 раз за 10 лет. Поэтому рекомендую такую конструкцию, т.к. она реально удобна.

Альтернативный вариант:

### DATE_TRUNC( )

[Обрезает дату/время до указанной точности](https://postgrespro.ru/docs/postgresql/18/functions-datetime#FUNCTIONS-DATETIME-TRUNC).
```sql
-- PostgreSQL

DATE_TRUNC(field, source)
--
SELECT DATE_TRUNC('month', TIMESTAMP '2023-02-15')
```
`field` - определяет до какой **точности** обрезать входное значение (year, month, day и т.д.) \
`source` - значение даты/времени, выражение типа `timestamp`, `timestamp with time zone` или `interval`. (Значения типов `date` и `time` автоматически приводятся к типам `timestamp` и `interval`, соответственно.)

[Коды форматирования даты/времени](https://postgrespro.ru/docs/postgresql/9.5/functions-formatting)

In [32]:
%reload_ext sql

In [7]:
%%sql
SELECT
    username,
    date_joined,
    TO_CHAR(date_joined, 'YYYY-MM') AS ym,
    TO_CHAR(date_joined, 'YYYY-MM-DD') AS ymd,
    DATE_TRUNC('month', date_joined) AS ym2,
        -- отрежет все время и дату приведет на 1-й день месяца
    DATE_TRUNC('day', date_joined) AS ymd2,
    DATE_TRUNC('year', date_joined) AS "year"
FROM users;

2774 rows affected.

,username,date_joined,ym,ymd,ym2,ymd2,year
0,Pbnnd,2021-11-23 13:58:52.051036,2021-11,2021-11-23,2021-11-01,2021-11-23,2021-01-01
1,fjbis,2021-09-01 12:04:31.148715,2021-09,2021-09-01,2021-09-01,2021-09-01,2021-01-01
2,jjxbfox,2021-12-12 07:03:00.583264,2021-12,2021-12-12,2021-12-01,2021-12-12,2021-01-01
3,nsosabisfsobm,2022-01-02 12:22:43.014039,2022-01,2022-01-02,2022-01-01,2022-01-02,2022-01-01
4,Fofbx196,2021-04-22 15:37:33.000000,2021-04,2021-04-22,2021-04-01,2021-04-22,2021-01-01
...,...,...,...,...,...,...,...
2769,Domsd,2022-02-18 05:21:31.631400,2022-02,2022-02-18,2022-02-01,2022-02-18,2022-01-01
2770,odbfonn,2022-04-01 12:31:14.559731,2022-04,2022-04-01,2022-04-01,2022-04-01,2022-01-01
2771,cookboo,2022-04-08 21:01:54.011350,2022-04,2022-04-08,2022-04-01,2022-04-08,2022-01-01
2772,dbkbxdsaasna,2022-04-21 10:58:08.609494,2022-04,2022-04-21,2022-04-01,2022-04-21,2022-01-01
2773,jbesnab_ooojo,2022-04-21 12:20:00.000202,2022-04,2022-04-21,2022-04-01,2022-04-21,2022-01-01

Для вычитания дат мы можем собрать дату:

### MAKE_DATE( )

Создает дату из года, месяца и дня.
```sql
MAKE_DATE(year, month, day)
--
SELECT MAKE_DATE(2025, 6, 5)
```

In [24]:
%%sql
SELECT
    username,
    date_joined,
    MAKE_DATE(2037, 5, 5)
FROM users;

2774 rows affected.

           username                date_joined   make_date
0             Pbnnd 2021-11-23 13:58:52.051036  2037-05-05
1             fjbis 2021-09-01 12:04:31.148715  2037-05-05
2           jjxbfox 2021-12-12 07:03:00.583264  2037-05-05
3     nsosabisfsobm 2022-01-02 12:22:43.014039  2037-05-05
4          Fofbx196 2021-04-22 15:37:33.000000  2037-05-05
...             ...                        ...         ...
2769          Domsd 2022-02-18 05:21:31.631400  2037-05-05
2770        odbfonn 2022-04-01 12:31:14.559731  2037-05-05
2771        cookboo 2022-04-08 21:01:54.011350  2037-05-05
2772   dbkbxdsaasna 2022-04-21 10:58:08.609494  2037-05-05
2773  jbesnab_ooojo 2022-04-21 12:20:00.000202  2037-05-05

[2774 rows x 3 columns]

In [38]:
%%sql
SELECT
    username,
    date_joined,
    MAKE_DATE(2037, 5, 5) - date_joined AS diff_exact
        -- Разница времени между собранной датой и ..
FROM users;

2774 rows affected.

           username                date_joined                diff_exact
0             Pbnnd 2021-11-23 13:58:52.051036 5641 days 10:01:07.948964
1             fjbis 2021-09-01 12:04:31.148715 5724 days 11:55:28.851285
2           jjxbfox 2021-12-12 07:03:00.583264 5622 days 16:56:59.416736
3     nsosabisfsobm 2022-01-02 12:22:43.014039 5601 days 11:37:16.985961
4          Fofbx196 2021-04-22 15:37:33.000000        5856 days 08:22:27
...             ...                        ...                       ...
2769          Domsd 2022-02-18 05:21:31.631400 5554 days 18:38:28.368600
2770        odbfonn 2022-04-01 12:31:14.559731 5512 days 11:28:45.440269
2771        cookboo 2022-04-08 21:01:54.011350 5505 days 02:58:05.988650
2772   dbkbxdsaasna 2022-04-21 10:58:08.609494 5492 days 13:01:51.390506
2773  jbesnab_ooojo 2022-04-21 12:20:00.000202 5492 days 11:39:59.999798

[2774 rows x 3 columns]

### NOW( )

Возвращает текущую дату и время с временной зоной.
```sql
NOW()
```

In [37]:
%%sql
SELECT
    username,
    date_joined,
    MAKE_DATE(2037, 5, 5) - date_joined AS diff_exact,
    NOW() - date_joined AS diff_now
        -- Разница между текущей датой и определенной
FROM users;

2774 rows affected.

,username,date_joined,diff_exact,diff_now
0,Pbnnd,2021-11-23 13:58:52.051036,5641 days 10:01:07.948964,1747 days 08:25:23.034826
1,fjbis,2021-09-01 12:04:31.148715,5724 days 11:55:28.851285,1830 days 10:19:43.937147
2,jjxbfox,2021-12-12 07:03:00.583264,5622 days 16:56:59.416736,1728 days 15:21:14.502598
3,nsosabisfsobm,2022-01-02 12:22:43.014039,5601 days 11:37:16.985961,1707 days 10:01:32.071823
4,Fofbx196,2021-04-22 15:37:33.000000,5856 days 08:22:27,1962 days 06:46:42.085862
...,...,...,...,...
2769,Domsd,2022-02-18 05:21:31.631400,5554 days 18:38:28.368600,1660 days 17:02:43.454462
2770,odbfonn,2022-04-01 12:31:14.559731,5512 days 11:28:45.440269,1618 days 09:53:00.526131
2771,cookboo,2022-04-08 21:01:54.011350,5505 days 02:58:05.988650,1611 days 01:22:21.074512
2772,dbkbxdsaasna,2022-04-21 10:58:08.609494,5492 days 13:01:51.390506,1598 days 11:26:06.476368
2773,jbesnab_ooojo,2022-04-21 12:20:00.000202,5492 days 11:39:59.999798,1598 days 10:04:15.085660

Если нас не интересует сколько прошло часов, минут. Если нас интересует сколько прошло, например, дней:

### EXTRACT( )

[Извлекает подполя из значения даты/времени](https://postgrespro.ru/docs/postgresql/18/functions-datetime#FUNCTIONS-DATETIME-EXTRACT)

```sql
EXTRACT(field FROM source)
--
SELECT EXTRACT(
		YEAR
		FROM TIMESTAMP '2023-01-01'
	)
```
`field` - Поле для извлечения (year, month, day и т.д.) из значения источника \
`FROM source` - Значение даты/времени; источником должно быть заданное выражением значение типа `timestamp`, `date`, `time` или `interval`
:::{card}
:header: ВОЗВРАЩАЕТ **ЧИСЛО**!
:footer: Поэтому с ней работают обычные математические сравнения с числами: `= 2021`, `> 2020` и т.д.

- `EXTRACT(year FROM ...)` вернёт просто `2021` (число, а не строку).
- `EXTRACT(month FROM ...)` вернёт номер месяца: `1`, `2` ... `12`.
- `EXTRACT(day FROM ...)` вернёт день месяца: `1`, `15`, `31` и т.д.

:::

In [47]:
%%sql
SELECT
    date_joined,
    MAKE_DATE(2037, 5, 5) - date_joined AS diff_exact,
    NOW() - date_joined AS diff_now,
    EXTRACT(days FROM MAKE_DATE(2037, 5, 5) - date_joined) AS diff_days
        -- Вытащи кол-во дней из разницы
FROM users;

2774 rows affected.

,date_joined,diff_exact,diff_now,diff_days
0,2021-11-23 13:58:52.051036,5641 days 10:01:07.948964,1747 days 08:25:23.034826,5641.0
1,2021-09-01 12:04:31.148715,5724 days 11:55:28.851285,1830 days 10:19:43.937147,5724.0
2,2021-12-12 07:03:00.583264,5622 days 16:56:59.416736,1728 days 15:21:14.502598,5622.0
3,2022-01-02 12:22:43.014039,5601 days 11:37:16.985961,1707 days 10:01:32.071823,5601.0
4,2021-04-22 15:37:33.000000,5856 days 08:22:27,1962 days 06:46:42.085862,5856.0
...,...,...,...,...
2769,2022-02-18 05:21:31.631400,5554 days 18:38:28.368600,1660 days 17:02:43.454462,5554.0
2770,2022-04-01 12:31:14.559731,5512 days 11:28:45.440269,1618 days 09:53:00.526131,5512.0
2771,2022-04-08 21:01:54.011350,5505 days 02:58:05.988650,1611 days 01:22:21.074512,5505.0
2772,2022-04-21 10:58:08.609494,5492 days 13:01:51.390506,1598 days 11:26:06.476368,5492.0
2773,2022-04-21 12:20:00.000202,5492 days 11:39:59.999798,1598 days 10:04:15.085660,5492.0

Узнать сколько прошло всего часов:

In [46]:
%%sql
SELECT
    date_joined,
    MAKE_DATE(2037, 5, 5) - date_joined AS diff_exact,
    NOW() - date_joined AS diff_now,
    EXTRACT(days FROM MAKE_DATE(2037, 5, 5) - date_joined) AS diff_days,
    --
    EXTRACT(days FROM MAKE_DATE(2037, 5, 5) - date_joined) * 24 
    + EXTRACT(hours FROM MAKE_DATE(2037, 5, 5) - date_joined) 
    AS diff_hours
FROM users;

2774 rows affected.

,date_joined,diff_exact,diff_now,diff_days,diff_hours
0,2021-11-23 13:58:52.051036,5641 days 10:01:07.948964,1747 days 08:25:23.034826,5641.0,135394.0
1,2021-09-01 12:04:31.148715,5724 days 11:55:28.851285,1830 days 10:19:43.937147,5724.0,137387.0
2,2021-12-12 07:03:00.583264,5622 days 16:56:59.416736,1728 days 15:21:14.502598,5622.0,134944.0
3,2022-01-02 12:22:43.014039,5601 days 11:37:16.985961,1707 days 10:01:32.071823,5601.0,134435.0
4,2021-04-22 15:37:33.000000,5856 days 08:22:27,1962 days 06:46:42.085862,5856.0,140552.0
...,...,...,...,...,...
2769,2022-02-18 05:21:31.631400,5554 days 18:38:28.368600,1660 days 17:02:43.454462,5554.0,133314.0
2770,2022-04-01 12:31:14.559731,5512 days 11:28:45.440269,1618 days 09:53:00.526131,5512.0,132299.0
2771,2022-04-08 21:01:54.011350,5505 days 02:58:05.988650,1611 days 01:22:21.074512,5505.0,132122.0
2772,2022-04-21 10:58:08.609494,5492 days 13:01:51.390506,1598 days 11:26:06.476368,5492.0,131821.0
2773,2022-04-21 12:20:00.000202,5492 days 11:39:59.999798,1598 days 10:04:15.085660,5492.0,131819.0

### INTERVAL( )

In [50]:
%%sql
SELECT
    date_joined,
    date_joined + INTERVAL '3 days' AS future_day,
    date_joined + INTERVAL '3 weeks' AS future_week,
    date_joined + INTERVAL '3 years' AS future_year
FROM users;

2774 rows affected.

,date_joined,future_day,future_week,future_year
0,2021-11-23 13:58:52.051036,2021-11-26 13:58:52.051036,2021-12-14 13:58:52.051036,2024-11-23 13:58:52.051036
1,2021-09-01 12:04:31.148715,2021-09-04 12:04:31.148715,2021-09-22 12:04:31.148715,2024-09-01 12:04:31.148715
2,2021-12-12 07:03:00.583264,2021-12-15 07:03:00.583264,2022-01-02 07:03:00.583264,2024-12-12 07:03:00.583264
3,2022-01-02 12:22:43.014039,2022-01-05 12:22:43.014039,2022-01-23 12:22:43.014039,2025-01-02 12:22:43.014039
4,2021-04-22 15:37:33.000000,2021-04-25 15:37:33.000000,2021-05-13 15:37:33.000000,2024-04-22 15:37:33.000000
...,...,...,...,...
2769,2022-02-18 05:21:31.631400,2022-02-21 05:21:31.631400,2022-03-11 05:21:31.631400,2025-02-18 05:21:31.631400
2770,2022-04-01 12:31:14.559731,2022-04-04 12:31:14.559731,2022-04-22 12:31:14.559731,2025-04-01 12:31:14.559731
2771,2022-04-08 21:01:54.011350,2022-04-11 21:01:54.011350,2022-04-29 21:01:54.011350,2025-04-08 21:01:54.011350
2772,2022-04-21 10:58:08.609494,2022-04-24 10:58:08.609494,2022-05-12 10:58:08.609494,2025-04-21 10:58:08.609494
2773,2022-04-21 12:20:00.000202,2022-04-24 12:20:00.000202,2022-05-12 12:20:00.000202,2025-04-21 12:20:00.000202

Пример конструкции: отфильтровать всех пользователей которые купили подписку в течение 1 суток после регистрации:
```sql
WHERE purchase_date BETWEEN date_joined 
                        AND date_joined + INTERVAL '24 hours'
```

In [58]:
%reload_ext sql

:::{attention} Возвращаемые типы данных (date/time)
:icon: false
- `TO_CHAR` (*To Character*) ➔ всегда возвращает `text` _(строку)_: `'2021-01-01'`
- `DATE_TRUNC` ➔ всегда возвращает `timestamp` (или `timestamptz`): `2021-01-01 00:00:00`
- `DATE 'YYYY-MM-DD'` ➔ возвращает `date` _(литерал даты)_: `2021-01-01`
- `DATE(выражение)` ➔ возвращает `date` _(отсекает время)_: `2021-01-01`
- `MAKE_DATE(YYYY, MM, DD)` ➔ возвращает `date` _(принимает целые числа)_: `2021-01-01`
- `DATE + INTERVAL` ➔ всегда возвращает `timestamp`: `2021-01-01 00:00:00` \
    _но сам по себе INTERVAL (длительность / смещение) – это самостоятельный тип данных `interval`, обозначающий отрезок времени, а не точку на календаре)_
:::

:::{attention} Шпаргалка выбора функции
:icon: false

| Условие в задаче                          | Лучший инструмент   | Пример записи                                     |
| ----------------------------------------- | ------------------- | ------------------------------------------------- |
| **Только год** (в 2022 году)              | EXTRACT             | EXTRACT(year FROM col) = 2022                     |
| **Месяц конкретного года** (в марте 2022) | DATE_TRUNC          | DATE_TRUNC('month', col) = TIMESTAMP '2022-03-01' |
| **Конкретный день** (15 сентября 2022)    | DATE() или интервал | DATE(col) = DATE '2022-09-15'                     |
:::

### Практка #5

::::{note} Задание 1
:class: dropdown
:open: true
:icon: false
:::{div}
:class: text-xs
Из таблицы `users` требуется вывести следующую информацию о пользователях:
- Идентификатор
- Логин
- Почта
- Дата и время регистрации
- Дата и время регистрации, округленная до первого числа месяца (например, `2022-04-21 12:20:00.000202` —> `2022-04-01 00:00:00`)

**Столбцы в результате**
- `id`
- `username`
- `email`
- `date_joined`
- `registration_month_start`

**Сортировка** \
Результат отсортируйте сначала по убыванию поля `date_joined`, а затем по возрастанию поля `id`.
:::
::::

In [52]:
%%sql
-- Практика 5. Задача 1
SELECT
	id,
	username,
	email,
	date_joined,
	date_trunc('month', date_joined) AS registration_month_start
FROM users
ORDER BY date_joined DESC, id;

2774 rows affected.

,id,username,email,date_joined,registration_month_start
0,2817,jbesnab_ooojo,enbfxseo71@example.net,2022-04-21 12:20:00.000202,2022-04-01
1,2816,dbkbxdsaasna,fdsnbfo@example.org,2022-04-21 10:58:08.609494,2022-04-01
2,2815,xxbabnn,bsfxb.fsxabn@example.com,2022-04-20 20:42:15.647099,2022-04-01
3,2814,aoxnbxf50,bdsoaaaon@example.net,2022-04-20 20:37:17.440384,2022-04-01
4,2813,coxanb24,fnksan@example.com,2022-04-20 18:39:47.208602,2022-04-01
...,...,...,...,...,...
2769,9,fonnosna,asfbdsnnbm.fons@mail.ru,2021-03-30 19:40:30.000000,2021-03-01
2770,13,Kbxdbobn,fscbmsanosfon@gmail.com,2021-03-29 18:16:06.000000,2021-03-01
2771,15,Sonno1,ob.fbnmdbf1990@mail.ru,2021-03-29 03:58:58.000000,2021-03-01
2772,18,aixbcssn,jbfksn@list.ru,2021-03-28 17:08:26.000000,2021-03-01
2773,8,foebeb13,jbnbnasxcbcbom@yandex.ru,2021-03-28 08:50:53.000000,2021-03-01

::::{note} Задание 2
:class: dropdown
:open: true
:icon: false
:::{div}
:class: text-xs

Из таблицы `users` требуется вывести следующую информацию о пользователях:
- Идентификатор
- Логин
- Почта
- Дата и время регистрации
- Отформатированная в виде текста дата регистрации в формате `DD Mon YYYY`

**Столбцы в результате**
- `id`
- `username`
- `email`
- `date_joined`
- `formatted_date`

**Сортировка** \
Результат отсортируйте сначала по убыванию поля `date_joined`, а затем по возрастанию поля `id`.
:::
::::

In [53]:
%%sql
-- Практика 5. Задача 2
SELECT
	id,
	username,
	email,
	date_joined,
	TO_CHAR(date_joined, 'DD Mon YYYY') AS formatted_date
FROM users
ORDER BY date_joined DESC, id;

2774 rows affected.

,id,username,email,date_joined,formatted_date
0,2817,jbesnab_ooojo,enbfxseo71@example.net,2022-04-21 12:20:00.000202,21 Apr 2022
1,2816,dbkbxdsaasna,fdsnbfo@example.org,2022-04-21 10:58:08.609494,21 Apr 2022
2,2815,xxbabnn,bsfxb.fsxabn@example.com,2022-04-20 20:42:15.647099,20 Apr 2022
3,2814,aoxnbxf50,bdsoaaaon@example.net,2022-04-20 20:37:17.440384,20 Apr 2022
4,2813,coxanb24,fnksan@example.com,2022-04-20 18:39:47.208602,20 Apr 2022
...,...,...,...,...,...
2769,9,fonnosna,asfbdsnnbm.fons@mail.ru,2021-03-30 19:40:30.000000,30 Mar 2021
2770,13,Kbxdbobn,fscbmsanosfon@gmail.com,2021-03-29 18:16:06.000000,29 Mar 2021
2771,15,Sonno1,ob.fbnmdbf1990@mail.ru,2021-03-29 03:58:58.000000,29 Mar 2021
2772,18,aixbcssn,jbfksn@list.ru,2021-03-28 17:08:26.000000,28 Mar 2021
2773,8,foebeb13,jbnbnasxcbcbom@yandex.ru,2021-03-28 08:50:53.000000,28 Mar 2021

::::{note} Задание 3
:class: dropdown
:open: true
:icon: false
:::{div}
:class: text-xs

Из таблицы `users` требуется вывести следующую информацию о пользователях:
- Идентификатор
- Логин
- Почта
- Дата и время регистрации
- Отформатированная в виде текста дата регистрации в формате год-месяц (`YYYY-MM`)

**толбцы в результате**
- `id`
- `username`
- `email`
- `date_joined`
- `formatted_date`

**Сортировка** \
Результат отсортируйте сначала по убыванию поля `date_joined`, а затем по возрастанию поля `id`.
:::
::::

In [57]:
%%sql
-- Практика 5. Задача 3
SELECT
	id,
	username,
	email,
	date_joined,
	TO_CHAR(date_joined, 'YYYY-MM') AS formatted_date
FROM users
ORDER BY date_joined DESC, id;

2774 rows affected.

,id,username,email,date_joined,formatted_date
0,2817,jbesnab_ooojo,enbfxseo71@example.net,2022-04-21 12:20:00.000202,2022-04
1,2816,dbkbxdsaasna,fdsnbfo@example.org,2022-04-21 10:58:08.609494,2022-04
2,2815,xxbabnn,bsfxb.fsxabn@example.com,2022-04-20 20:42:15.647099,2022-04
3,2814,aoxnbxf50,bdsoaaaon@example.net,2022-04-20 20:37:17.440384,2022-04
4,2813,coxanb24,fnksan@example.com,2022-04-20 18:39:47.208602,2022-04
...,...,...,...,...,...
2769,9,fonnosna,asfbdsnnbm.fons@mail.ru,2021-03-30 19:40:30.000000,2021-03
2770,13,Kbxdbobn,fscbmsanosfon@gmail.com,2021-03-29 18:16:06.000000,2021-03
2771,15,Sonno1,ob.fbnmdbf1990@mail.ru,2021-03-29 03:58:58.000000,2021-03
2772,18,aixbcssn,jbfksn@list.ru,2021-03-28 17:08:26.000000,2021-03
2773,8,foebeb13,jbnbnasxcbcbom@yandex.ru,2021-03-28 08:50:53.000000,2021-03

::::{note} Задание 4
:class: dropdown
:open: true
:icon: false
:::{div}
:class: text-xs

Из таблицы `users` требуется вывести информацию о пользователях, которые зарегистрировались на платформе в течение **45 дней** после `2022-01-01`.

**Столбцы в результате**
- `id`
- `username`
- `date_joined`

**Сортировка** \
Результат отсортируйте сначала по убыванию поля `date_joined`, а затем по возрастанию поля `id`.
:::
::::

In [61]:
%%sql
-- Практика 5. Задача 4
-- ВАРИАНТ 1: `MAKE_DATE`
SELECT
    id,
    username,
    date_joined
FROM users
WHERE date_joined BETWEEN MAKE_DATE(2022, 1, 1) 
                      AND MAKE_DATE(2022, 1, 1) + INTERVAL '45 days'
ORDER BY date_joined DESC, id;

1082 rows affected.

        id          username                date_joined
0     1499            sdsb60 2022-02-14 21:48:26.497276
1     1498              Jbnb 2022-02-14 21:09:58.711464
2     1497        fnsxnmdoms 2022-02-14 21:04:24.317917
3     1496            Lox4so 2022-02-14 20:36:19.759509
4     1495          aona1102 2022-02-14 20:09:36.157977
...    ...               ...                        ...
1077   418          nooaocox 2022-01-03 10:10:41.578200
1078   417            fnbmso 2022-01-02 14:29:29.611485
1079   416     nsosabisfsobm 2022-01-02 12:22:43.014039
1080   415             43B69 2022-01-02 10:07:41.152425
1081   414  nbabdsbYsboskbmb 2022-01-01 13:24:15.143819

[1082 rows x 3 columns]

### DATE

[Типизированный литерал стандарта ANSI SQL](https://postgrespro.ru/docs/postgrespro/current/functions-datetime) (Date Literal):

```sql
DATE 'YYYY-MM-DD'

-- date + integer → date
-- date + interval → timestamp

```
Функция извлечения части даты из даты/времени:
```sql
DATE(datetime)
--
SELECT DATE('2022-12-05 10:37:22')
```

::::{note} Явное лучше неявного
:class: dropdown simple
:open: false
:icon: true

:::{div}
:class: text-xs

Алан Болье формулирует фундаментальный принцип: **Явное лучше неявного** (Explicit is better than implicit).

Когда пишем просто `'2022-01-01'`, для SQL это обычная текстовая строка (литерал неизвестного типа `unknown` или `varchar`). Если будем полагаться на то, что СУБД *сама догадается*, что это дата, ты мы отдаём управление механизму неявного приведения типов (implicit casting). В простых случаях СУБД угадывает, а в сложных (как со знаком + INTERVAL) спотыкается.

**Что означает слово `DATE` перед строкой**?

Конструкция `DATE '2022-01-01'` – это **типизированный литерал стандарта ANSI SQL** (Date Literal).

Запись вида:
```sql
DATE 'YYYY-MM-DD'
```
говорит парсеру базы данных: **Не думай, не угадывай и не воспринимай это как простой текст. Это константа строго типа данных DATE!**

В стандарте SQL точно так же можно явно задавать типы для других констант:
- `TIME '12:30:00'` – литерал времени
- `TIMESTAMP '2022-01-01 12:30:00'` – дата со временем
- `INTERVAL '45 days'` – интервал. Механика здесь ровно та же самая, что и у `DATE '2022-01-01'`.

**В PostgreSQL есть три способа сделать явное приведение**:
1. Стандарт ANSI SQL (работает во всех БД: Oracle, MySQL, Postgres): \
`DATE '2022-01-01'`
2. Специальный синтаксис PostgreSQL (два двоеточия): \
`'2022-01-01'::date`
3. Через функцию конструирования: \
`MAKE_DATE(2022, 1, 1)`

Все три варианта делают **одно и то же**: исключают неявное угадывание и дают 100% гарантию, что база работает именно с датой.
:::
::::

::::{note} `DATE '2022-01-01'` или `DATE('2022-01-01')`
:class: dropdown simple
:open: false
:icon: true

:::{div}
:class: text-xs

Правильны оба варианта, но это принципиально разные механизмы.

Вариант без скобок: `DATE '2022-01-01'`
- **Что это такое**: Это литерал (константа) стандарта ANSI SQL.
- **Как работает**: На этапе разбора текста запроса парсер базы данных видит слово `DATE` перед строковой константой и сразу компилирует её в значение типа `date`.
- **Ограничение**: Сюда нельзя передать переменную или имя столбца. Нельзя написать `DATE date_joined` – будет синтаксическая ошибка. Этот синтаксис предназначен только для фиксированных значений (констант).
- **Где применяется**: Когда пишем фиксированную дату руками в коде запроса.

Вариант со скобками: `DATE(выражение)`
- **Что это такое**: Это вызов функции (или функциональное приведение типа). Передаём внутрь скобок любое выражение (строку, колонку, дату со временем) – и на выходе получаем `date`.
- **Пример**: Если есть колонка `date_joined` со временем `2022-01-15 14:30:00`, то `DATE(date_joined)` отсечёт время и вернёт только дату `2022-01-15`.
- `DATE('2022-01-01')` тоже сработает: функция примет строку и превратит её в дату.

---
**Итог**:
- Если задаём фиксированную дату руками: лучше писать `DATE '2022-01-01'` (мировой стандарт) или `MAKE_DATE(2022, 1, 1)`.
- Если нужно отрезать время от колонки/переменной: используют `DATE(date_joined)` (или `date_joined::date`).

:::
::::

In [ ]:
%%sql
-- Практика 5. Задача 4
-- ВАРИАНТ 2: `DATE`
SELECT
	id,
	username,
	date_joined
FROM users
WHERE date_joined BETWEEN DATE '2022-01-01'
					  AND DATE '2022-01-01' + INTERVAL '45 days'
ORDER BY date_joined DESC, id;

::::{tip} В реальной работе
:class: dropdown simple
:open: true
:icon: true

:::{div}
:class: text-xs

Для простой фильтрации строк `CASE` в блоке `WHERE` стараются не использовать без необходимости, потому что:
- Обычный `date_joined BETWEEN ...` пишется короче и читается легче.
- Простой `BETWEEN` позволяет СУБД использовать индексы по полю `date_joined` (запрос работает в тысячи раз быстрее на больших таблицах).

Но как тренировка понимания того, как работает CASE и как строятся предикаты – хорошее упражнение:
:::
::::

In [ ]:
%%sql
-- Практика 5. Задача 4
-- ВАРИАНТ 3: `CASE WHEN`
SELECT
    id,
    username,
    date_joined
FROM users
WHERE CASE
    WHEN date_joined < MAKE_DATE(2022, 1, 1) THEN 'no'
    WHEN date_joined > MAKE_DATE(2022, 1, 1) + INTERVAL '45 days' THEN 'no'
    ELSE 'yes'
END = 'yes'
ORDER BY date_joined DESC, id;

::::{note} Задание 5
:class: dropdown
:open: true
:icon: false
:::{div}
:class: text-xs

Из таблицы `users` требуется вывести информацию о пользователях, которые зарегистрировались на платформе в 2021 году.

**Столбцы в результате**
- `id`
- `username`
- `date_joined`

**Сортировка** \
Результат отсортируйте по возрастанию поля `id`.
:::
::::

In [64]:
%%sql
-- Практика 5. Задача 5
SELECT
    id,
    username,
    date_joined
FROM users
WHERE TO_CHAR(date_joined, 'YYYY') = '2021'
ORDER BY id;

398 rows affected.

      id      username                date_joined
0      1  bnbnabnsbona 2021-04-21 04:11:56.000000
1      2        Pbbdob 2021-04-15 14:29:43.000000
2      3      ebxnsomo 2021-04-10 10:14:22.000000
3      4  LsooSioesbdK 2021-04-06 12:50:57.000000
4      5      Dskbnnsb 2021-04-21 10:52:34.000000
..   ...           ...                        ...
393  409       Idsbkbn 2021-12-29 16:32:15.958010
394  410    Msxbabmxsn 2021-12-29 18:43:44.145399
395  411        oabxeo 2021-12-30 07:24:19.703396
396  412     oxskf1338 2021-12-30 11:34:00.164469
397  413     Pbmodksnn 2021-12-30 11:56:12.884032

[398 rows x 3 columns]


---
ВАРИАНТЫ: Практика 5. Задача 5

```sql
WHERE EXTRACT(year FROM date_joined) = 2021

-- возвращает число 2021, сравниваем с числом 2021
```

```sql
WHERE DATE_TRUNC('year', date_joined) = TIMESTAMP '2021-01-01'

-- явное лучше неявного
                               -- или = '2021-01-01'
                               -- или = DATE '2021-01-01'
                               -- или = MAKE_DATE(2021, 1, 1)
```
:::{note} Что возвращает каждое выражение:
:class: simple dropdown
:open: false
:icon: false

|                                     |                                                              |                              |                     |
| ----------------------------------- | ------------------------------------------------------------ | ---------------------------- | ------------------- |
| Выражение                           | Что возвращает                                               | Тип данных                   | Пример значения     |
| **DATE_TRUNC('year', date_joined)** | Дата со временем, *усечённая* до начала года                 | **timestamp** (дата и время) | 2021-01-01 00:00:00 |
| **TIMESTAMP '2021-01-01'**          | Константа даты и времени (со временем по умолчанию 00:00:00) | **timestamp** (дата и время) | 2021-01-01 00:00:00 |
| **'2021-01-01'**                    | Обычная строка текста                                        | **unknown / text** (строка)  | '2021-01-01'        |
| **DATE '2021-01-01'**               | Календарная дата без времени                                 | **date** (чистая дата)       | 2021-01-01          |
| **MAKE_DATE(2021, 1, 1)**           | Календарная дата без времени                                 | **date** (чистая дата)       | 2021-01-01          |

Эталон следования правилу **явное лучше неявного** \
`DATE_TRUNC('year', date_joined) = TIMESTAMP '2021-01-01'`
- Слева: `timestamp`.
- Справа: `timestamp`.
- Базе данных **вообще не нужно** тратить ресурсы на неявное приведение типов (type casting). Она видит два абсолютно идентичных типа данных и сравнивает их напрямую бит в бит.
    
Почему они все могут сравниваться с `DATE_TRUNC`? \
`DATE_TRUNC('year', date_joined) = DATE '2021-01-01'`  
PostgreSQL берёт `date` справа и приводит его к `timestamp` (`2021-01-01 00:00:00`). Значения слева и справа совпадают до микросекунды, поэтому равенство срабатывает идеально.
:::

```sql
WHERE date_joined >= DATE '2021-01-01' 
  AND date_joined <  DATE '2022-01-01'

/* явное указание типа DATE – признак хорошего тона, хотя
   PostgreSQL легко догадается сам, т.к. слева `timestamp` */
```

```sql
WHERE date_joined BETWEEN '2021-01-01 00:00:00'
                      AND '2021-12-31 23:59:59.999999'

/* чтобы не ловить микросекунды и не писать кучу девяток,
   разработчики баз данных почти никогда не используют 
   `BETWEEN` для дат со временем */
```

---

::::{note} Задание 6
:class: dropdown
:open: true
:icon: false
:::{div}
:class: text-xs

Из таблицы `users` требуется вывести информацию о пользователях, которые имеют домен электронной почты `bk.ru` и зарегистрировались на платформе в **2022** году.

**Столбцы в результате**
- `id`
- `username`
- `email`
- `date_joined`

**Сортировка** \
Результат отсортируйте по возрастанию поля `id`.
:::
::::

In [14]:
%%sql
-- Практика 5. Задача 6
SELECT
    id,
    username,
    email,
    date_joined
FROM users
-- 1-е место: идиоматичный ILIKE + быстрый числовой EXTRACT
WHERE email ILIKE '%@bk.ru'
  AND EXTRACT(year FROM date_joined) = 2022
/* Альтернативные варианты условий:
  -- 2-е место: через DATE_TRUNC и строгий литерал TIMESTAMP
  email ILIKE '%@bk.ru'
    AND DATE_TRUNC('year', date_joined) = TIMESTAMP '2022-01-01'

  -- 3-е место: через LOWER и строковое форматирование TO_CHAR
  LOWER(email) LIKE '%@bk.ru'
    AND TO_CHAR(date_joined, 'YYYY') = '2022'
*/
ORDER BY id;

43 rows affected.

      id       username              email                date_joined
0    442       Ksxsdd51        osx-m@bk.ru 2022-01-08 12:45:28.812268
1    446         kbdbno    ababobm-m@bk.ru 2022-01-09 16:46:57.926768
2    505  ВышелПокурить       nnfcoa@bk.ru 2022-01-14 00:25:47.549556
3    570        abnbnon      abnbnon@bk.ru 2022-01-17 09:32:37.408200
4    609     Bxbnoabibo      ksxbnbb@bk.ru 2022-01-19 06:53:12.191485
..   ...            ...                ...                        ...
38  2479     TskBbosna1     a.nmsxsn@bk.ru 2022-03-25 13:38:37.097684
39  2585       DsdsbxbK        nbfsd@bk.ru 2022-04-02 17:41:53.579615
40  2664         Ifbobm  sfbobm_sdsb@bk.ru 2022-04-10 17:45:00.646544
41  2693         b001nn   b.n.n.1992@bk.ru 2022-04-13 13:52:23.308589
42  2704       bkoadsen      koadsen@bk.ru 2022-04-14 08:02:27.310101

[43 rows x 4 columns]

::::{note} Задание 7
:class: dropdown
:open: true
:icon: false
:::{div}
:class: text-xs

Из таблицы `users` требуется вывести информацию о пользователях, которые зарегистрировались на платформе в 2021 году либо имеют количество очков опыта на платформе строго больше 100.

**Столбцы в результате**
- `id`
- `username`
- `email`
- `date_joined`
- `score`

**Сортировка** \
Результат отсортируйте по возрастанию поля `id`.
:::
::::

In [15]:
%%sql
-- Практика 5. Задача 7
SELECT
    id,
    username,
    email,
    date_joined,
    score
FROM users
WHERE EXTRACT(year FROM date_joined) = 2021
    OR score > 100
ORDER BY id;

492 rows affected.

,id,username,email,date_joined,score
0,1,bnbnabnsbona,bnbnabnsb.ona@yandex.ru,2021-04-21 04:11:56.000000,5
1,2,Pbbdob,ibbdob999.00@gmail.com,2021-04-15 14:29:43.000000,20
2,3,ebxnsomo,nsomo@bk.ru,2021-04-10 10:14:22.000000,95
3,4,LsooSioesbdK,1583253@gmail.com,2021-04-06 12:50:57.000000,0
4,5,Dskbnnsb,9158415237fc@gmail.com,2021-04-21 10:52:34.000000,10
...,...,...,...,...,...
487,2733,Lonsf,odonb.fxsfnsnsnb@gmail.com,2022-04-15 09:48:06.574002,105
488,2736,abxcsnsnn,abxcsnsnn124@yandex.ru,2022-04-15 12:36:59.444246,155
489,2751,aona5,bnfxbn@alexanyan.tech2,2022-04-16 13:29:37.323708,255
490,2770,bnfxbn23,snm-moa@mail.ru,2022-04-17 15:16:31.995972,215
491,2783,Nsosab_Sbmmb,nsosaobbbnf@gmail.com,2022-04-18 13:15:15.927339,105

::::{note} Задание 8
:class: dropdown
:open: true
:icon: false
:::{div}
:class: text-xs

Из таблицы `users` требуется вывести информацию о пользователях, которые имеют домен `bk.ru` либо `yandex.ru` и при этом зарегистрировались на платформе в 2021 году.

**Столбцы в результате**
- `id`
- `username`
- `email`
- `date_joined`

**Сортировка** \
Результат отсортируйте по возрастанию поля `id`.
:::
::::

In [16]:
%%sql
-- Практика 5. Задача 8
SELECT
    id,
    username,
    email,
    date_joined
FROM users
WHERE (email iLIKE '%@bk.ru'
    OR email iLIKE '%@yandex.ru')
    AND EXTRACT(year FROM date_joined) = 2021
/*  AND DATE_TRUNC('year', date_joined) = TIMESTAMP '2021-01-01' */
ORDER BY id;

82 rows affected.

     id      username                      email                date_joined
0     1  bnbnabnsbona    bnbnabnsb.ona@yandex.ru 2021-04-21 04:11:56.000000
1     3      ebxnsomo                nsomo@bk.ru 2021-04-10 10:14:22.000000
2     8      foebeb13   jbnbnasxcbcbom@yandex.ru 2021-03-28 08:50:53.000000
3    10   xsnascsxsna      xsnascsxsna@yandex.ru 2021-04-05 15:50:36.000000
4    16   snnbojbxsfb      snnbojbxsfb@yandex.ru 2021-04-01 02:35:41.000000
..  ...           ...                        ...                        ...
77  390   bbbdsamsnbm      bbbdsamsnbm@yandex.ru 2021-12-24 13:18:30.999106
78  391        fsonbm         s.fsonbm@yandex.ru 2021-12-24 13:47:54.352123
79  395      Fdbnnkob        nf.nasdoo@yandex.ru 2021-12-24 16:28:20.146407
80  408          Rseb  kbnaoxixb280398@yandex.ru 2021-12-29 10:26:28.492988
81  411        oabxeo         smo.oabx@yandex.ru 2021-12-30 07:24:19.703396

[82 rows x 4 columns]


---

## 8. Дополнительные приемы

Этот короткий, но полезный урок посвящён типичной ошибке - **целочисленному делению**. Вы поймёте, как она влияет на результаты и как её избежать. Это не только спасёт ваши запросы от неверных результатов, но и прокачает внимание к деталям.

Допустим мы хотим разделить `score / 10`.

In [12]:
%%sql
SELECT
    score,
    score / 10
FROM users
WHERE score::text NOT LIKE '%0';
-- score::text превращает число в строку для LIKE (т.к. функции TEXT() нет)

409 rows affected.

     score  ?column?
0        5         0
1        5         0
2       15         1
3        5         0
4       95         9
..     ...       ...
404      5         0
405    215        21
406     15         1
407    415        41
408     25         2

[409 rows x 2 columns]

:::{caution} Eсли делим целое число (integer) на целое число
база PostgreSQL выполняет **целочисленное деление** `score % 10`
:::

In [52]:
%%sql
SELECT
    score,
    score / 10           AS integer_division,
    -- целочисленное деление (45 / 10 = 4)
    score / 10.0         AS divide_by_float,
    -- эталон: деление на литерал с точкой (4.5)
    score * 1.0 / 10     AS multiply_first
    -- повышение через умножение на 1.0
FROM users
WHERE score::text NOT LIKE '%0';

409 rows affected.

     score  integer_division         divide_by_float          multiply_first
0        5                 0  0.50000000000000000000  0.50000000000000000000
1        5                 0  0.50000000000000000000  0.50000000000000000000
2       15                 1      1.5000000000000000      1.5000000000000000
3        5                 0  0.50000000000000000000  0.50000000000000000000
4       95                 9      9.5000000000000000      9.5000000000000000
..     ...               ...                     ...                     ...
404      5                 0  0.50000000000000000000  0.50000000000000000000
405    215                21     21.5000000000000000     21.5000000000000000
406     15                 1      1.5000000000000000      1.5000000000000000
407    415                41     41.5000000000000000     41.5000000000000000
408     25                 2      2.5000000000000000      2.5000000000000000

[409 rows x 4 columns]

### Cast оператор `::`

:::{note} Оператор `::` (двойное двоеточие)
:class: simple dropdown
:open: true

Фирменный оператор PostgreSQL для явного приведения одного типа данных к другому.
Является более короткой альтернативой конструкции `CAST(выражение AS тип)`.

:::{div}
:class: text-sm
**Примеры использования:**
- `score::numeric` – превращает целое число в число с плавающей точкой (для точного деления без потери остатка: `45::numeric / 10 = 4.5`).
- `'2026-08-25'::date` – превращает текстовую строку в дату (тип `date`), позволяя безопасно складывать её с `INTERVAL` или числами дней.
- `date_joined::date` – отсекает время от временной метки (`timestamp`), оставляя только календарный день.
- `score::text` – превращает число в текстовую строку (чтобы использовать строковые операторы вроде `LIKE` или конкатенацию).
- `'120'::integer` (или `::int`) – превращает строку с цифрами в целое число для математических вычислений.
- `'true'::boolean` (или `'1'::bool`) – превращает текст или цифру в логический тип (`TRUE`/`FALSE`).
:::
::::

In [53]:
%%sql
SELECT
    score,
    score / 10           AS integer_division,
    score / 10.0         AS divide_by_float,
    score * 1.0 / 10     AS multiply_first,
    score::numeric / 10  AS explicit_cast,
    -- явное приведение типа (numeric)
    CAST(score AS numeric) / 10 AS ansi_cast_divide
    -- универсальный стандарт ANSI SQL для приведения типов
FROM users
WHERE score::text NOT LIKE '%0';

409 rows affected.

,score,integer_division,divide_by_float,multiply_first,explicit_cast,ansi_cast_divide
0,5,0,0.50000000000000000000,0.50000000000000000000,0.50000000000000000000,0.50000000000000000000
1,5,0,0.50000000000000000000,0.50000000000000000000,0.50000000000000000000,0.50000000000000000000
2,15,1,1.5000000000000000,1.5000000000000000,1.5000000000000000,1.5000000000000000
3,5,0,0.50000000000000000000,0.50000000000000000000,0.50000000000000000000,0.50000000000000000000
4,95,9,9.5000000000000000,9.5000000000000000,9.5000000000000000,9.5000000000000000
...,...,...,...,...,...,...
404,5,0,0.50000000000000000000,0.50000000000000000000,0.50000000000000000000,0.50000000000000000000
405,215,21,21.5000000000000000,21.5000000000000000,21.5000000000000000,21.5000000000000000
406,15,1,1.5000000000000000,1.5000000000000000,1.5000000000000000,1.5000000000000000
407,415,41,41.5000000000000000,41.5000000000000000,41.5000000000000000,41.5000000000000000
408,25,2,2.5000000000000000,2.5000000000000000,2.5000000000000000,2.5000000000000000

### CAST ( )

::::{note} Функция / конструкция `CAST()`
:class: simple dropdown
:open: true
Используется для явного приведения значения из одного типа данных в другой.
```sql
CAST(выражение AS целевой_тип_данных)
```

:::{div}
:class: text-sm
Основные типы для приведения:
- AS `DATE` – превращает строку или временную метку в чистую дату без времени: \
  `CAST('2026-08-25' AS DATE)` ➔ `2026-08-25`
- AS `TIMESTAMP` – превращает строку в дату со временем: \
  `CAST('2026-08-25 14:30:00' AS TIMESTAMP)` ➔ `2026-08-25 14:30:00`
- AS `TIME` – превращает строку или временную метку во время суток (отсекает дату): \
  `CAST('2026-08-25 14:30:00' AS TIME)` ➔ `14:30:00`
- AS `NUMERIC` (или AS `DECIMAL`) – превращает целое число или строку в точное вещественное число: \
  `CAST(score AS NUMERIC) / 10` ➔ `4.5`
- AS `INTEGER` (или AS `INT`) – превращает вещественное число (округляя его) или текст в целое число: \
  `CAST('42' AS INTEGER)` ➔ `42`
- AS `TEXT` (или AS `VARCHAR`) – превращает любое значение (дату, число) в строку текста.

---
Помнить разницу:
- `TIMESTAMP` = дата + время (`2026-08-25 14:30:00`)
- `DATE` = только календарь (`2026-08-25`)
- `TIME` = только часы на стене (`14:30:00`)
- `INTERVAL` = отрезок длительности (`3 days 4 hours`)
:::
::::

:::{note} У типа `NUMERIC` можно в скобках явно указать желаемую точность:
:class: simple
```sql
NUMERIC(всего_цифр, цифр_после_запятой):
```
```sql
CAST(score / 10.0 AS numeric(10, 2)) AS direct_cast_round

/* Обрежь и упакуй это длинное число в формат:
   всего максимум 10 цифр,
   из которых ровно 2 цифры после запятой */
```
База данных сама приведёт результат к числу с 2 знаками после запятой при касте.
:::

---

In [57]:
%%sql
SELECT
    score,
    score / 10        AS integer_division,
    CAST(score / 10.0 AS numeric(10, 2)) AS direct_cast_round
      -- СНАЧАЛА деление, а приведение к numeric(10, 2) ПОТОМ
FROM users
WHERE score::text NOT LIKE '%0';

409 rows affected.

     score  integer_division direct_cast_round
0        5                 0              0.50
1        5                 0              0.50
2       15                 1              1.50
3        5                 0              0.50
4       95                 9              9.50
..     ...               ...               ...
404      5                 0              0.50
405    215                21             21.50
406     15                 1              1.50
407    415                41             41.50
408     25                 2              2.50

[409 rows x 3 columns]

Но самый понятный, универсальный и читаемый – это вариант с ROUND:
```sql
ROUND(CAST(score AS numeric) / 10, 2)
```

### ROUND( )

:::{note} Функция `ROUND()`
:class: simple dropdown

Используется для математического округления числовых значений (по правилам арифметики: от 5 – в большую сторону).

**Синтаксис:**
```sql
ROUND(число)             -- округление до ближайшего целого
ROUND(число::numeric, s) -- округление до `s` знаков после запятой
```
Примеры:
- `ROUND(4.2)` ➔ `4`
- `ROUND(4.8)` ➔ `5`
- `ROUND(12.3456::numeric, 2)` ➔ 12.35
- `ROUND(score / 10.0, 2)` ➔ округляет результат деления до сотых.

⚠️ Важно для PostgreSQL: Если передаётся второй аргумент (количество знаков после запятой), первый аргумент **обязан иметь тип `numeric`** (или быть явно приведён к нему через `::numeric` или литерал с точкой, например `10.0`).
:::

In [46]:
%%sql
SELECT
    score,
    score / 10                            AS integer_division,
    ROUND(score / 10.0, 2)                AS divide_by_float,
    ROUND(score * 1.0 / 10, 2)            AS multiply_first,
    ROUND(score::numeric / 10, 2)         AS explicit_cast,
    ROUND(CAST(score AS numeric) / 10, 2) AS ansi_cast_divide
FROM users
WHERE score::text NOT LIKE '%0';

409 rows affected.

,score,integer_division,divide_by_float,multiply_first,explicit_cast,ansi_cast_divide
0,5,0,0.50,0.50,0.50,0.50
1,5,0,0.50,0.50,0.50,0.50
2,15,1,1.50,1.50,1.50,1.50
3,5,0,0.50,0.50,0.50,0.50
4,95,9,9.50,9.50,9.50,9.50
...,...,...,...,...,...,...
404,5,0,0.50,0.50,0.50,0.50
405,215,21,21.50,21.50,21.50,21.50
406,15,1,1.50,1.50,1.50,1.50
407,415,41,41.50,41.50,41.50,41.50
408,25,2,2.50,2.50,2.50,2.50

### DISTINCT

:::{note} Ключевое слово `DISTINCT`
:class: simple dropdown
:open: false
Оператор для устранения дубликатов. Оставляет только уникальные строки в результирующей выборке.
Указывается сразу после ключевого слова `SELECT`.

**Синтаксис:**
```sql
SELECT DISTINCT колонка1, колонка2 FROM таблица;
```
Как это работает:

- По **одной колонке**: возвращает список уникальных значений этого поля.
```sql
-- Вернёт список уникальных доменов или стран без повторов:
SELECT DISTINCT tier FROM users;
```
- По **нескольким колонкам**: уникальность определяется по комбинации всех указанных колонок (дубликатом считается строка, где совпадают все поля сразу).
```sql
-- Вернёт уникальные пары `имя + фамилия`:
SELECT DISTINCT first_name, last_name FROM users;
```
💡 Заметка: DISTINCT требует от базы данных сортировки или хеширования всех строк для поиска повторов, поэтому на огромных таблицах он может работать медленнее обычного SELECT.
:::

In [48]:
%%sql
SELECT
    DISTINCT RIGHT(email, LENGTH(email) - POSITION('@' IN email)) AS unic
FROM users
ORDER BY unic;

182 rows affected.

            unic
0         123.ru
1        6664.ru
2    abb-bank.az
3     afarek.com
4     agamova.ru
..           ...
177        ya.ru
178   yks247.com
179     yndex.ru
180    zneep.com
181    zwoho.com

[182 rows x 1 columns]


---

## 9. Соединение таблиц - JOIN

В этом уроке вы научитесь одному из ключевых навыков в SQL - объединению данные из нескольких таблиц. Вы разберётесь в различных типах соединений, научитесь задавать условия и учитывать такие нюансы, как пропущенные строки или дубликаты.

Вы изучите:

- Виды соединений: `INNER JOIN`, `LEFT JOIN`, `RIGHT JOIN`, `FULL JOIN`
- Условия соединения `ON` с несколькими полями
- Обработка пропусков и дубликатов

[Таблица к уроку](https://docs.google.com/spreadsheets/d/1ceoMPB0zd5fVi26L2Jg8zY3nHPz37BflxcuNRWpPhbo/edit?gid=0#gid=0)

In [2]:
%%sql
SELECT *
FROM coderun c

55722 rows affected.

          id                 created_at  problem_id  user_id  language_id
0          1 2021-04-07 06:06:20.000000          13       10            3
1          2 2021-03-31 07:10:06.000000          15       13            3
2          3 2021-04-04 14:55:26.000000           1        6            3
3          4 2021-03-29 21:24:51.000000          26        4            3
4          5 2021-03-30 11:29:12.000000          21       18            3
...      ...                        ...         ...      ...          ...
55717  55718 2022-05-17 09:00:51.743027         101      171            2
55718  55719 2022-05-17 09:01:04.210208         101      171            2
55719  55720 2022-05-17 09:02:06.203189         101      171            2
55720  55721 2022-05-17 09:03:45.265515         102      171            2
55721  55722 2022-05-17 09:03:57.645401         102      171            2

[55722 rows x 5 columns]

INNER JOIN (JOIN) - берем все строки из первой таблицы, все строки из второй. Оставляем только те строки, по которым нашли соответствие.

LEFT JOIN - из 1-й (левой) таблицы выводим все строки вне зависимости встречаются они в правой таблице или нет. Если встречаются, выводим все значения которые нашли в правой таблице, если не встречаются выводим NULL

FULL JOIN - комбинация левого и правого соединения.

### INNER JOIN

In [3]:
%%sql
SELECT *
FROM coderun c
JOIN users u
ON c.user_id = u.id;

55722 rows affected.

,id,created_at,problem_id,user_id,language_id,id,username,first_name,last_name,is_active,date_joined,email,referal_user,company_id,tier,score
0,1,2021-04-07 06:06:20.000000,13,10,3,10,xsnascsxsna,Ульяна,Булатов,1,2021-04-05 15:50:36.000000,xsnascsxsna@yandex.ru,NaN,NaN,1,0
1,2,2021-03-31 07:10:06.000000,15,13,3,13,Kbxdbobn,Даниэль,Столяров,1,2021-03-29 18:16:06.000000,fscbmsanosfon@gmail.com,NaN,NaN,1,0
2,3,2021-04-04 14:55:26.000000,1,6,3,6,Pbmod1983,Романова,Леонтьева,1,2021-04-19 20:31:17.000000,i.abxbfnsenss@icloud.com,NaN,NaN,1,5
3,4,2021-03-29 21:24:51.000000,26,4,3,4,LsooSioesbdK,София,Ермаков,1,2021-04-06 12:50:57.000000,1583253@gmail.com,NaN,NaN,1,0
4,5,2021-03-30 11:29:12.000000,21,18,3,18,aixbcssn,Карина,Соловьев,1,2021-03-28 17:08:26.000000,jbfksn@list.ru,NaN,NaN,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55717,55718,2022-05-17 09:00:51.743027,101,171,2,171,UxbabnBsxs,Ника,Полякова,1,2021-11-23 09:00:55.919204,jofbx-009@mail.ru,NaN,NaN,1,5
55718,55719,2022-05-17 09:01:04.210208,101,171,2,171,UxbabnBsxs,Ника,Полякова,1,2021-11-23 09:00:55.919204,jofbx-009@mail.ru,NaN,NaN,1,5
55719,55720,2022-05-17 09:02:06.203189,101,171,2,171,UxbabnBsxs,Ника,Полякова,1,2021-11-23 09:00:55.919204,jofbx-009@mail.ru,NaN,NaN,1,5
55720,55721,2022-05-17 09:03:45.265515,102,171,2,171,UxbabnBsxs,Ника,Полякова,1,2021-11-23 09:00:55.919204,jofbx-009@mail.ru,NaN,NaN,1,5
55721,55722,2022-05-17 09:03:57.645401,102,171,2,171,UxbabnBsxs,Ника,Полякова,1,2021-11-23 09:00:55.919204,jofbx-009@mail.ru,NaN,NaN,1,5

In [7]:
%%sql
SELECT c.*, u.username
FROM coderun c
JOIN users u
ON c.user_id = u.id;

55722 rows affected.

,id,created_at,problem_id,user_id,language_id,username
0,1,2021-04-07 06:06:20.000000,13,10,3,xsnascsxsna
1,2,2021-03-31 07:10:06.000000,15,13,3,Kbxdbobn
2,3,2021-04-04 14:55:26.000000,1,6,3,Pbmod1983
3,4,2021-03-29 21:24:51.000000,26,4,3,LsooSioesbdK
4,5,2021-03-30 11:29:12.000000,21,18,3,aixbcssn
...,...,...,...,...,...,...
55717,55718,2022-05-17 09:00:51.743027,101,171,2,UxbabnBsxs
55718,55719,2022-05-17 09:01:04.210208,101,171,2,UxbabnBsxs
55719,55720,2022-05-17 09:02:06.203189,101,171,2,UxbabnBsxs
55720,55721,2022-05-17 09:03:45.265515,102,171,2,UxbabnBsxs
55721,55722,2022-05-17 09:03:57.645401,102,171,2,UxbabnBsxs

### RIGHT JOIN

In [5]:
%%sql
SELECT *
FROM coderun c
RIGHT JOIN users u
ON c.user_id = u.id;

57628 rows affected.

,id,created_at,problem_id,user_id,language_id,id,username,first_name,last_name,is_active,date_joined,email,referal_user,company_id,tier,score
0,1.0,2021-04-07 06:06:20,13.0,10.0,3.0,10,xsnascsxsna,Ульяна,Булатов,1,2021-04-05 15:50:36.000000,xsnascsxsna@yandex.ru,NaN,NaN,1,0
1,2.0,2021-03-31 07:10:06,15.0,13.0,3.0,13,Kbxdbobn,Даниэль,Столяров,1,2021-03-29 18:16:06.000000,fscbmsanosfon@gmail.com,NaN,NaN,1,0
2,3.0,2021-04-04 14:55:26,1.0,6.0,3.0,6,Pbmod1983,Романова,Леонтьева,1,2021-04-19 20:31:17.000000,i.abxbfnsenss@icloud.com,NaN,NaN,1,5
3,4.0,2021-03-29 21:24:51,26.0,4.0,3.0,4,LsooSioesbdK,София,Ермаков,1,2021-04-06 12:50:57.000000,1583253@gmail.com,NaN,NaN,1,0
4,5.0,2021-03-30 11:29:12,21.0,18.0,3.0,18,aixbcssn,Карина,Соловьев,1,2021-03-28 17:08:26.000000,jbfksn@list.ru,NaN,NaN,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57623,NaN,NaT,NaN,NaN,NaN,612,Axaok1606,Даниил,Беликов,1,2022-01-19 09:02:43.204390,bxaok131606@yandex.ru,NaN,NaN,1,0
57624,NaN,NaT,NaN,NaN,NaN,2283,dofsn99900,Мария,Баранова,1,2022-03-15 14:11:27.829071,dofsn99900@icloud.com,NaN,NaN,1,0
57625,NaN,NaT,NaN,NaN,NaN,2795,bfbnf,NaN,NaN,0,2022-04-18 18:54:11.041882,nbko@mail.ru,NaN,NaN,0,0
57626,NaN,NaT,NaN,NaN,NaN,2502,Hodab13,Алиса,Тимофеева,1,2022-03-27 15:57:07.022743,bdab@helga.perm.ru,NaN,NaN,1,0
57627,NaN,NaT,NaN,NaN,NaN,2209,InjsnsasDskbn,Платон,Баранова,1,2022-03-07 14:26:35.806705,fskb31120251@gmail.com,NaN,NaN,1,0

In [6]:
%%sql
SELECT *
FROM coderun c
RIGHT JOIN users u
ON c.user_id = u.id
WHERE c.id IS NULL;

1906 rows affected.

,id,created_at,problem_id,user_id,language_id,id,username,first_name,last_name,is_active,date_joined,email,referal_user,company_id,tier,score
0,None,None,None,None,None,2026,Pbdsnbk,Михаил,Фомин,0,2022-02-27 08:23:56.629815,ibdsnmsn@mail.ru,NaN,NaN,0,0
1,None,None,None,None,None,2024,annfbibf,Даниил,Киселев,1,2022-02-27 06:09:28.534612,ann-fbibf@mail.ru,NaN,NaN,1,0
2,None,None,None,None,None,264,jboodbasnoff,Николай,Гончарова,1,2021-11-28 19:38:11.183140,dbeon64955@xasems.com,NaN,NaN,1,0
3,None,None,None,None,None,1350,Knons22,NaN,NaN,1,2022-02-11 12:14:14.650042,odbfs221@gmail.com,NaN,NaN,1,0
4,None,None,None,None,None,1070,nboo92,NaN,NaN,1,2022-02-02 15:02:13.631397,nboon_1_9_9_2@mail.ru,NaN,NaN,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1901,None,None,None,None,None,612,Axaok1606,Даниил,Беликов,1,2022-01-19 09:02:43.204390,bxaok131606@yandex.ru,NaN,NaN,1,0
1902,None,None,None,None,None,2283,dofsn99900,Мария,Баранова,1,2022-03-15 14:11:27.829071,dofsn99900@icloud.com,NaN,NaN,1,0
1903,None,None,None,None,None,2795,bfbnf,NaN,NaN,0,2022-04-18 18:54:11.041882,nbko@mail.ru,NaN,NaN,0,0
1904,None,None,None,None,None,2502,Hodab13,Алиса,Тимофеева,1,2022-03-27 15:57:07.022743,bdab@helga.perm.ru,NaN,NaN,1,0
1905,None,None,None,None,None,2209,InjsnsasDskbn,Платон,Баранова,1,2022-03-07 14:26:35.806705,fskb31120251@gmail.com,NaN,NaN,1,0

### LEFT JOIN

In [8]:
%%sql
SELECT *
FROM users u
LEFT JOIN coderun c
ON u.id = c.user_id
WHERE c.id IS NULL;

1906 rows affected.

,id,username,first_name,last_name,is_active,date_joined,email,referal_user,company_id,tier,score,id,created_at,problem_id,user_id,language_id
0,2026,Pbdsnbk,Михаил,Фомин,0,2022-02-27 08:23:56.629815,ibdsnmsn@mail.ru,NaN,NaN,0,0,None,None,None,None,None
1,2024,annfbibf,Даниил,Киселев,1,2022-02-27 06:09:28.534612,ann-fbibf@mail.ru,NaN,NaN,1,0,None,None,None,None,None
2,264,jboodbasnoff,Николай,Гончарова,1,2021-11-28 19:38:11.183140,dbeon64955@xasems.com,NaN,NaN,1,0,None,None,None,None,None
3,1350,Knons22,NaN,NaN,1,2022-02-11 12:14:14.650042,odbfs221@gmail.com,NaN,NaN,1,0,None,None,None,None,None
4,1070,nboo92,NaN,NaN,1,2022-02-02 15:02:13.631397,nboon_1_9_9_2@mail.ru,NaN,NaN,1,0,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1901,612,Axaok1606,Даниил,Беликов,1,2022-01-19 09:02:43.204390,bxaok131606@yandex.ru,NaN,NaN,1,0,None,None,None,None,None
1902,2283,dofsn99900,Мария,Баранова,1,2022-03-15 14:11:27.829071,dofsn99900@icloud.com,NaN,NaN,1,0,None,None,None,None,None
1903,2795,bfbnf,NaN,NaN,0,2022-04-18 18:54:11.041882,nbko@mail.ru,NaN,NaN,0,0,None,None,None,None,None
1904,2502,Hodab13,Алиса,Тимофеева,1,2022-03-27 15:57:07.022743,bdab@helga.perm.ru,NaN,NaN,1,0,None,None,None,None,None
1905,2209,InjsnsasDskbn,Платон,Баранова,1,2022-03-07 14:26:35.806705,fskb31120251@gmail.com,NaN,NaN,1,0,None,None,None,None,None


---

In [9]:
%%sql
SELECT *
FROM coderun c
JOIN users u
ON c.user_id = u.id
JOIN problem p
ON p.id = c.problem_id;

55722 rows affected.

,id,created_at,problem_id,user_id,language_id,id,username,first_name,last_name,is_active,...,solution,cost,rating,page_id,solution_cost,priority,company_id,is_visible,is_private,recommendation
0,1,2021-04-07 06:06:20.000000,13,10,3,10,xsnascsxsna,Ульяна,Булатов,1,...,<inject-highlight>class Answer:\r\n def bui...,20,94.0,58,0,1.0,None,True,False,NaN
1,2,2021-03-31 07:10:06.000000,15,13,3,13,Kbxdbobn,Даниэль,Столяров,1,...,<inject-highlight>class Answer:\r\n def dai...,30,92.0,60,0,1.0,None,True,False,NaN
2,3,2021-04-04 14:55:26.000000,1,6,3,6,Pbmod1983,Романова,Леонтьева,1,...,<inject-highlight>class Answer:\r\n def two...,20,91.0,36,0,890.0,None,True,False,NaN
3,4,2021-03-29 21:24:51.000000,26,4,3,4,LsooSioesbdK,София,Ермаков,1,...,<inject-highlight>class Answer:\r\n def get...,30,91.0,71,0,1.0,None,True,False,NaN
4,5,2021-03-30 11:29:12.000000,21,18,3,18,aixbcssn,Карина,Соловьев,1,...,<inject-highlight>class Answer:\r\n def get...,20,95.0,66,0,1.0,None,True,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55717,55718,2022-05-17 09:00:51.743027,101,171,2,171,UxbabnBsxs,Ника,Полякова,1,...,<inject-highlight>SELECT DISTINCT t.Num AS Con...,30,87.0,147,0,890.0,None,True,False,NaN
55718,55719,2022-05-17 09:01:04.210208,101,171,2,171,UxbabnBsxs,Ника,Полякова,1,...,<inject-highlight>SELECT DISTINCT t.Num AS Con...,30,87.0,147,0,890.0,None,True,False,NaN
55719,55720,2022-05-17 09:02:06.203189,101,171,2,171,UxbabnBsxs,Ника,Полякова,1,...,<inject-highlight>SELECT DISTINCT t.Num AS Con...,30,87.0,147,0,890.0,None,True,False,NaN
55720,55721,2022-05-17 09:03:45.265515,102,171,2,171,UxbabnBsxs,Ника,Полякова,1,...,<inject-highlight>SELECT t.Salary\r\nFROM (\r...,30,97.0,148,0,890.0,None,True,False,NaN
55721,55722,2022-05-17 09:03:57.645401,102,171,2,171,UxbabnBsxs,Ника,Полякова,1,...,<inject-highlight>SELECT t.Salary\r\nFROM (\r...,30,97.0,148,0,890.0,None,True,False,NaN

In [11]:
%%sql
-- Очень аккуратно с JOIN'ами
SELECT *
FROM coderun c
RIGHT JOIN users u
ON c.user_id = u.id
JOIN problem p
ON p.id = c.problem_id
WHERE c.problem_id IS NULL;

Empty DataFrame
Columns: [id, created_at, problem_id, user_id, language_id, id, username, first_name, last_name, is_active, date_joined, email, referal_user, company_id, tier, score, id, name, complexity, bonus, task, solution, cost, rating, page_id, solution_cost, priority, company_id, is_visible, is_private, recommendation]
Index: []

[0 rows x 31 columns]

Неправильная последовательность JOIN'ов и Неправильный выбор типа соединения приводит к огромному количеству ошибок в сложных запросах.

::::{caution} Если используете несколько join'ов в одном запросе
И хотя бы один из этих join'ов левый или правый и потом к этой же табличке джойните еще что-то, то очень аккуратно используйте и проверяйте правильный ли тип соединения вы используете. 

---
:::{div}
:class: text-sm
Лучше даже прямо выбирать строку, которая потенциально могла потеряться и на ней проверять ничего ли вы не забыли `WHERE c.problem_id IS NULL`.
:::
::::

In [12]:
%%sql
-- Правильно
SELECT *
FROM coderun c
RIGHT JOIN users u
ON c.user_id = u.id
LEFT JOIN problem p
ON p.id = c.problem_id
WHERE c.problem_id IS NULL;

1906 rows affected.

,id,created_at,problem_id,user_id,language_id,id,username,first_name,last_name,is_active,...,solution,cost,rating,page_id,solution_cost,priority,company_id,is_visible,is_private,recommendation
0,None,None,None,None,None,2026,Pbdsnbk,Михаил,Фомин,0,...,None,None,None,None,None,None,None,None,None,None
1,None,None,None,None,None,2024,annfbibf,Даниил,Киселев,1,...,None,None,None,None,None,None,None,None,None,None
2,None,None,None,None,None,264,jboodbasnoff,Николай,Гончарова,1,...,None,None,None,None,None,None,None,None,None,None
3,None,None,None,None,None,1350,Knons22,NaN,NaN,1,...,None,None,None,None,None,None,None,None,None,None
4,None,None,None,None,None,1070,nboo92,NaN,NaN,1,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1901,None,None,None,None,None,612,Axaok1606,Даниил,Беликов,1,...,None,None,None,None,None,None,None,None,None,None
1902,None,None,None,None,None,2283,dofsn99900,Мария,Баранова,1,...,None,None,None,None,None,None,None,None,None,None
1903,None,None,None,None,None,2795,bfbnf,NaN,NaN,0,...,None,None,None,None,None,None,None,None,None,None
1904,None,None,None,None,None,2502,Hodab13,Алиса,Тимофеева,1,...,None,None,None,None,None,None,None,None,None,None
1905,None,None,None,None,None,2209,InjsnsasDskbn,Платон,Баранова,1,...,None,None,None,None,None,None,None,None,None,None


---

In [13]:
%%sql
SELECT u.company_id
FROM users u;

2774 rows affected.

      company_id
0            NaN
1            NaN
2            NaN
3            1.0
4            NaN
...          ...
2769         NaN
2770         4.0
2771         NaN
2772         4.0
2773         NaN

[2774 rows x 1 columns]

In [14]:
%%sql
SELECT *
FROM company c;

10 rows affected.

   id       name description  logo db_cred  site  welcome_bonus
0   1   Клиент 1    Клиент 1  None      sf  None            NaN
1   2   Клиент 2    Клиент 2  None     NaN  None          500.0
2   3   Клиент 3    Клиент 3  None      sf  None            NaN
3   4   Клиент 4    Клиент 4  None     NaN  None          750.0
4   5   Клиент 5    Клиент 5  None     NaN  None          750.0
5   6   Клиент 6    Клиент 6  None     NaN  None          750.0
6   7   Клиент 7    Клиент 7  None      sf  None            NaN
7   8   Клиент 8    Клиент 8  None      sf  None            NaN
8   9   Клиент 9    Клиент 9  None      sf  None            NaN
9  10  Клиент 10   Клиент 10  None      sf  None         5000.0

In [16]:
%%sql
SELECT *
FROM coderun c
RIGHT JOIN users u
ON c.user_id = u.id
JOIN company c2
ON COALESCE(u.company_id, 1) = c2.id;

57628 rows affected.

,id,created_at,problem_id,user_id,language_id,id,username,first_name,last_name,is_active,...,company_id,tier,score,id,name,description,logo,db_cred,site,welcome_bonus
0,1.0,2021-04-07 06:06:20,13.0,10.0,3.0,10,xsnascsxsna,Ульяна,Булатов,1,...,NaN,1,0,1,Клиент 1,Клиент 1,None,sf,None,NaN
1,2.0,2021-03-31 07:10:06,15.0,13.0,3.0,13,Kbxdbobn,Даниэль,Столяров,1,...,NaN,1,0,1,Клиент 1,Клиент 1,None,sf,None,NaN
2,3.0,2021-04-04 14:55:26,1.0,6.0,3.0,6,Pbmod1983,Романова,Леонтьева,1,...,NaN,1,5,1,Клиент 1,Клиент 1,None,sf,None,NaN
3,4.0,2021-03-29 21:24:51,26.0,4.0,3.0,4,LsooSioesbdK,София,Ермаков,1,...,NaN,1,0,1,Клиент 1,Клиент 1,None,sf,None,NaN
4,5.0,2021-03-30 11:29:12,21.0,18.0,3.0,18,aixbcssn,Карина,Соловьев,1,...,NaN,1,0,1,Клиент 1,Клиент 1,None,sf,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57623,NaN,NaT,NaN,NaN,NaN,612,Axaok1606,Даниил,Беликов,1,...,NaN,1,0,1,Клиент 1,Клиент 1,None,sf,None,NaN
57624,NaN,NaT,NaN,NaN,NaN,2283,dofsn99900,Мария,Баранова,1,...,NaN,1,0,1,Клиент 1,Клиент 1,None,sf,None,NaN
57625,NaN,NaT,NaN,NaN,NaN,2795,bfbnf,NaN,NaN,0,...,NaN,0,0,1,Клиент 1,Клиент 1,None,sf,None,NaN
57626,NaN,NaT,NaN,NaN,NaN,2502,Hodab13,Алиса,Тимофеева,1,...,NaN,1,0,1,Клиент 1,Клиент 1,None,sf,None,NaN
57627,NaN,NaT,NaN,NaN,NaN,2209,InjsnsasDskbn,Платон,Баранова,1,...,NaN,1,0,1,Клиент 1,Клиент 1,None,sf,None,NaN

In [17]:
%%sql
SELECT COUNT(*)
FROM coderun c
RIGHT JOIN users u
ON c.user_id = u.id
JOIN problem p
ON p.id = c.problem_id;

1 rows affected.

   count
0  55722

In [18]:
%%sql
SELECT COUNT(*)
FROM coderun c
RIGHT JOIN users u
ON c.user_id = u.id
LEFT JOIN problem p
ON p.id = c.problem_id;

1 rows affected.

   count
0  57628

In [19]:
%%sql
SELECT count(*)
FROM coderun c
RIGHT JOIN users u
ON c.user_id = u.id
JOIN company c2
ON COALESCE(u.company_id, 1) = c2.id;

1 rows affected.

   count
0  57628

In [20]:
%%sql
SELECT count(*)
FROM coderun c
RIGHT JOIN users u
ON c.user_id = u.id
LEFT JOIN company c2
ON COALESCE(u.company_id, 1) = c2.id;

1 rows affected.

   count
0  57628

In [22]:
%%sql
SELECT *
FROM coderun c
JOIN users u
ON c.user_id = u.id AND created_at <= date_joined;

12 rows affected.

,id,created_at,problem_id,user_id,language_id,id,username,first_name,last_name,is_active,date_joined,email,referal_user,company_id,tier,score
0,3,2021-04-04 14:55:26,1,6,3,6,Pbmod1983,Романова,Леонтьева,1,2021-04-19 20:31:17,i.abxbfnsenss@icloud.com,None,None,1,5
1,4,2021-03-29 21:24:51,26,4,3,4,LsooSioesbdK,София,Ермаков,1,2021-04-06 12:50:57,1583253@gmail.com,None,None,1,0
2,8,2021-03-29 03:46:24,6,9,3,9,fonnosna,NaN,NaN,1,2021-03-30 19:40:30,asfbdsnnbm.fons@mail.ru,None,None,1,0
3,9,2021-04-06 12:14:59,24,1,3,1,bnbnabnsbona,Таисия,Ермаков,1,2021-04-21 04:11:56,bnbnabnsb.ona@yandex.ru,None,None,1,5
4,10,2021-04-15 11:07:15,20,17,3,17,omaono500,Варвара,Тимофеева,1,2021-04-18 16:21:08,bsasnasecbs500@gmail.com,None,None,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,14,2021-03-31 14:10:57,14,3,3,3,ebxnsomo,Никита,Петров,1,2021-04-10 10:14:22,nsomo@bk.ru,None,None,1,95
8,21,2021-04-08 08:45:08,7,5,3,5,Dskbnnsb,Филипп,Тарасов,1,2021-04-21 10:52:34,9158415237fc@gmail.com,None,None,1,10
9,23,2021-04-18 01:44:20,6,1,3,1,bnbnabnsbona,Таисия,Ермаков,1,2021-04-21 04:11:56,bnbnabnsb.ona@yandex.ru,None,None,1,5
10,24,2021-03-27 17:55:11,13,20,3,20,Ysxb,Серафим,Власова,1,2021-04-19 07:46:43,ssx.bnsibd2011@yandex.ru,None,None,1,5
11,28,2021-03-28 02:18:47,27,19,3,19,Fofbx196,Эмилия,Фролова,1,2021-04-22 15:37:33,koonbnanojj.jofbx@yandex.ru,None,None,1,0

In [23]:
%%sql
-- Эквивалентно предыдущему
SELECT *
FROM coderun c
JOIN users u
ON c.user_id = u.id
WHERE created_at <= date_joined;

12 rows affected.

,id,created_at,problem_id,user_id,language_id,id,username,first_name,last_name,is_active,date_joined,email,referal_user,company_id,tier,score
0,3,2021-04-04 14:55:26,1,6,3,6,Pbmod1983,Романова,Леонтьева,1,2021-04-19 20:31:17,i.abxbfnsenss@icloud.com,None,None,1,5
1,4,2021-03-29 21:24:51,26,4,3,4,LsooSioesbdK,София,Ермаков,1,2021-04-06 12:50:57,1583253@gmail.com,None,None,1,0
2,8,2021-03-29 03:46:24,6,9,3,9,fonnosna,NaN,NaN,1,2021-03-30 19:40:30,asfbdsnnbm.fons@mail.ru,None,None,1,0
3,9,2021-04-06 12:14:59,24,1,3,1,bnbnabnsbona,Таисия,Ермаков,1,2021-04-21 04:11:56,bnbnabnsb.ona@yandex.ru,None,None,1,5
4,10,2021-04-15 11:07:15,20,17,3,17,omaono500,Варвара,Тимофеева,1,2021-04-18 16:21:08,bsasnasecbs500@gmail.com,None,None,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,14,2021-03-31 14:10:57,14,3,3,3,ebxnsomo,Никита,Петров,1,2021-04-10 10:14:22,nsomo@bk.ru,None,None,1,95
8,21,2021-04-08 08:45:08,7,5,3,5,Dskbnnsb,Филипп,Тарасов,1,2021-04-21 10:52:34,9158415237fc@gmail.com,None,None,1,10
9,23,2021-04-18 01:44:20,6,1,3,1,bnbnabnsbona,Таисия,Ермаков,1,2021-04-21 04:11:56,bnbnabnsb.ona@yandex.ru,None,None,1,5
10,24,2021-03-27 17:55:11,13,20,3,20,Ysxb,Серафим,Власова,1,2021-04-19 07:46:43,ssx.bnsibd2011@yandex.ru,None,None,1,5
11,28,2021-03-28 02:18:47,27,19,3,19,Fofbx196,Эмилия,Фролова,1,2021-04-22 15:37:33,koonbnanojj.jofbx@yandex.ru,None,None,1,0

In [24]:
%%sql
-- Заменим на RIGTH JOIN
SELECT *
FROM coderun c
RIGHT JOIN users u
ON c.user_id = u.id AND created_at <= date_joined;

2776 rows affected.

,id,created_at,problem_id,user_id,language_id,id,username,first_name,last_name,is_active,date_joined,email,referal_user,company_id,tier,score
0,3.0,2021-04-04 14:55:26,1.0,6.0,3.0,6,Pbmod1983,Романова,Леонтьева,1,2021-04-19 20:31:17.000000,i.abxbfnsenss@icloud.com,NaN,NaN,1,5
1,4.0,2021-03-29 21:24:51,26.0,4.0,3.0,4,LsooSioesbdK,София,Ермаков,1,2021-04-06 12:50:57.000000,1583253@gmail.com,NaN,NaN,1,0
2,8.0,2021-03-29 03:46:24,6.0,9.0,3.0,9,fonnosna,NaN,NaN,1,2021-03-30 19:40:30.000000,asfbdsnnbm.fons@mail.ru,NaN,NaN,1,0
3,9.0,2021-04-06 12:14:59,24.0,1.0,3.0,1,bnbnabnsbona,Таисия,Ермаков,1,2021-04-21 04:11:56.000000,bnbnabnsb.ona@yandex.ru,NaN,NaN,1,5
4,10.0,2021-04-15 11:07:15,20.0,17.0,3.0,17,omaono500,Варвара,Тимофеева,1,2021-04-18 16:21:08.000000,bsasnasecbs500@gmail.com,NaN,NaN,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2771,NaN,NaT,NaN,NaN,NaN,2283,dofsn99900,Мария,Баранова,1,2022-03-15 14:11:27.829071,dofsn99900@icloud.com,NaN,NaN,1,0
2772,NaN,NaT,NaN,NaN,NaN,2795,bfbnf,NaN,NaN,0,2022-04-18 18:54:11.041882,nbko@mail.ru,NaN,NaN,0,0
2773,NaN,NaT,NaN,NaN,NaN,1709,Mbxabmnm,Аделина,Булатов,1,2022-02-18 07:43:24.145446,kbxab.moxnbmb@mail.ru,NaN,1.0,1,0
2774,NaN,NaT,NaN,NaN,NaN,2502,Hodab13,Алиса,Тимофеева,1,2022-03-27 15:57:07.022743,bdab@helga.perm.ru,NaN,NaN,1,0
2775,NaN,NaT,NaN,NaN,NaN,2209,InjsnsasDskbn,Платон,Баранова,1,2022-03-07 14:26:35.806705,fskb31120251@gmail.com,NaN,NaN,1,0

In [26]:
%%sql
-- Пример использования OR
SELECT *
FROM coderun c
JOIN users u
ON (c.user_id = u.id AND created_at < date_joined)
    OR (c.user_id = u.id AND created_at = date_joined);

12 rows affected.

,id,created_at,problem_id,user_id,language_id,id,username,first_name,last_name,is_active,date_joined,email,referal_user,company_id,tier,score
0,3,2021-04-04 14:55:26,1,6,3,6,Pbmod1983,Романова,Леонтьева,1,2021-04-19 20:31:17,i.abxbfnsenss@icloud.com,None,None,1,5
1,4,2021-03-29 21:24:51,26,4,3,4,LsooSioesbdK,София,Ермаков,1,2021-04-06 12:50:57,1583253@gmail.com,None,None,1,0
2,8,2021-03-29 03:46:24,6,9,3,9,fonnosna,NaN,NaN,1,2021-03-30 19:40:30,asfbdsnnbm.fons@mail.ru,None,None,1,0
3,9,2021-04-06 12:14:59,24,1,3,1,bnbnabnsbona,Таисия,Ермаков,1,2021-04-21 04:11:56,bnbnabnsb.ona@yandex.ru,None,None,1,5
4,10,2021-04-15 11:07:15,20,17,3,17,omaono500,Варвара,Тимофеева,1,2021-04-18 16:21:08,bsasnasecbs500@gmail.com,None,None,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,14,2021-03-31 14:10:57,14,3,3,3,ebxnsomo,Никита,Петров,1,2021-04-10 10:14:22,nsomo@bk.ru,None,None,1,95
8,21,2021-04-08 08:45:08,7,5,3,5,Dskbnnsb,Филипп,Тарасов,1,2021-04-21 10:52:34,9158415237fc@gmail.com,None,None,1,10
9,23,2021-04-18 01:44:20,6,1,3,1,bnbnabnsbona,Таисия,Ермаков,1,2021-04-21 04:11:56,bnbnabnsb.ona@yandex.ru,None,None,1,5
10,24,2021-03-27 17:55:11,13,20,3,20,Ysxb,Серафим,Власова,1,2021-04-19 07:46:43,ssx.bnsibd2011@yandex.ru,None,None,1,5
11,28,2021-03-28 02:18:47,27,19,3,19,Fofbx196,Эмилия,Фролова,1,2021-04-22 15:37:33,koonbnanojj.jofbx@yandex.ru,None,None,1,0

In [27]:
%%sql
SELECT *
FROM problem_to_company ptc;

480 rows affected.

      id name  task  cost  company_id  problem_id bonus priority
0      1  NaN  None  None           1         117  None     None
1      2  NaN  None  None           1         118  None     None
2      3  NaN  None  None           1         119  None     None
3      4  NaN  None  None           1         120  None     None
4      5  NaN  None  None           1         121  None     None
..   ...  ...   ...   ...         ...         ...   ...      ...
475  476  NaN  None  None          10         148  None     None
476  477  NaN  None  None          10         149  None     None
477  478  NaN  None  None          10         150  None     None
478  479  NaN  None  None          10         151  None     None
479  480  NaN  None  None          10         152  None     None

[480 rows x 8 columns]

In [28]:
%%sql
SELECT *
FROM users u
JOIN company c
ON u.company_id = c.id
WHERE username = 'nsosabisfsobm';

1 rows affected.

,id,username,first_name,last_name,is_active,date_joined,email,referal_user,company_id,tier,score,id,name,description,logo,db_cred,site,welcome_bonus
0,416,nsosabisfsobm,None,None,1,2022-01-02 12:22:43.014039,isfsobm.nseo@gmail.com,None,1,1,0,1,Клиент 1,Клиент 1,None,sf,None,None

In [29]:
%%sql
SELECT *
FROM problem p
JOIN problem_to_company ptc 
ON p.id = ptc.problem_id AND ptc.company_id = 1
WHERE p.id = 144;

1 rows affected.

,id,name,complexity,bonus,task,solution,cost,rating,page_id,solution_cost,...,is_private,recommendation,id,name,task,cost,company_id,problem_id,bonus,priority
0,144,NEW! SQL. ДЗ 4. Фильтрация агрегированных знач...,2,0,<h2>Дано</h2><p>Дана таблица <code>transaction...,"<inject-highlight>SELECT card_id, MAX(d.value)...",0,90.0,201,0,...,True,None,28,None,None,None,1,144,None,None