---
title: Глава 3. Запросы
subtitle: SQL Lab in JupyterLab
# license: CC-BY-4.0
github: https://github.com/magus1968/learning-sql
subject: Technical Portfolio
# subject: SQL Learning & Tooling
venue: GitHub & GitVerse Pages
abstract: |
  Расширение JupySQL подсвечивает синтаксис SQL в блокнотах Jupyter, но не на созданном в Jupyter Book сайте. Как обойти это недоразумение было показано в Главе 2. Здесь и далее подобным увлекаться не будем.
authors:
  - name: Alex Smirnov
    email: a@smirnovs.pro
    corresponding: true
    affiliations: Data & BI Analyst
      # - Data Analyst
      # - BI Analyst
      # - Business Analyst
      # - Independent Researcher
date: 2026-07-20
abbreviations:
    MyST: Markedly Structured Text
    Jupyter Book: Build static Web-books
    JupySQL: Run & highlight SQL in Jupyter
---

In [1]:
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

# Формируем структуру подключения к БД
connection_url = URL.create(
    drivername="mysql+pymysql",
    host="localhost",
    port=3306,
    database="sakila",
    username="root",
    password="********",
)

engine = create_engine(connection_url)

%load_ext sql

%config SqlMagic.displaylimit = 20
# %config SqlMagic.displaycon = False
# %config SqlMagic.feedback = False

%sql engine

print("SQLAlchemy - подключение создано")
print("JupySQL - успешно подключен через SQLAlchemy Engine!")

SQLAlchemy - подключение создано
JupySQL - успешно подключен через SQLAlchemy Engine!

## Механика запросов

In [30]:
%%sql
SELECT first_name, last_name
FROM customer
WHERE last_name = 'ZIEGLER'

Running query in 'mysql+pymysql://root:***@localhost:3306/sakila'

+------------+-----------+
| first_name | last_name |
+------------+-----------+
+------------+-----------+

In [31]:
%%sql
SELECT *
FROM category;

Running query in 'mysql+pymysql://root:***@localhost:3306/sakila'

16 rows affected.

+-------------+-------------+---------------------+
| category_id |     name    |     last_update     |
+-------------+-------------+---------------------+
|      1      |    Action   | 2006-02-15 04:46:27 |
|      2      |  Animation  | 2006-02-15 04:46:27 |
|      3      |   Children  | 2006-02-15 04:46:27 |
|      4      |   Classics  | 2006-02-15 04:46:27 |
|      5      |    Comedy   | 2006-02-15 04:46:27 |
|      6      | Documentary | 2006-02-15 04:46:27 |
|      7      |    Drama    | 2006-02-15 04:46:27 |
|      8      |    Family   | 2006-02-15 04:46:27 |
|      9      |   Foreign   | 2006-02-15 04:46:27 |
|      10     |    Games    | 2006-02-15 04:46:27 |
|      11     |    Horror   | 2006-02-15 04:46:27 |
|      12     |    Music    | 2006-02-15 04:46:27 |
|      13     |     New     | 2006-02-15 04:46:27 |
|      14     |    Sci-Fi   | 2006-02-15 04:46:27 |
|      15     |    Sports   | 2006-02-15 04:46:27 |
|      16     |    Travel   | 2006-02-15 04:46:27 |
+-------------+-------------+---------------------+

:::{note} Части запроса
:class: dropdown
:icon: false

| Имя      | Назначение                                                                                             |
| -------- | ------------------------------------------------------------------------------------------------------ |
| select   | Определяет, какие столбцы следует включить в результирующий набор запроса                              |
| from     | Определяет таблицы, из которых следует выбирать данные, а также таблицы, которые должны быть соединены |
| where    | Отсеивает ненужные данные                                                                              |
| group by | Используется для группировки строк по общим значениям столбцов                                         |
| having   | Отсеивает ненужные данные                                                                              |
| order by | Сортирует строки окончательного результирующего набора по одному или нескольким столбцам               |

:::

## Предложение *select*

In [32]:
%%sql
SELECT *
FROM language;

Running query in 'mysql+pymysql://root:***@localhost:3306/sakila'

6 rows affected.

+-------------+----------+---------------------+
| language_id |   name   |     last_update     |
+-------------+----------+---------------------+
|      1      | English  | 2006-02-15 05:02:19 |
|      2      | Italian  | 2006-02-15 05:02:19 |
|      3      | Japanese | 2006-02-15 05:02:19 |
|      4      | Mandarin | 2006-02-15 05:02:19 |
|      5      |  French  | 2006-02-15 05:02:19 |
|      6      |  German  | 2006-02-15 05:02:19 |
+-------------+----------+---------------------+

In [33]:
%%sql
SELECT language_id, name, last_update
FROM language;

Running query in 'mysql+pymysql://root:***@localhost:3306/sakila'

6 rows affected.

+-------------+----------+---------------------+
| language_id |   name   |     last_update     |
+-------------+----------+---------------------+
|      1      | English  | 2006-02-15 05:02:19 |
|      2      | Italian  | 2006-02-15 05:02:19 |
|      3      | Japanese | 2006-02-15 05:02:19 |
|      4      | Mandarin | 2006-02-15 05:02:19 |
|      5      |  French  | 2006-02-15 05:02:19 |
|      6      |  German  | 2006-02-15 05:02:19 |
+-------------+----------+---------------------+

In [34]:
%%sql
SELECT name
FROM language;

Running query in 'mysql+pymysql://root:***@localhost:3306/sakila'

6 rows affected.

+----------+
|   name   |
+----------+
| English  |
| Italian  |
| Japanese |
| Mandarin |
|  French  |
|  German  |
+----------+

In [35]:
%%sql
SELECT
  language_id,
  'COMMON' language_usage,
  language_id * 3.1415927 lang_pi_value,
  upper(name) language_name
FROM language;

Running query in 'mysql+pymysql://root:***@localhost:3306/sakila'

6 rows affected.

+-------------+----------------+---------------+---------------+
| language_id | language_usage | lang_pi_value | language_name |
+-------------+----------------+---------------+---------------+
|      1      |     COMMON     |   3.1415927   |    ENGLISH    |
|      2      |     COMMON     |   6.2831854   |    ITALIAN    |
|      3      |     COMMON     |   9.4247781   |    JAPANESE   |
|      4      |     COMMON     |   12.5663708  |    MANDARIN   |
|      5      |     COMMON     |   15.7079635  |     FRENCH    |
|      6      |     COMMON     |   18.8495562  |     GERMAN    |
+-------------+----------------+---------------+---------------+

In [36]:
%%sql
SELECT
  version (),
  user (),
  database ();

Running query in 'mysql+pymysql://root:***@localhost:3306/sakila'

1 rows affected.

+------------+----------------+-------------+
| version () |    user ()     | database () |
+------------+----------------+-------------+
|   8.0.46   | root@localhost |    sakila   |
+------------+----------------+-------------+

### Псевдонимы столбцов

In [37]:
%%sql
SELECT
  language_id,
  'COMMON' AS language_usage,
  language_id * 3.1415927 AS lang_pi_value,
  upper(name) AS language_name
FROM language;

Running query in 'mysql+pymysql://root:***@localhost:3306/sakila'

6 rows affected.

+-------------+----------------+---------------+---------------+
| language_id | language_usage | lang_pi_value | language_name |
+-------------+----------------+---------------+---------------+
|      1      |     COMMON     |   3.1415927   |    ENGLISH    |
|      2      |     COMMON     |   6.2831854   |    ITALIAN    |
|      3      |     COMMON     |   9.4247781   |    JAPANESE   |
|      4      |     COMMON     |   12.5663708  |    MANDARIN   |
|      5      |     COMMON     |   15.7079635  |     FRENCH    |
|      6      |     COMMON     |   18.8495562  |     GERMAN    |
+-------------+----------------+---------------+---------------+

### Удаление дубликатов

::::{tip} Для аккуратного визуального вывода
:class: dropdown
:open: true

Включим автоматическое преобразование внутреннего результата JupySQL в полноценный Pandas DataFrame. Таким образом получим стандартное усечение строк Pandas – чтобы вывод показывал начало и конец через многоточие вместо вывода всех строк.

Да, у нас появится слева дополнительный столбец с индексом. Просто не будем обращать на него внимания, чтобы не заниматься  дополнительными манипуляциями.
:::{div}
:class: text-xs
Перепробовал несколько способов. Этот вариант оказался наиболее оптимальным.
:::
::::

In [38]:
# Включаем автоматическое преобразование
%config SqlMagic.autopandas = True

In [39]:
%%sql
SELECT actor_id
FROM film_actor
ORDER BY actor_id;

Running query in 'mysql+pymysql://root:***@localhost:3306/sakila'

5462 rows affected.

      actor_id
0            1
1            1
2            1
3            1
4            1
...        ...
5457       200
5458       200
5459       200
5460       200
5461       200

[5462 rows x 1 columns]

In [40]:
%%sql
SELECT DISTINCT actor_id
FROM film_actor
ORDER BY actor_id;

Running query in 'mysql+pymysql://root:***@localhost:3306/sakila'

200 rows affected.

     actor_id
0           1
1           2
2           3
3           4
4           5
..        ...
195       196
196       197
197       198
198       199
199       200

[200 rows x 1 columns]

:::{tip} Если хочется убрать столбец с индексом, но при этом оставить стандартное усечение строк Pandas
:class: dropdown
:open: false

Придется выполнить дополнительные манипуляции. Например, для преобразования последнего результата `_` из памяти (последней выполненной ячейки):

```python
df = _.set_axis([''] * len(_), axis=0)

# Или обернуть в функцию
def no_idx(df):
    return df.set_axis([''] * len(df), axis=0)

no_idx(_)
```
Фактически данный способ убирает не индексный столбец, а значения в нем. Но визуально получаем желаемый результат.
:::

In [41]:
df = _.set_axis([''] * len(_), axis=0)
df

    actor_id
           1
           2
           3
           4
           5
..       ...
         196
         197
         198
         199
         200

[200 rows x 1 columns]

In [42]:
# Отключаем автоматическое преобразование
%config SqlMagic.autopandas = False

## Предложение *from*

### Производные таблицы (генерируемые подзапросами)

In [43]:
%%sql
SELECT
  CONCAT (cust.last_name, ', ', cust.first_name) AS full_name
FROM
  (
    SELECT first_name, last_name, email
    FROM customer
    WHERE first_name = 'JESSIE'
  ) AS cust;

Running query in 'mysql+pymysql://root:***@localhost:3306/sakila'

2 rows affected.

+---------------+
|   full_name   |
+---------------+
| BANKS, JESSIE |
| MILAM, JESSIE |
+---------------+

### Вр*е*менные таблицы

In [2]:
%%sql
CREATE TEMPORARY TABLE actors_j (
    actor_id smallint(5),
    first_name varchar(45),
    last_name varchar(45)
);

Running query in 'mysql+pymysql://root:***@localhost:3306/sakila'

++
||
++
++

In [3]:
%%sql
INSERT INTO actors_j
SELECT actor_id, first_name, last_name
FROM actor
WHERE last_name LIKE 'J%';

Running query in 'mysql+pymysql://root:***@localhost:3306/sakila'

7 rows affected.

++
||
++
++

In [4]:
%%sql
SELECT * FROM actors_j;

Running query in 'mysql+pymysql://root:***@localhost:3306/sakila'

7 rows affected.

+----------+------------+-----------+
| actor_id | first_name | last_name |
+----------+------------+-----------+
|   119    |   WARREN   |  JACKMAN  |
|   131    |    JANE    |  JACKMAN  |
|    8     |  MATTHEW   | JOHANSSON |
|    64    |    RAY     | JOHANSSON |
|   146    |   ALBERT   | JOHANSSON |
|    82    |   WOODY    |   JOLIE   |
|    43    |    KIRK    |  JOVOVICH |
+----------+------------+-----------+

### Представления

In [5]:
%%sql
CREATE VIEW cust_vw
AS
SELECT customer_id, first_name, last_name, active
FROM customer;

Running query in 'mysql+pymysql://root:***@localhost:3306/sakila'

++
||
++
++

In [6]:
%%sql
SELECT first_name, last_name
FROM cust_vw
WHERE active = 0;

Running query in 'mysql+pymysql://root:***@localhost:3306/sakila'

15 rows affected.

+------------+-----------+
| first_name | last_name |
+------------+-----------+
|   SANDRA   |   MARTIN  |
|   JUDITH   |    COX    |
|   SHEILA   |   WELLS   |
|   ERICA    |  MATTHEWS |
|   HEIDI    |   LARSON  |
|   PENNY    |    NEAL   |
|  KENNETH   |   GOODEN  |
|   HARRY    |    ARCE   |
|   NATHAN   |   RUNYON  |
|  THEODORE  |    CULP   |
|  MAURICE   |  CRAWLEY  |
|    BEN     |   EASTER  |
| CHRISTIAN  |    JUNG   |
|   JIMMIE   | EGGLESTON |
|  TERRANCE  |   ROUSH   |
+------------+-----------+

### Связи таблиц

In [7]:
%%sql
SELECT
    customer.first_name,
    customer.last_name,
    TIME(rental.rental_date) rental_time
FROM customer
    INNER JOIN rental
    ON customer.customer_id = rental.customer_id
WHERE date(rental.rental_date) = '2005-06-14';

Running query in 'mysql+pymysql://root:***@localhost:3306/sakila'

16 rows affected.

+------------+-----------+-------------+
| first_name | last_name | rental_time |
+------------+-----------+-------------+
|  JEFFERY   |   PINSON  |   22:53:33  |
|   ELMER    |    NOE    |   22:55:13  |
|   MINNIE   |   ROMERO  |   23:00:34  |
|   MIRIAM   |  MCKINNEY |   23:07:08  |
|   DANIEL   |   CABRAL  |   23:09:38  |
|  TERRANCE  |   ROUSH   |   23:12:46  |
|   JOYCE    |  EDWARDS  |   23:16:26  |
| GWENDOLYN  |    MAY    |   23:16:27  |
| CATHERINE  |  CAMPBELL |   23:17:03  |
|  MATTHEW   |   MAHAN   |   23:25:58  |
|   HERMAN   |   DEVORE  |   23:35:09  |
|   AMBER    |   DIXON   |   23:42:56  |
|  TERRENCE  | GUNDERSON |   23:47:35  |
|   SONIA    |  GREGORY  |   23:50:11  |
|  CHARLES   |  KOWALSKI |   23:54:34  |
|  JEANETTE  |   GREENE  |   23:54:46  |
+------------+-----------+-------------+

### Определение псевдонимов таблиц

In [ ]:
%%sql
SELECT c.first_name, c.last_name,
  TIME(r.rental_date) rental_time
FROM customer c
  INNER JOIN rental r
  ON c.customer_id = r.customer_id
WHERE date(r.rental_date) = '2005-06-14';

In [10]:
%%sql
SELECT c.first_name, c.last_name,
  TIME(r.rental_date) rental_time
FROM customer AS c
  INNER JOIN rental AS r
  ON c.customer_id = r.customer_id
WHERE date(r.rental_date) = '2005-06-14';

Running query in 'mysql+pymysql://root:***@localhost:3306/sakila'

16 rows affected.

+------------+-----------+-------------+
| first_name | last_name | rental_time |
+------------+-----------+-------------+
|  JEFFERY   |   PINSON  |   22:53:33  |
|   ELMER    |    NOE    |   22:55:13  |
|   MINNIE   |   ROMERO  |   23:00:34  |
|   MIRIAM   |  MCKINNEY |   23:07:08  |
|   DANIEL   |   CABRAL  |   23:09:38  |
|  TERRANCE  |   ROUSH   |   23:12:46  |
|   JOYCE    |  EDWARDS  |   23:16:26  |
| GWENDOLYN  |    MAY    |   23:16:27  |
| CATHERINE  |  CAMPBELL |   23:17:03  |
|  MATTHEW   |   MAHAN   |   23:25:58  |
|   HERMAN   |   DEVORE  |   23:35:09  |
|   AMBER    |   DIXON   |   23:42:56  |
|  TERRENCE  | GUNDERSON |   23:47:35  |
|   SONIA    |  GREGORY  |   23:50:11  |
|  CHARLES   |  KOWALSKI |   23:54:34  |
|  JEANETTE  |   GREENE  |   23:54:46  |
+------------+-----------+-------------+

## Предложение *where*

In [11]:
%%sql
SELECT title
FROM film
WHERE rating = 'G' AND rental_duration >= 7;

Running query in 'mysql+pymysql://root:***@localhost:3306/sakila'

29 rows affected.

+-------------------------+
|          title          |
+-------------------------+
|     BLANKET BEVERLY     |
|   BORROWERS BEDAZZLED   |
|      BRIDE INTRIGUE     |
|      CATCH AMISTAD      |
|      CITIZEN SHREK      |
|   COLDBLOODED DARLING   |
|      CONTROL ANTHEM     |
|    CRUELTY UNFORGIVEN   |
|      DARN FORRESTER     |
| DESPERATE TRAINSPOTTING |
|       DIARY PANIC       |
|     DRACULA CRYSTAL     |
|     EMPIRE MALKOVICH    |
|    FIREHOUSE VIETNAM    |
|     GILBERT PELICAN     |
|      GRADUATE LORD      |
|       GREASE YOUTH      |
|        GUN BONNIE       |
|      HOOK CHARIOTS      |
|        MARRIED GO       |
+-------------------------+
Truncated to displaylimit of 20.

:::{tip} Чтобы следующий запрос не выводил все 340 строк
:class: dropdown
:open: true

Cнова включим автоматическое преобразование.  
Только на этот раз в `Polars DataFrame` (интересно же).
:::

In [2]:
import polars as pl
print(pl.__version__)

1.42.1

In [7]:
# Включаем автопреобразование в Polars DataFrame
%config SqlMagic.autopolars = True

In [4]:
%%sql
SELECT title
FROM film
WHERE rating = 'G' OR rental_duration >= 7;

Running query in 'mysql+pymysql://root:***@localhost:3306/sakila'

340 rows affected.

shape: (340, 1)
┌─────────────────────┐
│ title               │
│ ---                 │
│ str                 │
╞═════════════════════╡
│ ACE GOLDFINGER      │
│ ADAPTATION HOLES    │
│ AFFAIR PREJUDICE    │
│ AFRICAN EGG         │
│ ALAMO VIDEOTAPE     │
│ …                   │
│ WESTWARD SEABISCUIT │
│ WOLVES DESIRE       │
│ WON DARES           │
│ WORKER TARZAN       │
│ YOUNG LANGUAGE      │
└─────────────────────┘

In [5]:
type(_)

polars.dataframe.frame.DataFrame

In [8]:
%%sql
SELECT title, rating, rental_duration
FROM film
WHERE (rating = 'G' AND rental_duration >=7)
    OR (rating = 'PG-13' AND rental_duration < 4);

Running query in 'mysql+pymysql://root:***@localhost:3306/sakila'

68 rows affected.

shape: (68, 3)
┌─────────────────────┬────────┬─────────────────┐
│ title               ┆ rating ┆ rental_duration │
│ ---                 ┆ ---    ┆ ---             │
│ str                 ┆ str    ┆ i64             │
╞═════════════════════╪════════╪═════════════════╡
│ ALABAMA DEVIL       ┆ PG-13  ┆ 3               │
│ BACKLASH UNDEFEATED ┆ PG-13  ┆ 3               │
│ BILKO ANONYMOUS     ┆ PG-13  ┆ 3               │
│ BLANKET BEVERLY     ┆ G      ┆ 7               │
│ BORROWERS BEDAZZLED ┆ G      ┆ 7               │
│ …                   ┆ …      ┆ …               │
│ TRUMAN CRAZY        ┆ G      ┆ 7               │
│ WAIT CIDER          ┆ PG-13  ┆ 3               │
│ WAKE JAWS           ┆ G      ┆ 7               │
│ WAR NOTTING         ┆ G      ┆ 7               │
│ WORLD LEATHERNECKS  ┆ PG-13  ┆ 3               │
└─────────────────────┴────────┴─────────────────┘

In [ ]:
# Отключаем автопреобразование в Polars DataFrame
%config SqlMagic.autopolars = False

:::{tip} Pandas vs Polars
:class: dropdown
:open: true

В поиске оптимального решения **для вывода усеченных строк** – чтобы вывод показывал начало и конец через многоточие вместо вывода всех строк – опробовали `Pandas` и `Polars`.

- `Pandas`: отображает значения как в выводе SQL, но добавляет слева поле индекса. _Потому что с точки зрения философии Pandas, датафрейм без индекса существовать не может._
- `Polars`: выводит результат запроса без индекса, но строковые значения отображает в кавычках. _Потому что с точки зрения философии Polars, визуальная валидация типов и контроль скрытых символов важнее классической визуальной эстетики текста._
:::

## Предложения *group by* и *having*